#############################################################################
# Makefile for building: genledg
# Generated by qmake (1.07a) (Qt 3.3.2) on: Mon Jul 12 15:10:28 2004
# Project:  genledg.pro
# Template: app
# Command: $(QMAKE) -o Makefile genledg.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O3 -march=athlon-xp  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O3 -march=athlon-xp  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/qt/mkspecs/default -I. -I. -Iinclude -I$(QTDIR)/include
LINK     = g++
LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm $(LDFLAGS)
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = include/accountStack.h \
		include/accountTable.h \
		include/generalLedger.h \
		include/goBackLabel.h \
		include/journalStack.h \
		include/journalTable.h \
		include/mainStack.h \
		include/reportStack.h
SOURCES = src/accountStack.cpp \
		src/accountTable.cpp \
		src/generalLedger.cpp \
		src/goBackLabel.cpp \
		src/journalStack.cpp \
		src/journalTable.cpp \
		src/main.cpp \
		src/mainStack.cpp \
		src/reportStack.cpp
OBJECTS = accountStack.o \
		accountTable.o \
		generalLedger.o \
		goBackLabel.o \
		journalStack.o \
		journalTable.o \
		main.o \
		mainStack.o \
		reportStack.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = include/moc_accountStack.cpp \
		include/moc_generalLedger.cpp \
		include/moc_goBackLabel.cpp \
		include/moc_journalStack.cpp \
		include/moc_mainStack.cpp \
		include/moc_reportStack.cpp
OBJMOC = moc_accountStack.o \
		moc_generalLedger.o \
		moc_goBackLabel.o \
		moc_journalStack.o \
		moc_mainStack.o \
		moc_reportStack.o
DIST	   = genledg.pro
QMAKE_TARGET = genledg
DESTDIR  = 
TARGET   = genledg

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: genledg.pro  /usr/qt/mkspecs/default/qmake.conf /usr/qt/lib/libqt-mt.prl
	$(QMAKE) -o Makefile genledg.pro
qmake: 
	@$(QMAKE) -o Makefile genledg.pro

dist: 
	@mkdir -p .tmp/genledg && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/genledg/ && ( cd `dirname .tmp/genledg` && $(TAR) genledg.tar genledg && $(GZIP) genledg.tar ) && $(MOVE) `dirname .tmp/genledg`/genledg.tar.gz . && $(DEL_FILE) -r .tmp/genledg

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

accountStack.o: src/accountStack.cpp include/accountStack.h \
		include/accountTable.h \
		include/goBackLabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accountStack.o src/accountStack.cpp

accountTable.o: src/accountTable.cpp include/accountTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accountTable.o src/accountTable.cpp

generalLedger.o: src/generalLedger.cpp include/generalLedger.h \
		include/mainStack.h \
		include/accountStack.h \
		include/journalStack.h \
		include/reportStack.h \
		include/goBackLabel.h \
		include/accountTable.h \
		include/journalTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generalLedger.o src/generalLedger.cpp

goBackLabel.o: src/goBackLabel.cpp include/goBackLabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goBackLabel.o src/goBackLabel.cpp

journalStack.o: src/journalStack.cpp include/journalStack.h \
		include/journalTable.h \
		include/goBackLabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o journalStack.o src/journalStack.cpp

journalTable.o: src/journalTable.cpp include/journalTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o journalTable.o src/journalTable.cpp

main.o: src/main.cpp include/generalLedger.h \
		include/mainStack.h \
		include/accountStack.h \
		include/journalStack.h \
		include/reportStack.h \
		include/goBackLabel.h \
		include/accountTable.h \
		include/journalTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainStack.o: src/mainStack.cpp include/mainStack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainStack.o src/mainStack.cpp

reportStack.o: src/reportStack.cpp include/reportStack.h \
		include/goBackLabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reportStack.o src/reportStack.cpp

moc_accountStack.o: include/moc_accountStack.cpp  include/accountStack.h include/goBackLabel.h \
		include/accountTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accountStack.o include/moc_accountStack.cpp

moc_generalLedger.o: include/moc_generalLedger.cpp  include/generalLedger.h include/mainStack.h \
		include/accountStack.h \
		include/journalStack.h \
		include/reportStack.h \
		include/goBackLabel.h \
		include/accountTable.h \
		include/journalTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_generalLedger.o include/moc_generalLedger.cpp

moc_goBackLabel.o: include/moc_goBackLabel.cpp  include/goBackLabel.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_goBackLabel.o include/moc_goBackLabel.cpp

moc_journalStack.o: include/moc_journalStack.cpp  include/journalStack.h include/goBackLabel.h \
		include/journalTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_journalStack.o include/moc_journalStack.cpp

moc_mainStack.o: include/moc_mainStack.cpp  include/mainStack.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainStack.o include/moc_mainStack.cpp

moc_reportStack.o: include/moc_reportStack.cpp  include/reportStack.h include/goBackLabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reportStack.o include/moc_reportStack.cpp

include/moc_accountStack.cpp: $(MOC) include/accountStack.h
	$(MOC) include/accountStack.h -o include/moc_accountStack.cpp

include/moc_generalLedger.cpp: $(MOC) include/generalLedger.h
	$(MOC) include/generalLedger.h -o include/moc_generalLedger.cpp

include/moc_goBackLabel.cpp: $(MOC) include/goBackLabel.h
	$(MOC) include/goBackLabel.h -o include/moc_goBackLabel.cpp

include/moc_journalStack.cpp: $(MOC) include/journalStack.h
	$(MOC) include/journalStack.h -o include/moc_journalStack.cpp

include/moc_mainStack.cpp: $(MOC) include/mainStack.h
	$(MOC) include/mainStack.h -o include/moc_mainStack.cpp

include/moc_reportStack.cpp: $(MOC) include/reportStack.h
	$(MOC) include/reportStack.h -o include/moc_reportStack.cpp

####### Install

install:  

uninstall:  

