ReportStack Class Reference
#include <reportStack.h>
Signals
void goToMain ()
Public Member Functions
ReportStack (QWidget *parent=0, const char *name=0)
~ReportStack ()
Private Slots
void detailAccountsAllChanged (bool)
void trialAccountsAllChanged (bool)
void dbOpened ()
void updateAccounts ()
void viewReport (QString &text)
void exportPDF ()
void exportCSV ()
void switchWidget ()
void generalDetailReport ()
void generalTrialReport ()
void chartAccountsReport ()
void balanceReport ()
void incomeSvcReport ()
void incomeRetailReport ()
void switchToEditBalance ()
void switchToEditIncomeSvc ()
void switchToEditIncomeRetail ()
void print ()
Private Member Functions
bool eventFilter (QObject *target, QEvent *event)
Private Attributes
Database * db
Settings * settings
Printer * printer
QString clientPath
QString exportPath
QString importPath
int active
QStringList accounts
xx xx xx xx xx xx xx xx xx
struct {
 QWidget * widget
 QVBoxLayout * vBoxLabel
 QHBoxLayout * hBoxLabel
 GoBackLabel * topLabel
 QHBoxLayout * hBoxLayout
 QVBoxLayout * vBoxLayout
 QVGroupBox * reportsGroup
 QWidget * reportsWidget
 QGridLayout * reportsGridLayout
 QVGroupBox * generalDetailVGroupBox
 QWidget * generalDetailDateRangeWidget
 QHBoxLayout * generalDetailDateRangeHBoxLayout
 QLabel * generalDetailDateRangeLabelBegin
 QComboBox * generalDetailDateRangeBegin
 QLabel * generalDetailDateRangeLabelBetween
 QComboBox * generalDetailDateRangeEnd
 QWidget * generalDetailAccountRangeWidget
 QHBoxLayout * generalDetailAccountRangeHBoxLayout
 QLabel * generalDetailAccountRangeLabel
 AccountList * generalDetailAccountRangeBegin
 QLabel * generalDetailAccountRangeLabelBetween
 AccountList * generalDetailAccountRangeEnd
 QCheckBox * generalDetailAccountRangeAll
 QVBoxLayout * generalDetailButtonVBoxLayout
 QPushButton * generalDetailButton
 QVGroupBox * generalTrialVGroupBox
 QWidget * generalTrialMonthEndWidget
 QHBoxLayout * generalTrialMonthEndHBoxLayout
 QLabel * generalTrialMonthEndLabel
 QComboBox * generalTrialMonthEndList
 QWidget * generalTrialAccountRangeWidget
 QHBoxLayout * generalTrialAccountRangeHBoxLayout
 QLabel * generalTrialAccountRangeLabel
 AccountList * generalTrialAccountRangeBegin
 QLabel * generalTrialAccountRangeLabelBetween
 AccountList * generalTrialAccountRangeEnd
 QCheckBox * generalTrialAccountRangeAll
 QVBoxLayout * generalTrialButtonVBoxLayout
 QPushButton * generalTrialButton
 QVGroupBox * balanceVGroupBox
 QWidget * balanceMonthEndWidget
 QHBoxLayout * balanceMonthEndHBoxLayout
 QLabel * balanceMonthEndLabel
 QComboBox * balanceMonthEndList
 QWidget * balanceModifyWidget
 QHBoxLayout * balanceModifyHBoxLayout
 QPushButton * balanceModifyButton
 QVBoxLayout * balanceReportButtonVBoxLayout
 QPushButton * balanceReportButton
 QVGroupBox * incomeSvcVGroupBox
 QWidget * incomeSvcMonthEndWidget
 QHBoxLayout * incomeSvcMonthEndHBoxLayout
 QLabel * incomeSvcMonthEndLabel
 QComboBox * incomeSvcMonthEndList
 QWidget * incomeSvcModifyWidget
 QHBoxLayout * incomeSvcModifyHBoxLayout
 QPushButton * incomeSvcModifyButton
 QVBoxLayout * incomeSvcButtonVBoxLayout
 QPushButton * incomeSvcButton
 QVGroupBox * incomeRetailVGroupBox
 QWidget * incomeRetailMonthEndWidget
 QHBoxLayout * incomeRetailMonthEndHBoxLayout
 QLabel * incomeRetailMonthEndLabel
 QComboBox * incomeRetailMonthEndList
 QWidget * incomeRetailModifyWidget
 QHBoxLayout * incomeRetailModifyHBoxLayout
 QPushButton * incomeRetailModifyButton
 QVBoxLayout * incomeRetailButtonVBoxLayout
 QPushButton * incomeRetailButton
 QVBoxLayout * chartAccountsButtonVBoxLayout
 QPushButton * chartAccountsButton
} main
xx xx xx xx xx xx xx xx xx
struct {
 QWidget * widget
 QVBoxLayout * vBoxLayout
 QBoxLayout * labelLayout
 GoBackLabel * topLabel
 QPushButton * print
 QTextEdit * view
 QWidget * bottomWidget
 QHBoxLayout * bottomHBoxLayout
 QLabel * bottomLabel
 QFrame * bottomRightFrame
 QBoxLayout * bottomRightBoxLayout
 QPushButton * exportPDFButton
 QPushButton * exportCSVButton
} report
xx xx xx xx xx xx xx xx xx
struct {
 QWidget * widget
 QVBoxLayout * vBoxLayout
 QBoxLayout * labelLayout
 GoBackLabel * topLabel
 BalanceSheetEditor * editor
} balance
xx xx xx xx xx xx xx xx xx
struct {
 QWidget * widget
 QVBoxLayout * vBoxLayout
 QBoxLayout * labelLayout
 GoBackLabel * topLabel
 IncomeSvcEditor * editor
} incomeSvc
xx xx xx xx xx xx xx xx xx
struct {
 QWidget * widget
 QVBoxLayout * vBoxLayout
 QBoxLayout * labelLayout
 GoBackLabel * topLabel
 IncomeRetailEditor * editor
} incomeRetail
Constructor & Destructor Documentation
ReportStack::ReportStack (QWidget * parent = 0, const char * name = 0)
Definition at line 37 of file reportStack.cpp.
References accounts, active, balanceReport(), chartAccountsReport(), clientPath, db, detailAccountsAllChanged(), exportCSV(), exportPath, exportPDF(), generalDetailReport(), generalTrialReport(), Settings::getClientPath(), Settings::getExportPath(), Settings::getImportPath(), goToMain(), importPath, incomeRetailReport(), incomeSvcReport(), Printer::instance(), Settings::instance(), Database::instance(), main, print(), printer, report, settings, switchToEditBalance(), switchToEditIncomeRetail(), switchToEditIncomeSvc(), switchWidget(), trialAccountsAllChanged(), and updateAccounts().
38 : QWidgetStack(parent,name)
39
40 db = Database::instance();
41 settings = Settings::instance();
42 printer = Printer::instance();
43
44 clientPath = settings->getClientPath();
45 exportPath = settings->getExportPath();
46 importPath = settings->getImportPath();
47
48 connect(db, SIGNAL(accountsChanged()), this, SLOT(updateAccounts()));
49 accounts = QStringList(" "); // set a placeholder width
50
51 QStringList periodTmp("Period X (00/00/00)"); // placeholder for combobox sizes
52
53 main.widget = new QWidget(this);
54
55 main.vBoxLabel = new QVBoxLayout(main.widget);
56
57 main.hBoxLabel = new QHBoxLayout(main.vBoxLabel);
58 main.hBoxLabel->setMargin(5);
59
60 main.topLabel = new GoBackLabel(main.widget);
61 connect(main.topLabel, SIGNAL(goBack()), this, SIGNAL(goToMain()));
62
63 main.hBoxLabel->addWidget(main.topLabel);
64 main.hBoxLabel->addStretch();
65
66 main.hBoxLayout = new QHBoxLayout(main.vBoxLabel);
67
68 main.hBoxLayout->addStretch();
69
70 main.vBoxLayout = new QVBoxLayout(main.hBoxLayout);
71 main.vBoxLayout->setSpacing(30);
72
73 main.vBoxLayout->addStretch();
74
75
76 main.reportsGroup = new QVGroupBox("Reports", main.widget);
77 main.reportsGroup->setInsideMargin(30);
78 main.reportsGroup->setInsideSpacing(20);
79
80 main.vBoxLayout->add(main.reportsGroup);
81
82 main.reportsWidget = new QWidget(main.reportsGroup);
83
84 main.reportsGridLayout = new QGridLayout(main.reportsWidget, 6, 2, 0, 15); // rows, cols, margin, spacing
85
86
87 main.generalDetailVGroupBox = new QVGroupBox(main.reportsWidget);
88 main.generalDetailVGroupBox->setInsideSpacing(5);
89
90 main.generalDetailDateRangeWidget = new QWidget(main.generalDetailVGroupBox);
91 main.generalDetailDateRangeHBoxLayout = new QHBoxLayout(main.generalDetailDateRangeWidget);
92 main.generalDetailDateRangeHBoxLayout->setSpacing(5);
93
94 main.generalDetailDateRangeLabelBegin = new QLabel("Date Range:", main.generalDetailDateRangeWidget);
95 main.generalDetailDateRangeBegin = new QComboBox(main.generalDetailDateRangeWidget);
96 main.generalDetailDateRangeBegin->setFocus();
97 main.generalDetailDateRangeBegin->installEventFilter(this);
98 main.generalDetailDateRangeBegin->insertStringList(periodTmp);
99 main.generalDetailDateRangeLabelBetween = new QLabel("to", main.generalDetailDateRangeWidget);
100 main.generalDetailDateRangeEnd = new QComboBox(main.generalDetailDateRangeWidget);
101 main.generalDetailDateRangeEnd->installEventFilter(this);
102 main.generalDetailDateRangeEnd->insertStringList(periodTmp);
103
104 main.generalDetailDateRangeHBoxLayout->addWidget(main.generalDetailDateRangeLabelBegin);
105 main.generalDetailDateRangeHBoxLayout->addWidget(main.generalDetailDateRangeBegin);
106 main.generalDetailDateRangeHBoxLayout->addWidget(main.generalDetailDateRangeLabelBetween);
107 main.generalDetailDateRangeHBoxLayout->addWidget(main.generalDetailDateRangeEnd);
108 main.generalDetailDateRangeHBoxLayout->addStretch();
109
110 main.generalDetailAccountRangeWidget = new QWidget(main.generalDetailVGroupBox);
111 main.generalDetailAccountRangeHBoxLayout = new QHBoxLayout(main.generalDetailAccountRangeWidget);
112 main.generalDetailAccountRangeHBoxLayout->setSpacing(5);
113
114 main.generalDetailAccountRangeLabel = new QLabel("Account Range:", main.generalDetailAccountRangeWidget);
115 main.generalDetailAccountRangeAll = new QCheckBox("All", main.generalDetailAccountRangeWidget);
116 main.generalDetailAccountRangeAll->installEventFilter(this);
117 main.generalDetailAccountRangeAll->setChecked(true);
118 connect(main.generalDetailAccountRangeAll, SIGNAL(toggled(bool)), this, SLOT(detailAccountsAllChanged(bool)));
119 main.generalDetailAccountRangeBegin = new AccountList(main.generalDetailAccountRangeWidget, 0, accounts);
120 main.generalDetailAccountRangeBegin->installEventFilter(this);
121 main.generalDetailAccountRangeBegin->setEnabled(false);
122 main.generalDetailAccountRangeLabelBetween = new QLabel("to", main.generalDetailAccountRangeWidget);
123 main.generalDetailAccountRangeLabelBetween->setEnabled(false);
124 main.generalDetailAccountRangeEnd = new AccountList(main.generalDetailAccountRangeWidget, 0, accounts);
125 main.generalDetailAccountRangeEnd->installEventFilter(this);
126 main.generalDetailAccountRangeEnd->setEnabled(false);
127
128 main.generalDetailAccountRangeHBoxLayout->addWidget(main.generalDetailAccountRangeLabel);
129 main.generalDetailAccountRangeHBoxLayout->addWidget(main.generalDetailAccountRangeAll);
130 main.generalDetailAccountRangeHBoxLayout->addWidget(main.generalDetailAccountRangeBegin);
131 main.generalDetailAccountRangeHBoxLayout->addWidget(main.generalDetailAccountRangeLabelBetween);
132 main.generalDetailAccountRangeHBoxLayout->addWidget(main.generalDetailAccountRangeEnd);
133 main.generalDetailAccountRangeHBoxLayout->addStretch();
134
135 main.generalDetailButtonVBoxLayout = new QVBoxLayout();
136 main.generalDetailButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/generalDetailReport.png")),
137 "General Ledger Detail", main.reportsWidget);
138 connect(main.generalDetailButton, SIGNAL(clicked()), this, SLOT(generalDetailReport()));
139 main.generalDetailButton->setDefault(true);
140 main.generalDetailButton->installEventFilter(this);
141 main.generalDetailButtonVBoxLayout->addWidget(main.generalDetailButton);
142
143 main.reportsGridLayout->addWidget(main.generalDetailVGroupBox, 0, 0);
144 main.reportsGridLayout->addLayout(main.generalDetailButtonVBoxLayout, 0, 1);
145
146
147 main.generalTrialVGroupBox = new QVGroupBox(main.reportsWidget);
148 main.generalTrialVGroupBox->setInsideSpacing(5);
149
150 main.generalTrialMonthEndWidget = new QWidget(main.generalTrialVGroupBox);
151 main.generalTrialMonthEndHBoxLayout = new QHBoxLayout(main.generalTrialMonthEndWidget);
152 main.generalTrialMonthEndHBoxLayout->setSpacing(5);
153
154 main.generalTrialMonthEndLabel = new QLabel("Month-End:", main.generalTrialMonthEndWidget);
155 main.generalTrialMonthEndList = new QComboBox(main.generalTrialMonthEndWidget);
156 main.generalTrialMonthEndList->installEventFilter(this);
157 main.generalTrialMonthEndList->insertStringList(periodTmp);
158
159 main.generalTrialMonthEndHBoxLayout->addWidget(main.generalTrialMonthEndLabel);
160 main.generalTrialMonthEndHBoxLayout->addWidget(main.generalTrialMonthEndList);
161 main.generalTrialMonthEndHBoxLayout->addStretch();
162
163 main.generalTrialAccountRangeWidget = new QWidget(main.generalTrialVGroupBox);
164 main.generalTrialAccountRangeHBoxLayout = new QHBoxLayout(main.generalTrialAccountRangeWidget);
165 main.generalTrialAccountRangeHBoxLayout->setSpacing(5);
166
167 main.generalTrialAccountRangeLabel = new QLabel("Account Range:", main.generalTrialAccountRangeWidget);
168 main.generalTrialAccountRangeAll = new QCheckBox("All", main.generalTrialAccountRangeWidget);
169 main.generalTrialAccountRangeAll->installEventFilter(this);
170 main.generalTrialAccountRangeAll->setChecked(true);
171 connect(main.generalTrialAccountRangeAll, SIGNAL(toggled(bool)), this, SLOT(trialAccountsAllChanged(bool)));
172 main.generalTrialAccountRangeBegin = new AccountList(main.generalTrialAccountRangeWidget, 0, accounts);
173 main.generalTrialAccountRangeBegin->installEventFilter(this);
174 main.generalTrialAccountRangeBegin->setEnabled(false);
175 main.generalTrialAccountRangeLabelBetween = new QLabel("to", main.generalTrialAccountRangeWidget);
176 main.generalTrialAccountRangeLabelBetween->setEnabled(false);
177 main.generalTrialAccountRangeEnd = new AccountList(main.generalTrialAccountRangeWidget, 0, accounts);
178 main.generalTrialAccountRangeEnd->installEventFilter(this);
179 main.generalTrialAccountRangeEnd->setEnabled(false);
180
181 main.generalTrialAccountRangeHBoxLayout->addWidget(main.generalTrialAccountRangeLabel);
182 main.generalTrialAccountRangeHBoxLayout->addWidget(main.generalTrialAccountRangeAll);
183 main.generalTrialAccountRangeHBoxLayout->addWidget(main.generalTrialAccountRangeBegin);
184 main.generalTrialAccountRangeHBoxLayout->addWidget(main.generalTrialAccountRangeLabelBetween);
185 main.generalTrialAccountRangeHBoxLayout->addWidget(main.generalTrialAccountRangeEnd);
186 main.generalTrialAccountRangeHBoxLayout->addStretch();
187
188 main.generalTrialButtonVBoxLayout = new QVBoxLayout();
189 main.generalTrialButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/generalTrialReport.png")),
190 "General Trial Balance", main.reportsWidget);
191 connect(main.generalTrialButton, SIGNAL(clicked()), this, SLOT(generalTrialReport()));
192 main.generalTrialButton->installEventFilter(this);
193 main.generalTrialButtonVBoxLayout->addWidget(main.generalTrialButton);
194
195 main.reportsGridLayout->addWidget(main.generalTrialVGroupBox, 1, 0);
196 main.reportsGridLayout->addLayout(main.generalTrialButtonVBoxLayout, 1, 1);
197
198
199 main.balanceVGroupBox = new QVGroupBox(main.reportsWidget);
200 main.balanceVGroupBox->setInsideSpacing(5);
201
202 main.balanceMonthEndWidget = new QWidget(main.balanceVGroupBox);
203 main.balanceMonthEndHBoxLayout = new QHBoxLayout(main.balanceMonthEndWidget);
204 main.balanceMonthEndHBoxLayout->setSpacing(5);
205
206 main.balanceMonthEndLabel = new QLabel("Month-End:", main.balanceMonthEndWidget);
207 main.balanceMonthEndList = new QComboBox(main.balanceMonthEndWidget);
208 main.balanceMonthEndList->installEventFilter(this);
209 main.balanceMonthEndList->insertStringList(periodTmp);
210
211 main.balanceMonthEndHBoxLayout->addWidget(main.balanceMonthEndLabel);
212 main.balanceMonthEndHBoxLayout->addWidget(main.balanceMonthEndList);
213 main.balanceMonthEndHBoxLayout->addStretch();
214
215 main.balanceModifyWidget = new QWidget(main.balanceVGroupBox);
216 main.balanceModifyHBoxLayout = new QHBoxLayout(main.balanceModifyWidget);
217
218 main.balanceModifyButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/modifyReport.png")),
219 "Modify Balance Sheet", main.balanceModifyWidget);
220 connect(main.balanceModifyButton, SIGNAL(clicked()), this, SLOT(switchToEditBalance()));
221 main.balanceModifyButton->installEventFilter(this);
222
223 main.balanceModifyHBoxLayout->addWidget(main.balanceModifyButton);
224 main.balanceModifyHBoxLayout->addStretch();
225
226 main.balanceReportButtonVBoxLayout = new QVBoxLayout();
227 main.balanceReportButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/balanceReport.png")),
228 "Balance Sheet Report", main.reportsWidget);
229 connect(main.balanceReportButton, SIGNAL(clicked()), this, SLOT(balanceReport()));
230 main.balanceReportButton->installEventFilter(this);
231 main.balanceReportButtonVBoxLayout->addWidget(main.balanceReportButton);
232
233
234 main.reportsGridLayout->addWidget(main.balanceVGroupBox, 2, 0);
235 main.reportsGridLayout->addLayout(main.balanceReportButtonVBoxLayout, 2, 1);
236
237
238 main.incomeSvcVGroupBox = new QVGroupBox(main.reportsWidget);
239 main.incomeSvcVGroupBox->setInsideSpacing(5);
240
241 main.incomeSvcMonthEndWidget = new QWidget(main.incomeSvcVGroupBox);
242 main.incomeSvcMonthEndHBoxLayout = new QHBoxLayout(main.incomeSvcMonthEndWidget);
243 main.incomeSvcMonthEndHBoxLayout->setSpacing(5);
244
245 main.incomeSvcMonthEndLabel = new QLabel("Month-End:", main.incomeSvcMonthEndWidget);
246 main.incomeSvcMonthEndList = new QComboBox(main.incomeSvcMonthEndWidget);
247 main.incomeSvcMonthEndList->installEventFilter(this);
248 main.incomeSvcMonthEndList->insertStringList(periodTmp);
249
250 main.incomeSvcMonthEndHBoxLayout->addWidget(main.incomeSvcMonthEndLabel);
251 main.incomeSvcMonthEndHBoxLayout->addWidget(main.incomeSvcMonthEndList);
252 main.incomeSvcMonthEndHBoxLayout->addStretch();
253
254 main.incomeSvcModifyWidget = new QWidget(main.incomeSvcVGroupBox);
255 main.incomeSvcModifyHBoxLayout = new QHBoxLayout(main.incomeSvcModifyWidget);
256
257 main.incomeSvcModifyButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/modifyReport.png")),
258 "Modify Income Statement Svc. Co.", main.incomeSvcModifyWidget);
259 connect(main.incomeSvcModifyButton, SIGNAL(clicked()), this, SLOT(switchToEditIncomeSvc()));
260 main.incomeSvcModifyButton->installEventFilter(this);
261
262 main.incomeSvcModifyHBoxLayout->addWidget(main.incomeSvcModifyButton);
263 main.incomeSvcModifyHBoxLayout->addStretch();
264
265 main.incomeSvcButtonVBoxLayout = new QVBoxLayout();
266 main.incomeSvcButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/incomeReport.png")),
267 "Income Statement Svc. Co.", main.reportsWidget);
268 connect(main.incomeSvcButton, SIGNAL(clicked()), this, SLOT(incomeSvcReport()));
269 main.incomeSvcButton->installEventFilter(this);
270 main.incomeSvcButtonVBoxLayout->addWidget(main.incomeSvcButton);
271
272
273 main.reportsGridLayout->addWidget(main.incomeSvcVGroupBox, 3, 0);
274 main.reportsGridLayout->addLayout(main.incomeSvcButtonVBoxLayout, 3, 1);
275
276
277
278 main.incomeRetailVGroupBox = new QVGroupBox(main.reportsWidget);
279 main.incomeRetailVGroupBox->setInsideSpacing(5);
280
281 main.incomeRetailMonthEndWidget = new QWidget(main.incomeRetailVGroupBox);
282 main.incomeRetailMonthEndHBoxLayout = new QHBoxLayout(main.incomeRetailMonthEndWidget);
283 main.incomeRetailMonthEndHBoxLayout->setSpacing(5);
284
285 main.incomeRetailMonthEndLabel = new QLabel("Month-End:", main.incomeRetailMonthEndWidget);
286 main.incomeRetailMonthEndList = new QComboBox(main.incomeRetailMonthEndWidget);
287 main.incomeRetailMonthEndList->installEventFilter(this);
288 main.incomeRetailMonthEndList->insertStringList(periodTmp);
289
290 main.incomeRetailMonthEndHBoxLayout->addWidget(main.incomeRetailMonthEndLabel);
291 main.incomeRetailMonthEndHBoxLayout->addWidget(main.incomeRetailMonthEndList);
292 main.incomeRetailMonthEndHBoxLayout->addStretch();
293
294 main.incomeRetailModifyWidget = new QWidget(main.incomeRetailVGroupBox);
295 main.incomeRetailModifyHBoxLayout = new QHBoxLayout(main.incomeRetailModifyWidget);
296
297 main.incomeRetailModifyButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/modifyReport.png")),
298 "Modify Income Statement Retail", main.incomeRetailModifyWidget);
299 connect(main.incomeRetailModifyButton, SIGNAL(clicked()), this, SLOT(switchToEditIncomeRetail()));
300 main.incomeRetailModifyButton->installEventFilter(this);
301
302 main.incomeRetailModifyHBoxLayout->addWidget(main.incomeRetailModifyButton);
303 main.incomeRetailModifyHBoxLayout->addStretch();
304
305 main.incomeRetailButtonVBoxLayout = new QVBoxLayout();
306 main.incomeRetailButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/incomeReport.png")),
307 "Income Statement Retail", main.reportsWidget);
308 connect(main.incomeRetailButton, SIGNAL(clicked()), this, SLOT(incomeRetailReport()));
309 main.incomeRetailButton->installEventFilter(this);
310 main.incomeRetailButtonVBoxLayout->addWidget(main.incomeRetailButton);
311
312
313 main.reportsGridLayout->addWidget(main.incomeRetailVGroupBox, 4, 0);
314 main.reportsGridLayout->addLayout(main.incomeRetailButtonVBoxLayout, 4, 1);
315
316
317
318 main.chartAccountsButtonVBoxLayout = new QVBoxLayout();
319 main.chartAccountsButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/chartOfAccounts.png")),
320 "Chart of Accounts", main.reportsWidget);
321 connect(main.chartAccountsButton, SIGNAL(clicked()), this, SLOT(chartAccountsReport()));
322 main.chartAccountsButton->installEventFilter(this);
323 main.chartAccountsButtonVBoxLayout->addWidget(main.chartAccountsButton);
324
325
326 main.reportsGridLayout->addLayout(main.chartAccountsButtonVBoxLayout, 5, 1);
327
328
329 main.vBoxLayout->addStretch();
330
331 main.hBoxLayout->addStretch();
332
333
334 addWidget(main.widget, 0);
335
336 active = 0;
337
338
339 report.widget = new QWidget(this);
340 report.vBoxLayout = new QVBoxLayout(report.widget);
341 report.vBoxLayout->setMargin(5);
342 report.vBoxLayout->setSpacing(5);
343
344 report.labelLayout = new QBoxLayout(report.vBoxLayout, QBoxLayout::LeftToRight);
345 report.topLabel = new GoBackLabel(report.widget);
346 connect(report.topLabel, SIGNAL(goBack()), this, SLOT(switchWidget()));
347
348 report.print = new QPushButton(
349 QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/print.png")),
350 "Print Report (F8)", report.widget);
351 report.print->setFocusPolicy(QWidget::NoFocus);
352 connect(report.print, SIGNAL(clicked()), this, SLOT(print()));
353
354 report.labelLayout->addWidget(report.topLabel, 0, Qt::AlignLeft | Qt::AlignTop);
355 report.labelLayout->addStretch();
356 report.labelLayout->addWidget(report.print);
357
358 report.view = new QTextEdit(report.widget);
359 report.view->setTextFormat(QTextEdit::RichText);
360 report.view->setReadOnly(true);
361 report.view->setVScrollBarMode(QScrollView::AlwaysOn);
362 report.view->installEventFilter(this);
363
364 report.vBoxLayout->addWidget(report.view);
365
366 report.bottomWidget = new QWidget(report.widget);
367 report.bottomHBoxLayout = new QHBoxLayout(report.bottomWidget);
368
369 report.bottomLabel = new QLabel(
370 "<nobr><b>Keyboard Control:</b></nobr><br>"
371 "<nobr> nbsp; nbsp; <b>Up</b> / <b>Down</b>: Scroll the page</nobr><br>",
372 report.bottomWidget);
373
374 report.bottomRightFrame = new QFrame(report.bottomWidget);
375 report.bottomRightBoxLayout = new QBoxLayout(report.bottomRightFrame, QBoxLayout::LeftToRight);
376 report.bottomRightBoxLayout->setSpacing(5);
377
378 report.exportPDFButton = new QPushButton(
379 QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/exportpdf.png")),
380 "Export to PDF (F11)", report.bottomRightFrame);
381 connect(report.exportPDFButton, SIGNAL(clicked()), this, SLOT(exportPDF()));
382
383 report.exportCSVButton = new QPushButton(
384 QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/export.png")),
385 "Export to CSV (F12)", report.bottomRightFrame);
386 connect(report.exportCSVButton, SIGNAL(clicked()), this, SLOT(exportCSV()));
387
388 report.bottomRightBoxLayout->addWidget(report.exportPDFButton, 0, Qt::AlignLeft | Qt::AlignTop);
389 report.bottomRightBoxLayout->addWidget(report.exportCSVButton, 0, Qt::AlignLeft | Qt::AlignTop);
390
391 report.bottomHBoxLayout->addWidget(report.bottomLabel);
392 report.bottomHBoxLayout->addStretch();
393 report.bottomHBoxLayout->addWidget(report.bottomRightFrame);
394
395 report.vBoxLayout->addWidget(report.bottomWidget);
396
397 addWidget(report.widget, 1);
398
399
ReportStack::~ReportStack ()
Definition at line 401 of file reportStack.cpp.
402 {}
Member Function Documentation
void ReportStack::balanceReport () [private, slot]
Definition at line 520 of file reportStack.cpp.
References db, Database::getBalanceReport(), main, Database::reportString(), and viewReport().
Referenced by eventFilter(), and ReportStack().
521 {
522     viewReport(db->getBalanceReport(main.balanceMonthEndList->currentText())->reportString());
523 }
void ReportStack::chartAccountsReport () [private, slot]
Definition at line 525 of file reportStack.cpp.
References db, Database::getChartAccounts(), Database::reportString(), and viewReport().
Referenced by eventFilter(), and ReportStack().
526 {
527     viewReport(db->getChartAccounts()->reportString());
528 }
void ReportStack::dbOpened () [private, slot]
Definition at line 438 of file reportStack.cpp.
References active, db, Database::getPeriodBegin(), Database::getPeriodEnd(), main, and updateAccounts().
439 {
440     updateAccounts();
441     
442     QStringList periodBegin = db->getPeriodBegin();
443     QStringList periodEnd = db->getPeriodEnd();
444     main.generalDetailDateRangeBegin->clear();
445     main.generalDetailDateRangeBegin->insertStringList(periodBegin);
446     main.generalDetailDateRangeEnd->clear();
447     main.generalDetailDateRangeEnd->insertStringList(periodEnd);
448     main.generalTrialMonthEndList->clear();
449     main.generalTrialMonthEndList->insertStringList(periodEnd);
450     main.balanceMonthEndList->clear();
451     main.balanceMonthEndList->insertStringList(periodEnd);
452     main.incomeSvcMonthEndList->clear();
453     main.incomeSvcMonthEndList->insertStringList(periodEnd);
454     main.incomeRetailMonthEndList->clear();
455     main.incomeRetailMonthEndList->insertStringList(periodEnd);
456 
457     raiseWidget(0);
458     active = 0;
459 }
void ReportStack::detailAccountsAllChanged (bool) [private, slot]
Definition at line 404 of file reportStack.cpp.
References main.
Referenced by ReportStack().
405 {
406     if(on)
407     {
408         main.generalDetailAccountRangeBegin->setEnabled(false);
409         main.generalDetailAccountRangeLabelBetween->setEnabled(false);
410         main.generalDetailAccountRangeEnd->setEnabled(false);
411         main.generalDetailAccountRangeAll->setFocus();
412     }
413     else
414     {
415         main.generalDetailAccountRangeBegin->setEnabled(true);
416         main.generalDetailAccountRangeLabelBetween->setEnabled(true);
417         main.generalDetailAccountRangeEnd->setEnabled(true);
418     }
419 } 
bool ReportStack::eventFilter (QObject * target, QEvent * event) [private]
Definition at line 694 of file reportStack.cpp.
References active, balanceReport(), chartAccountsReport(), exportCSV(), exportPDF(), generalDetailReport(), generalTrialReport(), goToMain(), incomeRetailReport(), incomeSvcReport(), main, print(), switchToEditIncomeRetail(), switchToEditIncomeSvc(), and switchWidget().
695 {
696     if(event->type() == QEvent::KeyPress)
697     {
698         QKeyEvent *keyEvent = (QKeyEvent *)event;
699         if(keyEvent->key() == Key_Escape)
700         {
701             if(active == 0)
702                 emit goToMain();
703             else
704                 switchWidget();
705             return true;
706         }
707         if((keyEvent->key() == Key_Enter || keyEvent->key() == Key_Return)
708            && active == 0)
709         {
710             if(main.generalDetailButton->isDefault())
711                 generalDetailReport();
712             else if(main.generalTrialButton->isDefault())
713                 generalTrialReport();
714             else if(main.balanceReportButton->isDefault())
715                 balanceReport();
716             else if(main.incomeSvcModifyButton->isDefault())
717                 switchToEditIncomeSvc();
718             else if(main.incomeSvcButton->isDefault())
719                 incomeSvcReport();
720             else if(main.incomeRetailModifyButton->isDefault())
721                 switchToEditIncomeRetail();
722             else if(main.incomeRetailButton->isDefault())
723                 incomeRetailReport();
724             else if(main.chartAccountsButton->isDefault())
725                 chartAccountsReport();
726         }
727         if(keyEvent->key() == Key_F8 && active == 1)
728         {
729             print();
730             return true;
731         }
732         if(keyEvent->key() == Key_F11 && active == 1)
733         {
734             exportPDF();
735             return true;
736         }
737         if(keyEvent->key() == Key_F12 && active == 1)
738         {
739             exportCSV();
740             return true;
741         }
742     }
743     if(event->type() == QEvent::FocusIn)
744     {
745         if(target == main.generalDetailDateRangeBegin
746            || target == main.generalDetailDateRangeEnd
747            || target == main.generalDetailAccountRangeBegin
748            || target == main.generalDetailAccountRangeEnd
749            || target == main.generalDetailAccountRangeAll
750            || target == main.generalDetailButton)
751         {
752             if(!main.generalDetailButton->isDefault())
753             {
754                 main.generalDetailButton->setDefault(true);
755                 main.generalTrialButton->setDefault(false);
756                 main.balanceReportButton->setDefault(false);
757                 main.incomeSvcModifyButton->setDefault(false);
758                 main.incomeSvcButton->setDefault(false);
759                 main.incomeRetailModifyButton->setDefault(false);
760                 main.incomeRetailButton->setDefault(false);
761                 main.chartAccountsButton->setDefault(false);
762             }
763         }
764         else if(target == main.generalTrialMonthEndList
765                 || target == main.generalTrialAccountRangeBegin
766                 || target == main.generalTrialAccountRangeEnd
767                 || target == main.generalTrialAccountRangeAll
768                 || target == main.generalTrialButton)
769         {
770             if(!main.generalTrialButton->isDefault())
771             {
772                 main.generalDetailButton->setDefault(false);
773                 main.generalTrialButton->setDefault(true);
774                 main.balanceReportButton->setDefault(false);
775                 main.incomeSvcModifyButton->setDefault(false);
776                 main.incomeSvcButton->setDefault(false);
777                 main.incomeRetailModifyButton->setDefault(false);
778                 main.incomeRetailButton->setDefault(false);
779                 main.chartAccountsButton->setDefault(false);
780             }
781         }
782         else if(target == main.balanceMonthEndList
783                 || target == main.balanceModifyButton   
784                 || target == main.balanceReportButton)
785         {
786             if(!main.balanceReportButton->isDefault())
787             {
788                 main.generalDetailButton->setDefault(false);
789                 main.generalTrialButton->setDefault(false);
790                 main.balanceReportButton->setDefault(true);
791                 main.incomeSvcModifyButton->setDefault(false);
792                 main.incomeSvcButton->setDefault(false);
793                 main.incomeRetailModifyButton->setDefault(false);
794                 main.incomeRetailButton->setDefault(false);
795                 main.chartAccountsButton->setDefault(false);
796             }
797         }
798         else if(target == main.incomeSvcMonthEndList
799                 || target == main.incomeSvcButton)
800         {
801             if(!main.incomeSvcButton->isDefault())
802             {
803                 main.generalDetailButton->setDefault(false);
804                 main.generalTrialButton->setDefault(false);
805                 main.balanceReportButton->setDefault(false);
806                 main.incomeSvcModifyButton->setDefault(false);
807                 main.incomeSvcButton->setDefault(true);
808                 main.incomeRetailModifyButton->setDefault(false);
809                 main.incomeRetailButton->setDefault(false);
810                 main.chartAccountsButton->setDefault(false);
811             }
812         }
813         else if(target == main.incomeSvcModifyButton)
814         {
815             if(!main.incomeSvcModifyButton->isDefault())
816             {
817                 main.generalDetailButton->setDefault(false);
818                 main.generalTrialButton->setDefault(false);
819                 main.balanceReportButton->setDefault(false);
820                 main.incomeSvcModifyButton->setDefault(true);
821                 main.incomeSvcButton->setDefault(false);
822                 main.incomeRetailModifyButton->setDefault(false);
823                 main.incomeRetailButton->setDefault(false);
824                 main.chartAccountsButton->setDefault(false);
825             }
826         }
827         else if(target == main.incomeRetailMonthEndList
828                 || target == main.incomeRetailButton)
829         {
830             if(!main.incomeRetailButton->isDefault())
831             {
832                 main.generalDetailButton->setDefault(false);
833                 main.generalTrialButton->setDefault(false);
834                 main.balanceReportButton->setDefault(false);
835                 main.incomeSvcModifyButton->setDefault(false);
836                 main.incomeSvcButton->setDefault(false);
837                 main.incomeRetailModifyButton->setDefault(false);
838                 main.incomeRetailButton->setDefault(true);
839                 main.chartAccountsButton->setDefault(false);
840             }
841         }
842         else if(target == main.incomeRetailModifyButton)
843         {
844             if(!main.incomeRetailModifyButton->isDefault())
845             {
846                 main.generalDetailButton->setDefault(false);
847                 main.generalTrialButton->setDefault(false);
848                 main.balanceReportButton->setDefault(false);
849                 main.incomeSvcModifyButton->setDefault(false);
850                 main.incomeSvcButton->setDefault(false);
851                 main.incomeRetailModifyButton->setDefault(true);
852                 main.incomeRetailButton->setDefault(false);
853                 main.chartAccountsButton->setDefault(false);
854             }
855         }
856         else if(target == main.chartAccountsButton)
857         {
858             main.generalDetailButton->setDefault(false);
859             main.generalTrialButton->setDefault(false);
860             main.balanceReportButton->setDefault(false);
861             main.incomeSvcModifyButton->setDefault(false);
862             main.incomeSvcButton->setDefault(false);
863             main.incomeRetailModifyButton->setDefault(false);
864             main.incomeRetailButton->setDefault(false);
865             main.chartAccountsButton->setDefault(true);
866         }
867     }
868     return QWidgetStack::eventFilter(target,event);
869 }  
void ReportStack::exportCSV () [private, slot]
Definition at line 588 of file reportStack.cpp.
References db, importPath, and Database::reportCSV().
Referenced by eventFilter(), and ReportStack().
589 {
590     QString file = QFileDialog::getSaveFileName(
591             importPath,
592             "Comma Separated Values (*.csv)",
593             this,
594             0,
595             "Export Report to CSV");
596     
597     if(file != "")
598     {
599         if(file.right(4) != ".csv")
600             file.append(".csv");
601 
602         QFile destFile(file);
603     
604         if(destFile.open(IO_WriteOnly))
605         {
606             QTextStream destStream(&destFile);
607             destStream << db->reportCSV();
608         }
609         destFile.close();
610     }
611 }
void ReportStack::exportPDF () [private, slot]
Definition at line 545 of file reportStack.cpp.
References clientPath, db, PDFOptions::exec(), exportPath, and Database::reportHTML().
Referenced by eventFilter(), and ReportStack().
546 {
547     QString file = QFileDialog::getSaveFileName(
548             exportPath,
549             "PDF Files (*.pdf)",
550             this,
551             0,
552             "Export Report to PDF");
553     
554     if(file != "")
555     {
556         if(file.right(4) != ".pdf")
557             file.append(".pdf");
558 
559         PDFOptions pdfOptions;
560         QString options = pdfOptions.exec();
561         if(options == QString::null)
562             return;
563 
564         QFile tmpHTML(clientPath + "/tmp.html");
565         if(!tmpHTML.open( IO_WriteOnly ))
566             return;
567 
568         QTextStream tmpStream(&tmpHTML);
569 
570         QString html = db->reportHTML();
571         html.replace("<tr><td> </td></tr>", "<tr><td>&nbsp;<br></td></tr>");
572 
573         tmpStream << html;
574 
575         tmpStream.unsetDevice();
576         tmpHTML.close();
577 
578         system(QString(HTMLDOC_PATH + "/htmldoc --footer ./. --fontsize 9.0 "
579                 + options +
580                 "--right .5in --left .5in --top .2in "
581                 "--textfont helvetica --no-toc --no-title --quiet -f \""
582                 + file + "\" \"" + clientPath + "/tmp.html\""));
583 
584         remove(clientPath + "/tmp.html");
585     }
586 }
void ReportStack::generalDetailReport () [private, slot]
Definition at line 492 of file reportStack.cpp.
References db, Database::getGeneralDetail(), main, Database::reportString(), and viewReport().
Referenced by eventFilter(), and ReportStack().
493 {
494     if(main.generalDetailAccountRangeAll->isChecked())
495         viewReport(db->getGeneralDetail(
496                 main.generalDetailDateRangeBegin->currentText(),
497                 main.generalDetailDateRangeEnd->currentText(),
498                 "", "")->reportString());
499     else
500         viewReport(db->getGeneralDetail(
501                 main.generalDetailDateRangeBegin->currentText(),
502                 main.generalDetailDateRangeEnd->currentText(),
503                 main.generalDetailAccountRangeBegin->accountNumber(),
504                 main.generalDetailAccountRangeEnd->accountNumber())->reportString());
505 }
void ReportStack::generalTrialReport () [private, slot]
Definition at line 507 of file reportStack.cpp.
References db, Database::getGeneralTrialBalance(), main, Database::reportString(), and viewReport().
Referenced by eventFilter(), and ReportStack().
508 {
509     if(main.generalTrialAccountRangeAll->isChecked())
510         viewReport(db->getGeneralTrialBalance(
511             main.generalTrialMonthEndList->currentText(),
512             "", "")->reportString());
513     else
514         viewReport(db->getGeneralTrialBalance(
515             main.generalTrialMonthEndList->currentText(),
516             main.generalTrialAccountRangeBegin->accountNumber(),
517             main.generalTrialAccountRangeEnd->accountNumber())->reportString());
518 }
void ReportStack::goToMain () [signal]
Referenced by eventFilter(), and ReportStack().
void ReportStack::incomeRetailReport () [private, slot]
Definition at line 535 of file reportStack.cpp.
References db, Database::getIncomeRetailReport(), main, Database::reportString(), and viewReport().
Referenced by eventFilter(), and ReportStack().
536 {
537     viewReport(db->getIncomeRetailReport(main.incomeRetailMonthEndList->currentText())->reportString());
538 }
void ReportStack::incomeSvcReport () [private, slot]
Definition at line 530 of file reportStack.cpp.
References db, Database::getIncomeSvcReport(), main, Database::reportString(), and viewReport().
Referenced by eventFilter(), and ReportStack().
531 {
532     viewReport(db->getIncomeSvcReport(main.incomeSvcMonthEndList->currentText())->reportString());
533 }
void ReportStack::print () [private, slot]
Referenced by eventFilter(), and ReportStack().
void ReportStack::switchToEditBalance () [private, slot]
Definition at line 613 of file reportStack.cpp.
References active, balance, switchWidget(), and widget.
Referenced by ReportStack().
614 {
615     if(widget(2))
616         delete balance.widget;
617 
618     balance.widget = new QWidget(this);
619     balance.vBoxLayout = new QVBoxLayout(balance.widget);
620     balance.vBoxLayout->setMargin(5);
621     balance.vBoxLayout->setSpacing(5);
622     
623     balance.labelLayout = new QHBoxLayout(balance.vBoxLayout);
624     balance.topLabel = new GoBackLabel(balance.widget);
625     connect(balance.topLabel, SIGNAL(goBack()), this, SLOT(switchWidget()));
626     
627     balance.labelLayout->addWidget(balance.topLabel);
628     balance.labelLayout->addStretch();
629     
630     balance.editor = new BalanceSheetEditor(balance.widget);
631     
632     balance.vBoxLayout->addWidget(balance.editor);
633     
634     addWidget(balance.widget, 2);
635 
636     raiseWidget(2);
637     active = 2;
638 }
void ReportStack::switchToEditIncomeRetail () [private, slot]
Definition at line 667 of file reportStack.cpp.
References active, incomeRetail, switchWidget(), and widget.
Referenced by eventFilter(), and ReportStack().
668 {
669     if(widget(4))
670         delete incomeRetail.widget;
671 
672     incomeRetail.widget = new QWidget(this);
673     incomeRetail.vBoxLayout = new QVBoxLayout(incomeRetail.widget);
674     incomeRetail.vBoxLayout->setMargin(5);
675     incomeRetail.vBoxLayout->setSpacing(5);
676     
677     incomeRetail.labelLayout = new QHBoxLayout(incomeRetail.vBoxLayout);
678     incomeRetail.topLabel = new GoBackLabel(incomeRetail.widget);
679     connect(incomeRetail.topLabel, SIGNAL(goBack()), this, SLOT(switchWidget()));
680     
681     incomeRetail.labelLayout->addWidget(incomeRetail.topLabel);
682     incomeRetail.labelLayout->addStretch();
683     
684     incomeRetail.editor = new IncomeRetailEditor(incomeRetail.widget);
685     
686     incomeRetail.vBoxLayout->addWidget(incomeRetail.editor);
687     
688     addWidget(incomeRetail.widget, 4);
689 
690     raiseWidget(4);
691     active = 4;
692 }
void ReportStack::switchToEditIncomeSvc () [private, slot]
Definition at line 640 of file reportStack.cpp.
References active, incomeSvc, switchWidget(), and widget.
Referenced by eventFilter(), and ReportStack().
641 {
642     if(widget(3))
643         delete incomeSvc.widget;
644 
645     incomeSvc.widget = new QWidget(this);
646     incomeSvc.vBoxLayout = new QVBoxLayout(incomeSvc.widget);
647     incomeSvc.vBoxLayout->setMargin(5);
648     incomeSvc.vBoxLayout->setSpacing(5);
649     
650     incomeSvc.labelLayout = new QHBoxLayout(incomeSvc.vBoxLayout);
651     incomeSvc.topLabel = new GoBackLabel(incomeSvc.widget);
652     connect(incomeSvc.topLabel, SIGNAL(goBack()), this, SLOT(switchWidget()));
653     
654     incomeSvc.labelLayout->addWidget(incomeSvc.topLabel);
655     incomeSvc.labelLayout->addStretch();
656     
657     incomeSvc.editor = new IncomeSvcEditor(incomeSvc.widget);
658     
659     incomeSvc.vBoxLayout->addWidget(incomeSvc.editor);
660     
661     addWidget(incomeSvc.widget, 3);
662 
663     raiseWidget(3);
664     active = 3;
665 }
void ReportStack::switchWidget () [private, slot]
Definition at line 477 of file reportStack.cpp.
References active, and report.
Referenced by eventFilter(), ReportStack(), switchToEditBalance(), switchToEditIncomeRetail(), switchToEditIncomeSvc(), and viewReport().
478 {
479     if(active == 0)
480     {
481             raiseWidget(1);
482             report.view->setFocus();
483             active = 1;
484     }
485     else
486     {
487         raiseWidget(0);
488         active = 0;
489     }
490 }
void ReportStack::trialAccountsAllChanged (bool) [private, slot]
Definition at line 421 of file reportStack.cpp.
References main.
Referenced by ReportStack().
422 {
423     if(on)
424     {
425         main.generalTrialAccountRangeBegin->setEnabled(false);
426         main.generalTrialAccountRangeLabelBetween->setEnabled(false);
427         main.generalTrialAccountRangeEnd->setEnabled(false);
428         main.generalTrialAccountRangeAll->setFocus();
429     }
430     else
431     {
432         main.generalTrialAccountRangeBegin->setEnabled(true);
433         main.generalTrialAccountRangeLabelBetween->setEnabled(true);
434         main.generalTrialAccountRangeEnd->setEnabled(true);
435     }
436 }
void ReportStack::updateAccounts () [private, slot]
Definition at line 461 of file reportStack.cpp.
References accounts, db, Database::getAccountsList(), and main.
Referenced by dbOpened(), and ReportStack().
462 {
463     accounts = db->getAccountsList();
464     main.generalDetailAccountRangeBegin->updateAccounts(accounts);
465     main.generalDetailAccountRangeEnd->updateAccounts(accounts);
466     main.generalTrialAccountRangeBegin->updateAccounts(accounts);
467     main.generalTrialAccountRangeEnd->updateAccounts(accounts);
468 }
void ReportStack::viewReport (QString & text) [private, slot]
Definition at line 470 of file reportStack.cpp.
References report, and switchWidget().
Referenced by balanceReport(), chartAccountsReport(), generalDetailReport(), generalTrialReport(), incomeRetailReport(), and incomeSvcReport().
471 {
472     report.view->setText(text);
473 
474     switchWidget();
475 }
Member Data Documentation
QStringList ReportStack::accounts [private]
Definition at line 76 of file reportStack.h.
Referenced by ReportStack(), and updateAccounts().
int ReportStack::active [private]
Definition at line 75 of file reportStack.h.
Referenced by dbOpened(), eventFilter(), ReportStack(), switchToEditBalance(), switchToEditIncomeRetail(), switchToEditIncomeSvc(), and switchWidget().
struct { ... } ReportStack::balance [private]
Referenced by switchToEditBalance().
QPushButton* ReportStack::balanceModifyButton [private]
Definition at line 129 of file reportStack.h.
QHBoxLayout* ReportStack::balanceModifyHBoxLayout [private]
Definition at line 128 of file reportStack.h.
QWidget* ReportStack::balanceModifyWidget [private]
Definition at line 127 of file reportStack.h.
QHBoxLayout* ReportStack::balanceMonthEndHBoxLayout [private]
Definition at line 124 of file reportStack.h.
QLabel* ReportStack::balanceMonthEndLabel [private]
Definition at line 125 of file reportStack.h.
QComboBox* ReportStack::balanceMonthEndList [private]
Definition at line 126 of file reportStack.h.
QWidget* ReportStack::balanceMonthEndWidget [private]
Definition at line 123 of file reportStack.h.
QPushButton* ReportStack::balanceReportButton [private]
Definition at line 131 of file reportStack.h.
QVBoxLayout* ReportStack::balanceReportButtonVBoxLayout [private]
Definition at line 130 of file reportStack.h.
QVGroupBox* ReportStack::balanceVGroupBox [private]
Definition at line 122 of file reportStack.h.
QHBoxLayout* ReportStack::bottomHBoxLayout [private]
Definition at line 167 of file reportStack.h.
QLabel* ReportStack::bottomLabel [private]
Definition at line 168 of file reportStack.h.
QBoxLayout* ReportStack::bottomRightBoxLayout [private]
Definition at line 170 of file reportStack.h.
QFrame* ReportStack::bottomRightFrame [private]
Definition at line 169 of file reportStack.h.
QWidget* ReportStack::bottomWidget [private]
Definition at line 166 of file reportStack.h.
QPushButton* ReportStack::chartAccountsButton [private]
Definition at line 156 of file reportStack.h.
QVBoxLayout* ReportStack::chartAccountsButtonVBoxLayout [private]
Definition at line 155 of file reportStack.h.
QString ReportStack::clientPath [private]
Definition at line 71 of file reportStack.h.
Referenced by exportPDF(), and ReportStack().
Database* ReportStack::db [private]
Definition at line 67 of file reportStack.h.
Referenced by balanceReport(), chartAccountsReport(), dbOpened(), exportCSV(), exportPDF(), generalDetailReport(), generalTrialReport(), incomeRetailReport(), incomeSvcReport(), ReportStack(), and updateAccounts().
IncomeRetailEditor* ReportStack::editor [private]
Definition at line 196 of file reportStack.h.
IncomeSvcEditor* ReportStack::editor [private]
Definition at line 188 of file reportStack.h.
BalanceSheetEditor* ReportStack::editor [private]
Definition at line 180 of file reportStack.h.
QPushButton* ReportStack::exportCSVButton [private]
Definition at line 172 of file reportStack.h.
QString ReportStack::exportPath [private]
Definition at line 72 of file reportStack.h.
Referenced by exportPDF(), and ReportStack().
QPushButton* ReportStack::exportPDFButton [private]
Definition at line 171 of file reportStack.h.
QCheckBox* ReportStack::generalDetailAccountRangeAll [private]
Definition at line 103 of file reportStack.h.
AccountList* ReportStack::generalDetailAccountRangeBegin [private]
Definition at line 100 of file reportStack.h.
AccountList* ReportStack::generalDetailAccountRangeEnd [private]
Definition at line 102 of file reportStack.h.
QHBoxLayout* ReportStack::generalDetailAccountRangeHBoxLayout [private]
Definition at line 98 of file reportStack.h.
QLabel* ReportStack::generalDetailAccountRangeLabel [private]
Definition at line 99 of file reportStack.h.
QLabel* ReportStack::generalDetailAccountRangeLabelBetween [private]
Definition at line 101 of file reportStack.h.
QWidget* ReportStack::generalDetailAccountRangeWidget [private]
Definition at line 97 of file reportStack.h.
QPushButton* ReportStack::generalDetailButton [private]
Definition at line 105 of file reportStack.h.
QVBoxLayout* ReportStack::generalDetailButtonVBoxLayout [private]
Definition at line 104 of file reportStack.h.
QComboBox* ReportStack::generalDetailDateRangeBegin [private]
Definition at line 94 of file reportStack.h.
QComboBox* ReportStack::generalDetailDateRangeEnd [private]
Definition at line 96 of file reportStack.h.
QHBoxLayout* ReportStack::generalDetailDateRangeHBoxLayout [private]
Definition at line 92 of file reportStack.h.
QLabel* ReportStack::generalDetailDateRangeLabelBegin [private]
Definition at line 93 of file reportStack.h.
QLabel* ReportStack::generalDetailDateRangeLabelBetween [private]
Definition at line 95 of file reportStack.h.
QWidget* ReportStack::generalDetailDateRangeWidget [private]
Definition at line 91 of file reportStack.h.
QVGroupBox* ReportStack::generalDetailVGroupBox [private]
Definition at line 90 of file reportStack.h.
QCheckBox* ReportStack::generalTrialAccountRangeAll [private]
Definition at line 118 of file reportStack.h.
AccountList* ReportStack::generalTrialAccountRangeBegin [private]
Definition at line 115 of file reportStack.h.
AccountList* ReportStack::generalTrialAccountRangeEnd [private]
Definition at line 117 of file reportStack.h.
QHBoxLayout* ReportStack::generalTrialAccountRangeHBoxLayout [private]
Definition at line 113 of file reportStack.h.
QLabel* ReportStack::generalTrialAccountRangeLabel [private]
Definition at line 114 of file reportStack.h.
QLabel* ReportStack::generalTrialAccountRangeLabelBetween [private]
Definition at line 116 of file reportStack.h.
QWidget* ReportStack::generalTrialAccountRangeWidget [private]
Definition at line 112 of file reportStack.h.
QPushButton* ReportStack::generalTrialButton [private]
Definition at line 120 of file reportStack.h.
QVBoxLayout* ReportStack::generalTrialButtonVBoxLayout [private]
Definition at line 119 of file reportStack.h.
QHBoxLayout* ReportStack::generalTrialMonthEndHBoxLayout [private]
Definition at line 109 of file reportStack.h.
QLabel* ReportStack::generalTrialMonthEndLabel [private]
Definition at line 110 of file reportStack.h.
QComboBox* ReportStack::generalTrialMonthEndList [private]
Definition at line 111 of file reportStack.h.
QWidget* ReportStack::generalTrialMonthEndWidget [private]
Definition at line 108 of file reportStack.h.
QVGroupBox* ReportStack::generalTrialVGroupBox [private]
Definition at line 107 of file reportStack.h.
QHBoxLayout* ReportStack::hBoxLabel [private]
Definition at line 81 of file reportStack.h.
QHBoxLayout* ReportStack::hBoxLayout [private]
Definition at line 83 of file reportStack.h.
QString ReportStack::importPath [private]
Definition at line 73 of file reportStack.h.
Referenced by exportCSV(), and ReportStack().
struct { ... } ReportStack::incomeRetail [private]
Referenced by switchToEditIncomeRetail().
QPushButton* ReportStack::incomeRetailButton [private]
Definition at line 153 of file reportStack.h.
QVBoxLayout* ReportStack::incomeRetailButtonVBoxLayout [private]
Definition at line 152 of file reportStack.h.
QPushButton* ReportStack::incomeRetailModifyButton [private]
Definition at line 151 of file reportStack.h.
QHBoxLayout* ReportStack::incomeRetailModifyHBoxLayout [private]
Definition at line 150 of file reportStack.h.
QWidget* ReportStack::incomeRetailModifyWidget [private]
Definition at line 149 of file reportStack.h.
QHBoxLayout* ReportStack::incomeRetailMonthEndHBoxLayout [private]
Definition at line 146 of file reportStack.h.
QLabel* ReportStack::incomeRetailMonthEndLabel [private]
Definition at line 147 of file reportStack.h.
QComboBox* ReportStack::incomeRetailMonthEndList [private]
Definition at line 148 of file reportStack.h.
QWidget* ReportStack::incomeRetailMonthEndWidget [private]
Definition at line 145 of file reportStack.h.
QVGroupBox* ReportStack::incomeRetailVGroupBox [private]
Definition at line 144 of file reportStack.h.
struct { ... } ReportStack::incomeSvc [private]
Referenced by switchToEditIncomeSvc().
QPushButton* ReportStack::incomeSvcButton [private]
Definition at line 142 of file reportStack.h.
QVBoxLayout* ReportStack::incomeSvcButtonVBoxLayout [private]
Definition at line 141 of file reportStack.h.
QPushButton* ReportStack::incomeSvcModifyButton [private]
Definition at line 140 of file reportStack.h.
QHBoxLayout* ReportStack::incomeSvcModifyHBoxLayout [private]
Definition at line 139 of file reportStack.h.
QWidget* ReportStack::incomeSvcModifyWidget [private]
Definition at line 138 of file reportStack.h.
QHBoxLayout* ReportStack::incomeSvcMonthEndHBoxLayout [private]
Definition at line 135 of file reportStack.h.
QLabel* ReportStack::incomeSvcMonthEndLabel [private]
Definition at line 136 of file reportStack.h.
QComboBox* ReportStack::incomeSvcMonthEndList [private]
Definition at line 137 of file reportStack.h.
QWidget* ReportStack::incomeSvcMonthEndWidget [private]
Definition at line 134 of file reportStack.h.
QVGroupBox* ReportStack::incomeSvcVGroupBox [private]
Definition at line 133 of file reportStack.h.
QBoxLayout* ReportStack::labelLayout [private]
Definition at line 194 of file reportStack.h.
QBoxLayout* ReportStack::labelLayout [private]
Definition at line 186 of file reportStack.h.
QBoxLayout* ReportStack::labelLayout [private]
Definition at line 178 of file reportStack.h.
QBoxLayout* ReportStack::labelLayout [private]
Definition at line 162 of file reportStack.h.
struct { ... } ReportStack::main [private]
Referenced by balanceReport(), dbOpened(), detailAccountsAllChanged(), eventFilter(), generalDetailReport(), generalTrialReport(), incomeRetailReport(), incomeSvcReport(), ReportStack(), trialAccountsAllChanged(), and updateAccounts().
void ReportStack::print [private]
Definition at line 540 of file reportStack.cpp.
541 {
542     printer->printReport(db->reportHeader(), db->reportData());
543 }
Printer* ReportStack::printer [private]
Definition at line 69 of file reportStack.h.
Referenced by ReportStack().
struct { ... } ReportStack::report [private]
Referenced by ReportStack(), switchWidget(), and viewReport().
QGridLayout* ReportStack::reportsGridLayout [private]
Definition at line 88 of file reportStack.h.
QVGroupBox* ReportStack::reportsGroup [private]
Definition at line 86 of file reportStack.h.
QWidget* ReportStack::reportsWidget [private]
Definition at line 87 of file reportStack.h.
Settings* ReportStack::settings [private]
Definition at line 68 of file reportStack.h.
Referenced by ReportStack().
GoBackLabel* ReportStack::topLabel [private]
Definition at line 195 of file reportStack.h.
GoBackLabel* ReportStack::topLabel [private]
Definition at line 187 of file reportStack.h.
GoBackLabel* ReportStack::topLabel [private]
Definition at line 179 of file reportStack.h.
GoBackLabel* ReportStack::topLabel [private]
Definition at line 163 of file reportStack.h.
GoBackLabel* ReportStack::topLabel [private]
Definition at line 82 of file reportStack.h.
QVBoxLayout* ReportStack::vBoxLabel [private]
Definition at line 80 of file reportStack.h.
QVBoxLayout* ReportStack::vBoxLayout [private]
Definition at line 193 of file reportStack.h.
QVBoxLayout* ReportStack::vBoxLayout [private]
Definition at line 185 of file reportStack.h.
QVBoxLayout* ReportStack::vBoxLayout [private]
Definition at line 177 of file reportStack.h.
QVBoxLayout* ReportStack::vBoxLayout [private]
Definition at line 161 of file reportStack.h.
QVBoxLayout* ReportStack::vBoxLayout [private]
Definition at line 84 of file reportStack.h.
QTextEdit* ReportStack::view [private]
Definition at line 165 of file reportStack.h.
QWidget* ReportStack::widget [private]
Definition at line 192 of file reportStack.h.
QWidget* ReportStack::widget [private]
Definition at line 184 of file reportStack.h.
QWidget* ReportStack::widget [private]
Definition at line 176 of file reportStack.h.
QWidget* ReportStack::widget [private]
Definition at line 160 of file reportStack.h.
QWidget* ReportStack::widget [private]
Definition at line 79 of file reportStack.h.
Referenced by switchToEditBalance(), switchToEditIncomeRetail(), and switchToEditIncomeSvc().
The documentation for this class was generated from the following files:
reportStack.h
reportStack.cpp