AccountStack Class Reference
#include <accountStack.h>
Signals
void goToMain ()
void goToJournal ()
void goToReports ()
void goToHelp ()
Public Member Functions
AccountStack (QWidget *parent=0, const char *name=0)
~AccountStack ()
Private Slots
void dbOpened ()
void importCSV ()
void exportCSV ()
Private Member Functions
bool eventFilter (QObject *target, QEvent *event)
void showEvent (QShowEvent *)
Private Attributes
Database * db
Settings * settings
QString exportPath
QString importPath
bool active
xx xx xx xx xx xx xx xx xx
struct {
 QVBoxLayout * vBoxLayout
 QHBoxLayout * labelLayout
 GoBackLabel * topLabel
 AccountTable * dataTable
 QWidget * bottomWidget
 QHBoxLayout * bottomHBoxLayout
 QLabel * bottomLabel
 QFrame * bottomRightFrame
 QBoxLayout * bottomRightBoxLayout
 QPushButton * importButton
 QPushButton * exportButton
} main
Constructor & Destructor Documentation
AccountStack::AccountStack (QWidget * parent = 0, const char * name = 0)
Definition at line 19 of file accountStack.cpp.
References active, db, exportPath, Settings::getExportPath(), Settings::getImportPath(), importPath, Settings::instance(), Database::instance(), and settings.
20     : QWidget(parent,name)
21 {
22     db = Database::instance();
23     settings = Settings::instance();
24 
25     exportPath = settings->getExportPath();
26     importPath = settings->getImportPath();
27 
28     active = false;
29 }
AccountStack::~AccountStack ()
Definition at line 31 of file accountStack.cpp.
32 {}
Member Function Documentation
void AccountStack::dbOpened () [private, slot]
Definition at line 34 of file accountStack.cpp.
References active, exportCSV(), goToHelp(), goToJournal(), goToMain(), goToReports(), importCSV(), and main.
35 {
36     if(active)
37     {
38         delete main.exportButton;
39         delete main.importButton;
40         delete main.bottomRightBoxLayout;
41         delete main.bottomRightFrame;
42         delete main.bottomLabel;
43         delete main.bottomHBoxLayout;
44         delete main.bottomWidget;
45         delete main.dataTable;
46         delete main.topLabel;
47         delete main.labelLayout;
48         delete main.vBoxLayout;
49     }
50     
51     main.vBoxLayout = new QVBoxLayout(this);
52     main.vBoxLayout->setMargin(5);
53     main.vBoxLayout->setSpacing(5);
54     
55     main.labelLayout = new QHBoxLayout(main.vBoxLayout);
56     main.topLabel = new GoBackLabel(this);
57     connect(main.topLabel, SIGNAL(goBack()), this, SIGNAL(goToMain()));
58     main.labelLayout->addWidget(main.topLabel);
59     main.labelLayout->addStretch();
60     
61     main.dataTable = new AccountTable(this);
62     connect(main.dataTable, SIGNAL(goToMain()), this, SIGNAL(goToMain()));
63     connect(main.dataTable, SIGNAL(goToJournal()), this, SIGNAL(goToJournal()));
64     connect(main.dataTable, SIGNAL(goToReports()), this, SIGNAL(goToReports()));
65     connect(main.dataTable, SIGNAL(goToHelp()), this, SIGNAL(goToHelp()));
66     main.dataTable->installEventFilter(this);
67     
68     main.vBoxLayout->addWidget(main.dataTable);
69     
70     main.bottomWidget = new QWidget(this);
71     main.bottomHBoxLayout = new QHBoxLayout(main.bottomWidget);
72     
73     main.bottomLabel = new QLabel(
74             "<nobr><b>Keyboard Control:</b></nobr><br>"
75             "<nobr> &nbsp; &nbsp; <b>Enter</b>: Edit current field, move to next field</nobr><br>"
76             "<nobr> &nbsp; &nbsp; <b>Insert</b> / <b>Delete</b>: Create new entry / Delete selected entry</nobr>",
77             main.bottomWidget);
78     
79     main.bottomRightFrame = new QFrame(main.bottomWidget);
80     main.bottomRightBoxLayout = new QBoxLayout(main.bottomRightFrame, QBoxLayout::LeftToRight);
81     main.bottomRightBoxLayout->setSpacing(5);
82     
83     main.importButton = new QPushButton(
84             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/import.png") ),
85             "Import from CSV (F11)", main.bottomRightFrame);
86     main.importButton->setFocusPolicy(QWidget::NoFocus);
87     connect(main.importButton, SIGNAL(clicked()), this, SLOT(importCSV()));
88     
89     main.exportButton = new QPushButton(
90             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/export.png") ),
91             "Export to CSV (F12)", main.bottomRightFrame);
92     main.exportButton->setFocusPolicy(QWidget::NoFocus);
93     connect(main.exportButton, SIGNAL(clicked()), this, SLOT(exportCSV()));
94     
95     main.bottomRightBoxLayout->addWidget(main.importButton, 0, Qt::AlignLeft | Qt::AlignTop);
96     main.bottomRightBoxLayout->addWidget(main.exportButton, 0, Qt::AlignLeft | Qt::AlignTop);
97     
98     main.bottomHBoxLayout->addWidget(main.bottomLabel);
99     main.bottomHBoxLayout->addStretch();
100     main.bottomHBoxLayout->addWidget(main.bottomRightFrame);
101     
102     main.vBoxLayout->addWidget(main.bottomWidget);
103     
104     active = true;
105 }
bool AccountStack::eventFilter (QObject * target, QEvent * event) [private]
Definition at line 136 of file accountStack.cpp.
References exportCSV(), and importCSV().
137 {
138     if(event->type() == QEvent::KeyPress)
139     {
140         QKeyEvent *keyEvent = (QKeyEvent*)event;
141         if(keyEvent->key() == Key_F11)
142         {
143             importCSV();
144             return true;
145         }
146         if(keyEvent->key() == Key_F12)
147         {
148             exportCSV();
149             return true;
150         }
151     }
152     
153     return QWidget::eventFilter(target,event);
154 }  
void AccountStack::exportCSV () [private, slot]
Definition at line 123 of file accountStack.cpp.
References db, Database::exportCSV(), and exportPath.
Referenced by dbOpened(), and eventFilter().
124 {
125     QString file = QFileDialog::getSaveFileName(
126             exportPath,
127             "Comma Separated Values (*.csv)",
128             this,
129             0,
130             "Export Accounts");
131 
132     if(file != "")
133         db->exportCSV("accounts", file);
134 }
void AccountStack::goToHelp () [signal]
Referenced by dbOpened().
void AccountStack::goToJournal () [signal]
Referenced by dbOpened().
void AccountStack::goToMain () [signal]
Referenced by dbOpened().
void AccountStack::goToReports () [signal]
Referenced by dbOpened().
void AccountStack::importCSV () [private, slot]
Definition at line 107 of file accountStack.cpp.
References db, Database::importCSV(), importPath, and main.
Referenced by dbOpened(), and eventFilter().
108 {
109     QString file = QFileDialog::getOpenFileName(
110             importPath,
111             "Comma Separated Values (*.csv)",
112             this,
113             0,
114             "Import Accounts");
115     
116     if(file != "")
117     {
118         db->importCSV("accounts", file);
119         main.dataTable->populate();
120     }
121 }
void AccountStack::showEvent (QShowEvent *) [private]
Definition at line 156 of file accountStack.cpp.
References main.
157 {
158     main.dataTable->setFocus();
159 }
Member Data Documentation
bool AccountStack::active [private]
Definition at line 48 of file accountStack.h.
Referenced by AccountStack(), and dbOpened().
QHBoxLayout* AccountStack::bottomHBoxLayout [private]
Definition at line 56 of file accountStack.h.
QLabel* AccountStack::bottomLabel [private]
Definition at line 57 of file accountStack.h.
QBoxLayout* AccountStack::bottomRightBoxLayout [private]
Definition at line 59 of file accountStack.h.
QFrame* AccountStack::bottomRightFrame [private]
Definition at line 58 of file accountStack.h.
QWidget* AccountStack::bottomWidget [private]
Definition at line 55 of file accountStack.h.
AccountTable* AccountStack::dataTable [private]
Definition at line 54 of file accountStack.h.
Database* AccountStack::db [private]
Definition at line 42 of file accountStack.h.
Referenced by AccountStack(), exportCSV(), and importCSV().
QPushButton* AccountStack::exportButton [private]
Definition at line 61 of file accountStack.h.
QString AccountStack::exportPath [private]
Definition at line 45 of file accountStack.h.
Referenced by AccountStack(), and exportCSV().
QPushButton* AccountStack::importButton [private]
Definition at line 60 of file accountStack.h.
QString AccountStack::importPath [private]
Definition at line 46 of file accountStack.h.
Referenced by AccountStack(), and importCSV().
QHBoxLayout* AccountStack::labelLayout [private]
Definition at line 52 of file accountStack.h.
struct { ... } AccountStack::main [private]
Referenced by dbOpened(), importCSV(), and showEvent().
Settings* AccountStack::settings [private]
Definition at line 43 of file accountStack.h.
Referenced by AccountStack().
GoBackLabel* AccountStack::topLabel [private]
Definition at line 53 of file accountStack.h.
QVBoxLayout* AccountStack::vBoxLayout [private]
Definition at line 51 of file accountStack.h.
The documentation for this class was generated from the following files:
accountStack.h
accountStack.cpp