Tabs Class Reference
#include <tabs.h>
Public Member Functions
Tabs (QApplication *parent, const char *name=0)
~Tabs ()
Private Slots
void dbOpened ()
void dbClosed ()
void nameChanged ()
void switchToMain ()
void switchToAccounts ()
void switchToJournal ()
void switchToReports ()
void switchToHelp ()
void quit ()
Private Member Functions
void keyPressEvent (QKeyEvent *event)
void closeEvent (QCloseEvent *event)
Private Attributes
Database * db
Settings * settings
QApplication * app
MainStack * mainStack
AccountStack * accountStack
JournalStack * journalStack
ReportStack * reportStack
HelpStack * helpStack
Constructor & Destructor Documentation
Tabs::Tabs (QApplication * parent, const char * name = 0)
Definition at line 14 of file tabs.cpp.
References accountStack, app, db, dbClosed(), dbOpened(), Settings::getDefaultHeight(), Settings::getDefaultWidth(), Settings::getDefaultX(), Settings::getDefaultY(), helpStack, Settings::instance(), Database::instance(), journalStack, mainStack, nameChanged(), quit(), reportStack, settings, switchToAccounts(), switchToHelp(), switchToJournal(), switchToMain(), and switchToReports().
15     : QTabWidget(0,name)
16 {
17     db = Database::instance();
18     settings = Settings::instance();
19 
20     app = parent;
21     
22     setFocusPolicy(QWidget::NoFocus);
23     
24     setCaption("General Ledger");
25     
26     mainStack = new MainStack;
27     connect(mainStack, SIGNAL(dbOpened()), this, SLOT(dbOpened()));
28     connect(mainStack, SIGNAL(switchToAccounts()), this, SLOT(switchToAccounts()));
29     connect(mainStack, SIGNAL(switchToJournal()), this, SLOT(switchToJournal()));
30     connect(mainStack, SIGNAL(switchToReports()), this, SLOT(switchToReports()));
31     connect(mainStack, SIGNAL(dbClosed()), this, SLOT(dbClosed()));
32     connect(mainStack, SIGNAL(nameChanged()), this, SLOT(nameChanged()));
33     connect(mainStack, SIGNAL(quit()), this, SLOT(quit()));
34     
35     accountStack = new AccountStack;
36     connect(mainStack, SIGNAL(dbOpened()), accountStack, SLOT(dbOpened()));
37     connect(accountStack, SIGNAL(goToMain()), this, SLOT(switchToMain()));
38     connect(accountStack, SIGNAL(goToJournal()), this, SLOT(switchToJournal()));
39     connect(accountStack, SIGNAL(goToReports()), this, SLOT(switchToReports()));
40     connect(accountStack, SIGNAL(goToHelp()), this, SLOT(switchToHelp()));
41     
42     journalStack = new JournalStack;
43     connect(mainStack, SIGNAL(dbOpened()), journalStack, SLOT(dbOpened()));
44     connect(mainStack, SIGNAL(saveAndClearJournalTmp()), journalStack, SLOT(saveAndClear()));
45     connect(journalStack, SIGNAL(goToMain()), this, SLOT(switchToMain()));
46     connect(journalStack, SIGNAL(goToAccounts()), this, SLOT(switchToAccounts()));
47     connect(journalStack, SIGNAL(goToReports()), this, SLOT(switchToReports()));
48     connect(journalStack, SIGNAL(goToHelp()), this, SLOT(switchToHelp()));
49     
50     reportStack = new ReportStack;
51     connect(mainStack, SIGNAL(dbOpened()), reportStack, SLOT(dbOpened()));
52     connect(reportStack, SIGNAL(goToMain()), this, SLOT(switchToMain()));
53     
54     helpStack = new HelpStack;
55     connect(helpStack, SIGNAL(goToMain()), this, SLOT(switchToMain()));
56     
57     addTab( mainStack, QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/mainTab.png") ), "Main (F1)" );
58     addTab( accountStack, QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/accountsTab.png") ), "Accounts (F2)" );
59     setTabEnabled(accountStack, 0);
60     addTab( journalStack, QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/journalTab.png") ), "Journal Entry (F3)" );
61     setTabEnabled(journalStack, 0);
62     addTab( reportStack, QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/reportTab.png") ), "Reports (F4)" );
63     setTabEnabled(reportStack, 0);
64     addTab( helpStack, QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/help.png") ), "Help (F5)" );
65 
66 
67     if(settings->getDefaultX() == 10000 && settings->getDefaultY() == 10000 
68        && settings->getDefaultWidth() == 10000 && settings->getDefaultHeight() == 10000)
69         showMaximized();
70     else
71     {
72         move(settings->getDefaultX(), settings->getDefaultY());
73         resize(settings->getDefaultWidth(), settings->getDefaultHeight());
74     }
75     
76 }
Tabs::~Tabs ()
Definition at line 78 of file tabs.cpp.
79 {}
Member Function Documentation
void Tabs::closeEvent (QCloseEvent * event) [private]
Definition at line 129 of file tabs.cpp.
References MainStack::closeClient(), MainStack::closed(), mainStack, and quit().
130 {
131     mainStack->closeClient();
132     if(mainStack->closed())
133     {
134         quit();
135         event->accept();
136     }
137     else
138         event->ignore();
139 }
void Tabs::dbClosed () [private, slot]
Definition at line 90 of file tabs.cpp.
References accountStack, journalStack, and reportStack.
Referenced by Tabs().
91 {
92     setCaption("General Ledger");
93     
94     setTabEnabled(accountStack, false);
95     setTabEnabled(journalStack, false);
96     setTabEnabled(reportStack, false);
97 }
void Tabs::dbOpened () [private, slot]
Definition at line 81 of file tabs.cpp.
References accountStack, db, Database::getCurClient(), journalStack, and reportStack.
Referenced by Tabs().
82 {
83     setCaption("General Ledger - " + db->getCurClient());
84     
85     setTabEnabled(accountStack, true);
86     setTabEnabled(journalStack, true);
87     setTabEnabled(reportStack, true);
88 }
void Tabs::keyPressEvent (QKeyEvent * event) [private]
Definition at line 104 of file tabs.cpp.
References accountStack, helpStack, journalStack, mainStack, and reportStack.
105 {
106     switch(event->key())
107     {
108         case Key_F1:
109             showPage(mainStack);
110             break;
111         case Key_F2:
112             if(isTabEnabled(accountStack))
113                 showPage(accountStack);
114             break;
115         case Key_F3:
116             if(isTabEnabled(journalStack))
117                 showPage(journalStack);
118             break;
119         case Key_F4:
120             if(isTabEnabled(reportStack))
121                 showPage(reportStack);
122             break;
123         case Key_F5:
124             showPage(helpStack);
125             break;
126     }
127 }
void Tabs::nameChanged () [private, slot]
Definition at line 99 of file tabs.cpp.
References db, and Database::getCurClient().
Referenced by Tabs().
100 {
101     setCaption("General Ledger - " + db->getCurClient());
102 }
void Tabs::quit () [private, slot]
Definition at line 166 of file tabs.cpp.
References app, Settings::setDefaultHeight(), Settings::setDefaultWidth(), Settings::setDefaultX(), Settings::setDefaultY(), and settings.
Referenced by closeEvent(), and Tabs().
167 {
168     if(!isMaximized())
169     {
170         settings->setDefaultX(x());
171         settings->setDefaultY(y());
172         settings->setDefaultWidth(width());
173         settings->setDefaultHeight(height());
174     }
175     else
176     {
177         settings->setDefaultX(10000);  // 10000 instead of -1 because
178         settings->setDefaultY(10000);  // windows registry wasn't storing -1
179         settings->setDefaultWidth(10000);
180         settings->setDefaultHeight(10000);
181     }
182     
183     app->quit();
184 }
void Tabs::switchToAccounts () [private, slot]
Definition at line 146 of file tabs.cpp.
Referenced by Tabs().
147 {
148     setCurrentPage(1);
149 }
void Tabs::switchToHelp () [private, slot]
Definition at line 161 of file tabs.cpp.
Referenced by Tabs().
162 {
163     setCurrentPage(4);
164 }
void Tabs::switchToJournal () [private, slot]
Definition at line 151 of file tabs.cpp.
Referenced by Tabs().
152 {
153     setCurrentPage(2);
154 }
void Tabs::switchToMain () [private, slot]
Definition at line 141 of file tabs.cpp.
Referenced by Tabs().
142 {
143     setCurrentPage(0);
144 }
void Tabs::switchToReports () [private, slot]
Definition at line 156 of file tabs.cpp.
Referenced by Tabs().
157 {
158     setCurrentPage(3);
159 }
Member Data Documentation
AccountStack* Tabs::accountStack [private]
Definition at line 45 of file tabs.h.
Referenced by dbClosed(), dbOpened(), keyPressEvent(), and Tabs().
QApplication* Tabs::app [private]
Definition at line 43 of file tabs.h.
Referenced by quit(), and Tabs().
Database* Tabs::db [private]
Definition at line 40 of file tabs.h.
Referenced by dbOpened(), nameChanged(), and Tabs().
HelpStack* Tabs::helpStack [private]
Definition at line 48 of file tabs.h.
Referenced by keyPressEvent(), and Tabs().
JournalStack* Tabs::journalStack [private]
Definition at line 46 of file tabs.h.
Referenced by dbClosed(), dbOpened(), keyPressEvent(), and Tabs().
MainStack* Tabs::mainStack [private]
Definition at line 44 of file tabs.h.
Referenced by closeEvent(), keyPressEvent(), and Tabs().
ReportStack* Tabs::reportStack [private]
Definition at line 47 of file tabs.h.
Referenced by dbClosed(), dbOpened(), keyPressEvent(), and Tabs().
Settings* Tabs::settings [private]
Definition at line 41 of file tabs.h.
Referenced by quit(), and Tabs().
The documentation for this class was generated from the following files:
tabs.h
tabs.cpp