BalanceSheetEditor Class Reference
#include <balanceSheetEditor.h>
Public Member Functions
BalanceSheetEditor (QWidget *parent=0, const char *name=0)
~BalanceSheetEditor ()
Private Slots
void updateSection (void *)
void addElement (int category)
void addAssets ()
void addLiabilities ()
void addEquities ()
void oneAccountToggled ()
void rangeAccountToggled ()
void updateAccounts ()
Private Member Functions
void listSection (ElementSection *section)
void deleteSection (ElementSection *section)
Private Attributes
Database * db
QStringList accounts
QFrame * frame
QVBoxLayout * vBoxLayout
BalanceSheetEditor::ElementSection assets
BalanceSheetEditor::ElementSection liabilities
BalanceSheetEditor::ElementSection equities
xx xx xx xx xx xx xx xx xx
struct {
 QDialog * main
 QVBoxLayout * vBoxLayout
 QRadioButton * oneAccount
 QFrame * oneAccountFrame
 QHBoxLayout * oneAccountHBoxLayout
 QLabel * oneAccountLabel
 AccountList * oneAccountEdit
 QRadioButton * rangeAccount
 QFrame * rangeAccountFrame
 QHBoxLayout * rangeAccountHBoxLayout
 QFrame * rangeAccountFrameList
 QVBoxLayout * rangeAccountFrameListVBoxLayout
 QFrame * rangeBeginEndFrame
 QHBoxLayout * rangeBeginEndHBoxLayout
 QLabel * rangeBegin
 AccountList * rangeBeginEdit
 QLabel * rangeBetween
 AccountList * rangeEndEdit
 QFrame * rangeDescFrame
 QHBoxLayout * rangeDescFrameHBoxLayout
 QLabel * rangeDesc
 QLineEdit * rangeDescEdit
 QFrame * buttonFrame
 QHBoxLayout * buttonFrameHBoxLayout
 QPushButton * ok
 QPushButton * cancel
} dialog
Constructor & Destructor Documentation
BalanceSheetEditor::BalanceSheetEditor (QWidget * parent = 0, const char * name = 0)
Definition at line 18 of file balanceSheetEditor.cpp.
References accounts, addAssets(), BalanceSheetEditor::ElementSection::addButton, addEquities(), addLiabilities(), assets, BalanceSheetEditor::ElementSection::bottomFrame, BalanceSheetEditor::ElementSection::bottomHBoxLayout, db, equities, frame, Database::getAccountsList(), Database::instance(), BalanceSheetEditor::ElementSection::label, liabilities, listSection(), BalanceSheetEditor::ElementSection::listView, BalanceSheetEditor::ElementSection::topFrame, BalanceSheetEditor::ElementSection::topHBoxLayout, updateAccounts(), and vBoxLayout.
19     : QScrollView(parent,name)
20 {
21     db = Database::instance();
22 
23     setResizePolicy(QScrollView::AutoOneFit);
24     setMargins(5,5,5,5);
25     
26     connect(db, SIGNAL(accountsChanged()), this, SLOT(updateAccounts()));
27     accounts = db->getAccountsList();
28    
29     frame = new QFrame(viewport());
30     vBoxLayout = new QVBoxLayout(frame);
31     
32     assets.topFrame = new QFrame(frame);
33     assets.topHBoxLayout = new QHBoxLayout(assets.topFrame);
34     
35     
36     assets.label = new QLabel("<b>Assets:</b>", assets.topFrame);
37     assets.addButton = new QPushButton(
38             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/addElement.png") ),
39             "Add to Assets", assets.topFrame);
40     connect(assets.addButton, SIGNAL(clicked()), this, SLOT(addAssets()));
41 
42     assets.topHBoxLayout->addWidget(assets.label);
43     assets.topHBoxLayout->addStretch();
44     assets.topHBoxLayout->addWidget(assets.addButton);
45     
46     assets.bottomFrame = new QFrame(frame);
47     assets.bottomHBoxLayout = new QHBoxLayout(assets.bottomFrame);
48     listSection(&assets);
49     
50     assets.bottomHBoxLayout->addSpacing(5);
51     assets.bottomHBoxLayout->addWidget(assets.listView);
52     
53     vBoxLayout->addWidget(assets.topFrame);
54     vBoxLayout->addSpacing(5);
55 
56     vBoxLayout->addWidget(assets.bottomFrame);
57     vBoxLayout->addSpacing(10);
58    
59 
60     liabilities.topFrame = new QFrame(frame);
61     liabilities.topHBoxLayout = new QHBoxLayout(liabilities.topFrame);
62     
63     liabilities.label = new QLabel("<b>Liabilities:</b>", liabilities.topFrame);
64     liabilities.addButton = new QPushButton(
65             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/addElement.png") ),
66             "Add to Liabilities", liabilities.topFrame);
67     connect(liabilities.addButton, SIGNAL(clicked()), this, SLOT(addLiabilities()));
68     
69     liabilities.topHBoxLayout->addWidget(liabilities.label);
70     liabilities.topHBoxLayout->addStretch();
71     liabilities.topHBoxLayout->addWidget(liabilities.addButton);
72     
73     liabilities.bottomFrame = new QFrame(frame);
74     liabilities.bottomHBoxLayout = new QHBoxLayout(liabilities.bottomFrame);
75     listSection(&liabilities);
76     
77     liabilities.bottomHBoxLayout->addSpacing(5);
78     liabilities.bottomHBoxLayout->addWidget(liabilities.listView);
79     
80     vBoxLayout->addWidget(liabilities.topFrame);
81     vBoxLayout->addSpacing(5);
82     vBoxLayout->addWidget(liabilities.bottomFrame);
83     vBoxLayout->addSpacing(10);
84    
85     equities.topFrame = new QFrame(frame);
86     equities.topHBoxLayout = new QHBoxLayout(equities.topFrame);
87     
88     equities.label = new QLabel("<b>Equities:</b>", equities.topFrame);
89     equities.addButton = new QPushButton(
90             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/addElement.png") ),
91             "Add to Equities", equities.topFrame);
92     connect(equities.addButton, SIGNAL(clicked()), this, SLOT(addEquities()));
93     
94     equities.topHBoxLayout->addWidget(equities.label);
95     equities.topHBoxLayout->addStretch();
96     equities.topHBoxLayout->addWidget(equities.addButton);
97     
98     equities.bottomFrame = new QFrame(frame);
99     equities.bottomHBoxLayout = new QHBoxLayout(equities.bottomFrame);
100     listSection(&equities);
101     
102     equities.bottomHBoxLayout->addSpacing(5);
103     equities.bottomHBoxLayout->addWidget(equities.listView);
104     
105     vBoxLayout->addWidget(equities.topFrame);
106     vBoxLayout->addSpacing(5);
107     vBoxLayout->addWidget(equities.bottomFrame);
108     
109     vBoxLayout->addStretch();
110     
111     addChild(frame);
112 }
BalanceSheetEditor::~BalanceSheetEditor ()
Definition at line 114 of file balanceSheetEditor.cpp.
References assets, BalanceSheetEditor::ElementSection::elements, equities, and liabilities.
115 {
116     for(unsigned int i = 0; i < assets.elements.size(); i++)
117         delete assets.elements[i];
118     assets.elements.clear();
119     
120     for(unsigned int i = 0; i < liabilities.elements.size(); i++)
121         delete liabilities.elements[i];
122     liabilities.elements.clear();
123     
124     for(unsigned int i = 0; i < equities.elements.size(); i++)
125         delete equities.elements[i];
126     equities.elements.clear();
127 }
Member Function Documentation
void BalanceSheetEditor::addAssets () [private, slot]
Definition at line 336 of file balanceSheetEditor.cpp.
References addElement(), assets, and updateSection().
Referenced by BalanceSheetEditor().
337 {
338     addElement((int)Database::balanceAssets);
339     updateSection(&assets);
340 }
void BalanceSheetEditor::addElement (int category) [private, slot]
Definition at line 193 of file balanceSheetEditor.cpp.
References accounts, Database::createElement(), db, dialog, oneAccountToggled(), and rangeAccountToggled().
Referenced by addAssets(), addEquities(), and addLiabilities().
194 {
195     dialog.main = new QDialog;
196     switch((Database::editorCategories)category)
197     {
198         case Database::balanceAssets:
199             dialog.main->setCaption("Add to Assets");
200             break;
201         case Database::balanceLiabilities:
202             dialog.main->setCaption("Add to Liabilities");
203             break;
204         case Database::balanceEquities:
205             dialog.main->setCaption("Add to Equities");
206             break;
207         default:
208             break;
209     }
210     
211     dialog.vBoxLayout = new QVBoxLayout(dialog.main);
212     dialog.vBoxLayout->setMargin(5);
213     dialog.vBoxLayout->setSpacing(5);
214     
215     dialog.oneAccount = new QRadioButton("One Account", dialog.main);
216     connect(dialog.oneAccount, SIGNAL(clicked()), this, SLOT(oneAccountToggled()));
217         
218     dialog.oneAccountFrame = new QFrame(dialog.main);
219     dialog.oneAccountHBoxLayout = new QHBoxLayout(dialog.oneAccountFrame);
220     dialog.oneAccountHBoxLayout->setSpacing(5);
221     
222     dialog.oneAccountHBoxLayout->addSpacing(5);
223     dialog.oneAccountLabel = new QLabel("Account:", dialog.oneAccountFrame);
224     dialog.oneAccountHBoxLayout->addWidget(dialog.oneAccountLabel);
225     dialog.oneAccountEdit = new AccountList(dialog.oneAccountFrame, 0, accounts);
226     dialog.oneAccountHBoxLayout->addWidget(dialog.oneAccountEdit);
227     dialog.oneAccountHBoxLayout->addStretch();
228        
229     dialog.rangeAccount = new QRadioButton("Range of Accounts", dialog.main);
230     connect(dialog.rangeAccount, SIGNAL(clicked()), this, SLOT(rangeAccountToggled()));
231        
232     dialog.rangeAccountFrame = new QFrame(dialog.main, "rangeAccountFrame");
233     dialog.rangeAccountHBoxLayout = new QHBoxLayout(dialog.rangeAccountFrame);
234     dialog.rangeAccountHBoxLayout->addSpacing(5);
235     
236     dialog.rangeAccountFrameList = new QFrame(dialog.rangeAccountFrame);
237     dialog.rangeAccountFrameListVBoxLayout = new QVBoxLayout(dialog.rangeAccountFrameList);
238     dialog.rangeAccountFrameListVBoxLayout->setSpacing(5);
239     
240     dialog.rangeBeginEndFrame = new QFrame(dialog.rangeAccountFrameList);
241     dialog.rangeBeginEndHBoxLayout = new QHBoxLayout(dialog.rangeBeginEndFrame);
242     dialog.rangeBeginEndHBoxLayout->setSpacing(5);
243     
244     dialog.rangeBegin = new QLabel("Begin:", dialog.rangeBeginEndFrame);
245     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBegin);
246     dialog.rangeBeginEdit = new AccountList(dialog.rangeBeginEndFrame, 0, accounts);
247     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBeginEdit);
248     dialog.rangeBetween = new QLabel("to", dialog.rangeBeginEndFrame);
249     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBetween);
250     dialog.rangeEndEdit = new AccountList(dialog.rangeBeginEndFrame, 0, accounts);
251     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeEndEdit);
252     dialog.rangeBeginEndHBoxLayout->addStretch();
253     
254     dialog.rangeDescFrame = new QFrame(dialog.rangeAccountFrameList);
255     dialog.rangeDescFrameHBoxLayout = new QHBoxLayout(dialog.rangeDescFrame);
256     dialog.rangeDescFrameHBoxLayout->setSpacing(5);
257     
258     dialog.rangeDesc = new QLabel("Description:", dialog.rangeDescFrame);
259     dialog.rangeDescFrameHBoxLayout->addWidget(dialog.rangeDesc);
260     dialog.rangeDescEdit = new QLineEdit(dialog.rangeDescFrame);
261     dialog.rangeDescFrameHBoxLayout->addWidget(dialog.rangeDescEdit);
262     
263     dialog.rangeAccountFrameListVBoxLayout->addWidget(dialog.rangeBeginEndFrame);
264     dialog.rangeAccountFrameListVBoxLayout->addWidget(dialog.rangeDescFrame);
265     
266     dialog.rangeAccountHBoxLayout->addWidget(dialog.rangeAccountFrameList);
267     
268         
269     dialog.buttonFrame = new QFrame(dialog.main);
270     dialog.buttonFrameHBoxLayout = new QHBoxLayout(dialog.buttonFrame);
271     dialog.buttonFrameHBoxLayout->setSpacing(5);
272     dialog.buttonFrameHBoxLayout->addStretch();
273     
274     dialog.ok = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/addElement.png")),
275             "Add", dialog.buttonFrame);
276     connect(dialog.ok, SIGNAL(clicked()), dialog.main, SLOT(accept()));
277     dialog.buttonFrameHBoxLayout->addWidget(dialog.ok);
278     
279     dialog.cancel = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")),
280             "Cancel", dialog.buttonFrame);
281     connect(dialog.cancel, SIGNAL(clicked()), dialog.main, SLOT(reject()));
282     dialog.buttonFrameHBoxLayout->addWidget(dialog.cancel);
283     
284     
285     dialog.vBoxLayout->addWidget(dialog.oneAccount);
286     dialog.vBoxLayout->addWidget(dialog.oneAccountFrame);
287     dialog.vBoxLayout->addWidget(dialog.rangeAccount);
288     dialog.vBoxLayout->addWidget(dialog.rangeAccountFrame);
289     dialog.vBoxLayout->addSpacing(10);
290     dialog.vBoxLayout->addWidget(dialog.buttonFrame);
291     
292     oneAccountToggled();
293     
294     if(dialog.main->exec())
295     {
296         if(dialog.oneAccount->isChecked())
297             db->createElement((Database::editorCategories)category,
298                                       "0", "", dialog.oneAccountEdit->accountNumber(), "");
299         else
300             db->createElement((Database::editorCategories)category,
301                                       "1", dialog.rangeDescEdit->text(),
302                                       dialog.rangeBeginEdit->accountNumber(), dialog.rangeEndEdit->accountNumber());
303     }
304     
305     delete dialog.main;
306 }
void BalanceSheetEditor::addEquities () [private, slot]
Definition at line 348 of file balanceSheetEditor.cpp.
References addElement(), equities, and updateSection().
Referenced by BalanceSheetEditor().
349 {
350     addElement((int)Database::balanceEquities);
351     updateSection(&equities);
352 }
void BalanceSheetEditor::addLiabilities () [private, slot]
Definition at line 342 of file balanceSheetEditor.cpp.
References addElement(), liabilities, and updateSection().
Referenced by BalanceSheetEditor().
343 {
344     addElement((int)Database::balanceLiabilities);
345     updateSection(&liabilities);
346 }
void BalanceSheetEditor::deleteSection (ElementSection * section) [private]
Definition at line 158 of file balanceSheetEditor.cpp.
References BalanceSheetEditor::ElementSection::elements, BalanceSheetEditor::ElementSection::listView, and BalanceSheetEditor::ElementSection::vBoxLayout.
Referenced by updateSection().
159 {
160     if(section->elements.size())
161     {
162         for(unsigned int i = 0; i < section->elements.size(); i++)
163             delete section->elements[i];
164         section->elements.clear();
165         delete section->vBoxLayout;
166     }
167     delete section->listView;
168 }
void BalanceSheetEditor::listSection (ElementSection * section) [private]
Definition at line 129 of file balanceSheetEditor.cpp.
References assets, BalanceSheetEditor::ElementSection::bottomFrame, db, BalanceSheetEditor::ElementSection::elements, equities, Database::getElements(), EditorElement::getFrame(), liabilities, BalanceSheetEditor::ElementSection::listView, updateSection(), and BalanceSheetEditor::ElementSection::vBoxLayout.
Referenced by BalanceSheetEditor(), and updateSection().
130 {
131     QPtrList<EditorElement> list;
132     if(section == &assets)
133         list = db->getElements(Database::balanceAssets);
134     if(section == &liabilities)
135         list = db->getElements(Database::balanceLiabilities);
136     if(section == &equities)
137         list = db->getElements(Database::balanceEquities);
138     
139     if(!list.isEmpty())
140     {
141         section->listView = new QFrame(section->bottomFrame);
142         section->vBoxLayout = new QVBoxLayout(section->listView);
143         
144         EditorElement *element;
145         
146         for(element = list.first(); element; element = list.next())
147         {
148             connect(element, SIGNAL(changed(void*)), this, SLOT(updateSection(void*)));
149             section->elements.push_back(element);
150             section->vBoxLayout->addWidget(element->getFrame(section->listView, (void*)section));
151         }
152     }
153     else
154         section->listView = new QLabel("No Entries", section->bottomFrame);
155     
156 }
void BalanceSheetEditor::oneAccountToggled () [private, slot]
Definition at line 308 of file balanceSheetEditor.cpp.
References dialog.
Referenced by addElement().
309 {
310     dialog.oneAccount->setChecked(true);
311     dialog.rangeAccount->setChecked(false);
312     dialog.oneAccountLabel->setEnabled(true);
313     dialog.oneAccountEdit->setEnabled(true);
314     dialog.rangeBegin->setEnabled(false);
315     dialog.rangeBeginEdit->setEnabled(false);
316     dialog.rangeBetween->setEnabled(false);
317     dialog.rangeEndEdit->setEnabled(false);
318     dialog.rangeDesc->setEnabled(false);
319     dialog.rangeDescEdit->setEnabled(false);
320 }
void BalanceSheetEditor::rangeAccountToggled () [private, slot]
Definition at line 322 of file balanceSheetEditor.cpp.
References dialog.
Referenced by addElement().
323 {
324     dialog.rangeAccount->setChecked(true);
325     dialog.oneAccount->setChecked(false);
326     dialog.oneAccountLabel->setEnabled(false);
327     dialog.oneAccountEdit->setEnabled(false);
328     dialog.rangeBegin->setEnabled(true);
329     dialog.rangeBeginEdit->setEnabled(true);
330     dialog.rangeBetween->setEnabled(true);
331     dialog.rangeEndEdit->setEnabled(true);
332     dialog.rangeDesc->setEnabled(true);
333     dialog.rangeDescEdit->setEnabled(true);
334 }
void BalanceSheetEditor::updateAccounts () [private, slot]
Definition at line 354 of file balanceSheetEditor.cpp.
References accounts, db, and Database::getAccountsList().
Referenced by BalanceSheetEditor().
355 {
356     accounts = db->getAccountsList();
357 }
void BalanceSheetEditor::updateSection (void *) [private, slot]
Definition at line 170 of file balanceSheetEditor.cpp.
References assets, BalanceSheetEditor::ElementSection::bottomHBoxLayout, deleteSection(), equities, liabilities, listSection(), and BalanceSheetEditor::ElementSection::listView.
Referenced by addAssets(), addEquities(), addLiabilities(), and listSection().
171 {
172     ElementSection *section = (ElementSection*)newSection;
173     deleteSection(section);
174     listSection(section);
175     
176     if(section == &assets) 
177     {
178         assets.bottomHBoxLayout->addWidget(assets.listView);
179         assets.listView->show();
180     }
181     if(section == &liabilities) 
182     {
183         liabilities.bottomHBoxLayout->addWidget(liabilities.listView);
184         liabilities.listView->show();
185     }
186     if(section == &equities) 
187     {
188         equities.bottomHBoxLayout->addWidget(equities.listView);
189         equities.listView->show();
190     }
191 }
Member Data Documentation
QStringList BalanceSheetEditor::accounts [private]
Definition at line 43 of file balanceSheetEditor.h.
Referenced by addElement(), BalanceSheetEditor(), and updateAccounts().
struct BalanceSheetEditor::ElementSection BalanceSheetEditor::assets [private]
Referenced by addAssets(), BalanceSheetEditor(), listSection(), updateSection(), and ~BalanceSheetEditor().
QFrame* BalanceSheetEditor::buttonFrame [private]
Definition at line 86 of file balanceSheetEditor.h.
QHBoxLayout* BalanceSheetEditor::buttonFrameHBoxLayout [private]
Definition at line 87 of file balanceSheetEditor.h.
QPushButton* BalanceSheetEditor::cancel [private]
Definition at line 89 of file balanceSheetEditor.h.
Database* BalanceSheetEditor::db [private]
Definition at line 41 of file balanceSheetEditor.h.
Referenced by addElement(), BalanceSheetEditor(), listSection(), and updateAccounts().
struct { ... } BalanceSheetEditor::dialog [private]
Referenced by addElement(), oneAccountToggled(), and rangeAccountToggled().
struct BalanceSheetEditor::ElementSection BalanceSheetEditor::equities [private]
Referenced by addEquities(), BalanceSheetEditor(), listSection(), updateSection(), and ~BalanceSheetEditor().
QFrame* BalanceSheetEditor::frame [private]
Definition at line 45 of file balanceSheetEditor.h.
Referenced by BalanceSheetEditor().
struct BalanceSheetEditor::ElementSection BalanceSheetEditor::liabilities [private]
Referenced by addLiabilities(), BalanceSheetEditor(), listSection(), updateSection(), and ~BalanceSheetEditor().
QDialog* BalanceSheetEditor::main [private]
Definition at line 64 of file balanceSheetEditor.h.
QPushButton* BalanceSheetEditor::ok [private]
Definition at line 88 of file balanceSheetEditor.h.
QRadioButton* BalanceSheetEditor::oneAccount [private]
Definition at line 66 of file balanceSheetEditor.h.
AccountList* BalanceSheetEditor::oneAccountEdit [private]
Definition at line 70 of file balanceSheetEditor.h.
QFrame* BalanceSheetEditor::oneAccountFrame [private]
Definition at line 67 of file balanceSheetEditor.h.
QHBoxLayout* BalanceSheetEditor::oneAccountHBoxLayout [private]
Definition at line 68 of file balanceSheetEditor.h.
QLabel* BalanceSheetEditor::oneAccountLabel [private]
Definition at line 69 of file balanceSheetEditor.h.
QRadioButton* BalanceSheetEditor::rangeAccount [private]
Definition at line 71 of file balanceSheetEditor.h.
QFrame* BalanceSheetEditor::rangeAccountFrame [private]
Definition at line 72 of file balanceSheetEditor.h.
QFrame* BalanceSheetEditor::rangeAccountFrameList [private]
Definition at line 74 of file balanceSheetEditor.h.
QVBoxLayout* BalanceSheetEditor::rangeAccountFrameListVBoxLayout [private]
Definition at line 75 of file balanceSheetEditor.h.
QHBoxLayout* BalanceSheetEditor::rangeAccountHBoxLayout [private]
Definition at line 73 of file balanceSheetEditor.h.
QLabel* BalanceSheetEditor::rangeBegin [private]
Definition at line 78 of file balanceSheetEditor.h.
AccountList* BalanceSheetEditor::rangeBeginEdit [private]
Definition at line 79 of file balanceSheetEditor.h.
QFrame* BalanceSheetEditor::rangeBeginEndFrame [private]
Definition at line 76 of file balanceSheetEditor.h.
QHBoxLayout* BalanceSheetEditor::rangeBeginEndHBoxLayout [private]
Definition at line 77 of file balanceSheetEditor.h.
QLabel* BalanceSheetEditor::rangeBetween [private]
Definition at line 80 of file balanceSheetEditor.h.
QLabel* BalanceSheetEditor::rangeDesc [private]
Definition at line 84 of file balanceSheetEditor.h.
QLineEdit* BalanceSheetEditor::rangeDescEdit [private]
Definition at line 85 of file balanceSheetEditor.h.
QFrame* BalanceSheetEditor::rangeDescFrame [private]
Definition at line 82 of file balanceSheetEditor.h.
QHBoxLayout* BalanceSheetEditor::rangeDescFrameHBoxLayout [private]
Definition at line 83 of file balanceSheetEditor.h.
AccountList* BalanceSheetEditor::rangeEndEdit [private]
Definition at line 81 of file balanceSheetEditor.h.
QVBoxLayout* BalanceSheetEditor::vBoxLayout [private]
Definition at line 65 of file balanceSheetEditor.h.
QVBoxLayout* BalanceSheetEditor::vBoxLayout [private]
Definition at line 46 of file balanceSheetEditor.h.
Referenced by BalanceSheetEditor().
The documentation for this class was generated from the following files:
balanceSheetEditor.h
balanceSheetEditor.cpp