MainStack Class Reference
#include <mainStack.h>
Public Slots
void closeClient ()
Signals
void switchToAccounts ()
void switchToJournal ()
void switchToReports ()
void dbOpened ()
void dbClosed ()
void nameChanged ()
void saveAndClearJournalTmp ()
void quit ()
Public Member Functions
MainStack (QWidget *parent=0, const char *name=0)
~MainStack ()
bool closed () const
Private Slots
void openDefault ()
void openNewDialog ()
void createNewDialog ()
void editName ()
void copyClient ()
void changePath ()
void import ()
void encrypt ()
void decrypt ()
void prepareQuit ()
Private Member Functions
void clientOpened ()
void switchWidget ()
bool eventFilter (QObject *target, QEvent *event)
Private Attributes
Database * db
Settings * settings
QString clientPath
QString exportPath
QString importPath
int active
xx xx xx xx xx xx xx xx xx
struct {
 QWidget * widget
 QHBoxLayout * hBoxLayout
 QVBoxLayout * vBoxLayout
 QVGroupBox * mainGroup
 QPushButton * openDefaultButton
 QPushButton * openNewButton
 QPushButton * createNewButton
 QVGroupBox * otherGroup
 QPushButton * pathButton
 QPushButton * importButton
 QPushButton * quitButton
} main
xx xx xx xx xx xx xx xx xx
struct {
 QPushButton * focusedButton
 QWidget * widget
 QVBoxLayout * vBoxLabel
 QHBoxLayout * hBoxLabel
 QPushButton * closeButton
 QHBoxLayout * hBoxLayout
 QVBoxLayout * vBoxLayout
 QVGroupBox * clientGroup
 QPushButton * accountsButton
 QPushButton * journalButton
 QPushButton * reportButton
 QVGroupBox * adminGroup
 QPushButton * editNameButton
 QPushButton * copyDatabaseButton
 QPushButton * cryptButton
} tasks
Constructor & Destructor Documentation
MainStack::MainStack (QWidget * parent = 0, const char * name = 0)
Definition at line 25 of file mainStack.cpp.
References active, changePath(), clientPath, createNewDialog(), Database::curClientExists(), db, exportPath, Settings::getClientPath(), Database::getCurClient(), Settings::getExportPath(), Settings::getImportPath(), importPath, Settings::instance(), Database::instance(), main, openDefault(), openNewDialog(), prepareQuit(), and settings.
26     : QWidgetStack(parent,name)
27 {
28     db = Database::instance();
29     settings = Settings::instance();
30 
31     clientPath = settings->getClientPath();
32     exportPath = settings->getExportPath();
33     importPath = settings->getImportPath();
34     
35     main.widget = new QWidget(this);
36     
37     main.hBoxLayout = new QHBoxLayout(main.widget);
38     
39     main.hBoxLayout->addStretch();
40     
41     main.vBoxLayout = new QVBoxLayout(main.hBoxLayout);
42     
43     main.vBoxLayout->addStretch();
44     
45     main.mainGroup = new QVGroupBox("Main Options", main.widget);
46     main.mainGroup->setInsideMargin(30);
47     main.mainGroup->setInsideSpacing(20);
48     
49     main.vBoxLayout->add(main.mainGroup);
50     
51     if(db->getCurClient() != "" && db->curClientExists())
52     {
53         main.openDefaultButton = new QPushButton(
54                 QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/openDefButton.png") ),
55                 "Open " + db->getCurClient(), main.mainGroup);
56         connect(main.openDefaultButton, SIGNAL(clicked()), this, SLOT(openDefault()));
57         main.openDefaultButton->setDefault(true);
58         main.openDefaultButton->setFocus();
59         main.openDefaultButton->installEventFilter(this);
60     }
61     else
62     {
63         main.openDefaultButton = new QPushButton(
64                 QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/openDefButton.png") ),
65                 "Open ...", main.mainGroup);
66         main.openDefaultButton->setEnabled(false);
67     }
68     
69     main.openNewButton = new QPushButton(
70             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/openNewButton.png") ),
71             "Open a Different Client", main.mainGroup);
72     connect(main.openNewButton, SIGNAL(clicked()), this, SLOT(openNewDialog()));
73     main.openNewButton->installEventFilter(this);
74     
75     main.createNewButton = new QPushButton(
76             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/createNewButton.png") ),
77             "Create a New Client", main.mainGroup);
78     connect(main.createNewButton, SIGNAL(clicked()), this, SLOT(createNewDialog()));
79     main.createNewButton->installEventFilter(this);
80     
81     main.vBoxLayout->addSpacing(30);
82     
83     main.otherGroup = new QVGroupBox("Other Options", main.widget);
84     main.otherGroup->setInsideMargin(30);
85     main.otherGroup->setInsideSpacing(20);
86     
87     main.vBoxLayout->add(main.otherGroup);
88     
89     main.pathButton = new QPushButton(
90             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/pathButton.png") ),
91             "Change Client Database Folder", main.otherGroup);
92     connect(main.pathButton, SIGNAL(clicked()), this, SLOT(changePath()));
93     main.pathButton->installEventFilter(this);
94 
95     main.importButton = new QPushButton(
96             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/importButton.png") ),
97             "Import a Database File", main.otherGroup);
98     connect(main.importButton, SIGNAL(clicked()), this, SLOT(import()));
99     main.importButton->installEventFilter(this);
100     
101     main.quitButton = new QPushButton(
102             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/quitButton.png") ),
103             "Quit General Ledger", main.otherGroup);
104     connect(main.quitButton, SIGNAL(clicked()), this, SLOT(prepareQuit()));
105     main.quitButton->installEventFilter(this);
106     
107     main.vBoxLayout->addStretch();
108     
109     main.hBoxLayout->addStretch();
110     
111     addWidget(main.widget, 0);
112     
113     active = 0;
114 }
MainStack::~MainStack ()
Definition at line 116 of file mainStack.cpp.
117 {}
Member Function Documentation
void MainStack::changePath () [private, slot]
Definition at line 584 of file mainStack.cpp.
References clientPath, Settings::setClientPath(), and settings.
Referenced by MainStack().
585 {
586     QString path = QFileDialog::getExistingDirectory(
587             clientPath,
588             this,
589             0,
590             "Choose Client Database Folder");
591 
592     if(!path.isEmpty())
593         settings->setClientPath(path);
594 }
void MainStack::clientOpened () [private]
Definition at line 127 of file mainStack.cpp.
References active, closeClient(), copyClient(), db, decrypt(), editName(), encrypt(), Database::getCurClient(), Database::isEncrypted(), main, openDefault(), switchToAccounts(), switchToJournal(), switchToReports(), switchWidget(), tasks, and widget.
Referenced by createNewDialog(), decrypt(), encrypt(), openDefault(), and openNewDialog().
128 {
129     main.openDefaultButton->setText("Open " + db->getCurClient());
130     main.openDefaultButton->setEnabled(true);
131     main.openDefaultButton->installEventFilter(this);
132     disconnect(main.openDefaultButton, SIGNAL(clicked()), this, SLOT(openDefault()));
133     connect(main.openDefaultButton, SIGNAL(clicked()), this, SLOT(openDefault()));
134     
135     active = 0;
136 
137     if(widget(1))
138     {
139         removeWidget(tasks.widget);
140         delete tasks.cryptButton;
141         delete tasks.copyDatabaseButton;
142         delete tasks.editNameButton;
143         delete tasks.adminGroup;
144         delete tasks.reportButton;
145         delete tasks.journalButton;
146         delete tasks.accountsButton;
147         delete tasks.clientGroup;
148         delete tasks.vBoxLayout;
149         delete tasks.hBoxLayout;
150         delete tasks.closeButton;
151         delete tasks.hBoxLabel;
152         delete tasks.vBoxLabel;
153         delete tasks.widget;
154     }
155     
156     tasks.widget = new QWidget(this);
157     
158     tasks.vBoxLabel = new QVBoxLayout(tasks.widget);
159     
160     tasks.hBoxLabel = new QHBoxLayout(tasks.vBoxLabel);
161     tasks.hBoxLabel->setMargin(5);
162     
163     tasks.closeButton = new QPushButton(
164             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/closeClient.png") ),
165             "Close Client (F8)", tasks.widget);
166     tasks.closeButton->setFocusPolicy(QWidget::NoFocus);
167     connect(tasks.closeButton, SIGNAL(clicked()), this, SLOT(closeClient()));
168     
169     tasks.hBoxLabel->addStretch();
170     tasks.hBoxLabel->addWidget(tasks.closeButton);
171     
172     tasks.hBoxLayout = new QHBoxLayout(tasks.vBoxLabel);
173     
174     tasks.hBoxLayout->addStretch();
175     
176     tasks.vBoxLayout = new QVBoxLayout(tasks.hBoxLayout);
177     
178     tasks.vBoxLayout->addStretch();
179     
180     tasks.clientGroup = new QVGroupBox("Client Tasks", tasks.widget);
181     tasks.clientGroup->setInsideMargin(30);
182     tasks.clientGroup->setInsideSpacing(20);
183     
184     tasks.vBoxLayout->add(tasks.clientGroup);
185     
186     tasks.accountsButton = new QPushButton(
187             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/accountsTab.png") ),
188             "Accounts", tasks.clientGroup);
189     connect(tasks.accountsButton, SIGNAL(clicked()), this, SIGNAL(switchToAccounts()));
190     tasks.accountsButton->setDefault(true);
191     tasks.accountsButton->setFocus();
192     tasks.focusedButton = tasks.accountsButton;
193     tasks.accountsButton->installEventFilter(this);
194     
195     tasks.journalButton = new QPushButton(
196             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/journalTab.png") ),
197             "Journal Entry", tasks.clientGroup);
198     connect(tasks.journalButton, SIGNAL(clicked()), this, SIGNAL(switchToJournal()));
199     tasks.journalButton->installEventFilter(this);
200     
201     tasks.reportButton = new QPushButton(
202             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/reportTab.png") ),
203             "Reports", tasks.clientGroup);
204     connect(tasks.reportButton, SIGNAL(clicked()), this, SIGNAL(switchToReports()));
205     tasks.reportButton->installEventFilter(this);
206     
207     tasks.vBoxLayout->addSpacing(30);
208     
209     tasks.adminGroup = new QVGroupBox("Administrative Options", tasks.widget);
210     tasks.adminGroup->setInsideMargin(30);
211     tasks.adminGroup->setInsideSpacing(20);
212     
213     tasks.vBoxLayout->add(tasks.adminGroup);
214     
215     tasks.editNameButton = new QPushButton(
216             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/editNameButton.png") ),
217             "Edit Client Name", tasks.adminGroup);
218     connect(tasks.editNameButton, SIGNAL(clicked()), this, SLOT(editName()));
219     tasks.editNameButton->installEventFilter(this);
220     
221     tasks.copyDatabaseButton = new QPushButton(
222             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/copyDatabaseButton.png") ),
223             "Copy Client Database to File", tasks.adminGroup);
224     connect(tasks.copyDatabaseButton, SIGNAL(clicked()), this, SLOT(copyClient()));
225     tasks.copyDatabaseButton->installEventFilter(this);
226     
227 
228     if(db->isEncrypted())
229     {
230         tasks.cryptButton = new QPushButton(
231                 QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/decryptButton.png") ),
232                 "Decrypt Database", tasks.adminGroup);
233         connect(tasks.cryptButton, SIGNAL(clicked()), this, SLOT(decrypt()));
234     }
235     else
236     {
237         tasks.cryptButton = new QPushButton(
238                 QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/encryptButton.png") ),
239                 "Encrypt Database with Password", tasks.adminGroup);
240         connect(tasks.cryptButton, SIGNAL(clicked()), this, SLOT(encrypt()));
241     }
242     tasks.cryptButton->installEventFilter(this);
243     
244     tasks.vBoxLayout->addStretch();
245     
246     tasks.hBoxLayout->addStretch();
247     
248     addWidget(tasks.widget, 1);
249         
250     switchWidget();
251 }
void MainStack::closeClient () [slot]
Definition at line 706 of file mainStack.cpp.
References active, Database::closeDb(), db, dbClosed(), Database::journalTmpEmpty(), saveAndClearJournalTmp(), switchToJournal(), and switchWidget().
Referenced by clientOpened(), Tabs::closeEvent(), eventFilter(), and prepareQuit().
707 {
708     if(active == 0)
709         return;
710 
711     if(!(db->journalTmpEmpty()))
712     {
713         CloseDialog dialog;
714         dialog.exec();
715 
716         switch(dialog.result())
717         {
718             case 0:
719                 emit saveAndClearJournalTmp();
720                 break;
721             case 1:
722                 break;
723             case 2:
724                 emit switchToJournal();
725                 return;
726                 break;
727             default:
728                 break;
729         }
730     }
731 
732     db->closeDb();
733     switchWidget();
734     emit dbClosed();
735 }
bool MainStack::closed () const
Definition at line 119 of file mainStack.cpp.
References active.
Referenced by Tabs::closeEvent().
120 {
121     if(active == 0)
122         return true;
123     else
124         return false;
125 }
void MainStack::copyClient () [private, slot]
Definition at line 571 of file mainStack.cpp.
References Database::copyDb(), db, and exportPath.
Referenced by clientOpened().
572 {
573     QString file = QFileDialog::getSaveFileName(
574             exportPath,
575             "Client Database (*.db *.dbx)",
576             this,
577             0,
578             "Copy Client Database to File");
579     
580     if(!file.isEmpty())
581         db->copyDb(file);
582 }
void MainStack::createNewDialog () [private, slot]
Definition at line 470 of file mainStack.cpp.
References clientOpened(), Database::createNew(), db, dbOpened(), and vBoxLayout.
Referenced by MainStack().
471 {
472     QDialog dialog;
473     dialog.setCaption("Create a New Client");
474     
475     QVBoxLayout vBoxLayout(&dialog);
476     vBoxLayout.setMargin(5);
477     vBoxLayout.setSpacing(5);
478     
479     QLabel labelName("Input the Client's Name:", &dialog);
480     vBoxLayout.addWidget(&labelName);
481     
482     QLineEdit lineEdit(&dialog);
483     lineEdit.setMaxLength(50);
484     lineEdit.setFocus();
485     vBoxLayout.addWidget(&lineEdit);
486     
487     QHBoxLayout hBoxYearEnd(&vBoxLayout);
488     hBoxYearEnd.setSpacing(5);
489 
490     vBoxLayout.addSpacing(10);
491     
492     QLabel yearEndLabel("Year-End Date:", &dialog);
493     QComboBox yearEndList(false, &dialog);
494     QStringList yearEndStrings;
495     yearEndStrings << "January 31" << "February 28" << "March 31" << "April 30"
496             << "May 31" << "June 30" << "July 31" << "August 31" << "September 30"
497             << "October 31" << "November 30" << "December 31";
498     yearEndList.insertStringList(yearEndStrings);
499     
500     hBoxYearEnd.addWidget(&yearEndLabel);
501     hBoxYearEnd.addWidget(&yearEndList);
502     
503     QHBoxLayout hBoxButtons(&vBoxLayout);
504     hBoxButtons.setSpacing(5);
505     
506     QPushButton createButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/createNewButton.png")), "Create", &dialog);
507     createButton.setDefault(true);
508     connect(&createButton, SIGNAL(clicked()), &dialog, SLOT(accept()));
509     
510     QPushButton cancelButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")), "Cancel", &dialog);
511     connect(&cancelButton, SIGNAL(clicked()), &dialog, SLOT(reject()));
512     
513     hBoxButtons.addStretch();
514     hBoxButtons.addWidget(&createButton);
515     hBoxButtons.addWidget(&cancelButton);
516     
517     if(dialog.exec() && !lineEdit.text().isEmpty())
518     {
519         if(db->createNew(lineEdit.text(), yearEndList.currentText()))
520         {
521             clientOpened();
522             emit dbOpened();
523         }
524     }
525 }
void MainStack::dbClosed () [signal]
Referenced by closeClient().
void MainStack::dbOpened () [signal]
Referenced by createNewDialog(), openDefault(), and openNewDialog().
void MainStack::decrypt () [private, slot]
Definition at line 668 of file mainStack.cpp.
References clientOpened(), db, Database::decryptDb(), hBoxLayout, and vBoxLayout.
Referenced by clientOpened().
669 {
670     QDialog dialog;
671     dialog.setCaption("Decrypt Database");
672 
673     QVBoxLayout vBoxLayout(&dialog);
674     vBoxLayout.setMargin(5);
675     vBoxLayout.setSpacing(5);
676 
677     QLabel label("<nobr>Are you sure you want to decrypt the database?</nobr>", &dialog);
678 
679     vBoxLayout.addWidget(&label);
680     vBoxLayout.addSpacing(10);
681 
682     QHBoxLayout hBoxLayout(&vBoxLayout);
683     hBoxLayout.setSpacing(5);
684 
685     QPushButton decryptButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/decryptButton.png")),
686                               "Decrypt", &dialog);
687     connect(&decryptButton, SIGNAL(clicked()), &dialog, SLOT(accept()));
688     decryptButton.setDefault(false);
689 
690     QPushButton cancelButton(QIconSet(QPixmap::fromMimeSource(QString(ICON_PATH + "/cancelButton.png"))),
691                              "Cancel", &dialog);
692     connect(&cancelButton, SIGNAL(clicked()), &dialog, SLOT(reject()));
693     cancelButton.setDefault(true);
694 
695     hBoxLayout.addStretch();
696     hBoxLayout.addWidget(&decryptButton);
697     hBoxLayout.addWidget(&cancelButton);
698 
699     if(dialog.exec())
700     {
701         db->decryptDb();
702         clientOpened();
703     }
704 }
void MainStack::editName () [private, slot]
Definition at line 527 of file mainStack.cpp.
References db, Database::editName(), Database::getCurClient(), hBoxLayout, main, nameChanged(), and vBoxLayout.
Referenced by clientOpened().
528 {
529     QDialog dialog;
530     dialog.setCaption("Edit Client Name");
531 
532     QVBoxLayout vBoxLayout(&dialog);
533     vBoxLayout.setMargin(5);
534     vBoxLayout.setSpacing(5);
535 
536     QLabel label("Input a new client name:", &dialog);
537 
538     vBoxLayout.addWidget(&label);
539 
540     QLineEdit lineEdit(db->getCurClient(), &dialog);
541     lineEdit.setMaxLength(50);
542     lineEdit.setFocus();
543 
544     vBoxLayout.addWidget(&lineEdit);
545     vBoxLayout.addSpacing(10);
546 
547     QHBoxLayout hBoxLayout(&vBoxLayout);
548 
549     QPushButton okButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/editNameButton.png")),
550                          "Change Name", &dialog);
551     connect(&okButton, SIGNAL(clicked()), &dialog, SLOT(accept()));
552 
553     QPushButton cancelButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")),
554                              "Cancel", &dialog);
555     connect(&cancelButton, SIGNAL(clicked()), &dialog, SLOT(reject()));
556 
557     cancelButton.setDefault(false);
558     okButton.setDefault(true);
559 
560     hBoxLayout.addStretch();
561     hBoxLayout.addWidget(&okButton);
562     hBoxLayout.addWidget(&cancelButton);
563 
564     if( dialog.exec() && !(lineEdit.text().isEmpty()))
565         db->editName(lineEdit.text());
566 
567     main.openDefaultButton->setText("Open " + db->getCurClient());
568     emit nameChanged();
569 }
void MainStack::encrypt () [private, slot]
Definition at line 609 of file mainStack.cpp.
References clientOpened(), db, Database::encryptDb(), and vBoxLayout.
Referenced by clientOpened().
610 {
611     QDialog dialog;
612     dialog.setCaption("Encrypt Database");
613     
614     QVBoxLayout vBoxLayout(&dialog);
615     vBoxLayout.setMargin(5);
616     vBoxLayout.setSpacing(5);
617     
618     QHBoxLayout hBoxTop(&vBoxLayout);
619     hBoxTop.setSpacing(5);
620     
621     QLabel label1("Input a password:", &dialog);
622     QLineEdit password1(&dialog);
623     password1.setMaxLength(20);
624     password1.setEchoMode(QLineEdit::Password);
625     hBoxTop.addStretch();
626     hBoxTop.addWidget(&label1);
627     hBoxTop.addWidget(&password1);
628     
629     QHBoxLayout hBoxMiddle(&vBoxLayout);
630     hBoxMiddle.setSpacing(5);
631 
632     vBoxLayout.addSpacing(10);
633     
634     QLabel label2("Repeat:", &dialog);
635     QLineEdit password2(&dialog);
636     password2.setMaxLength(20);
637     password2.setEchoMode(QLineEdit::Password);
638     hBoxMiddle.addStretch();
639     hBoxMiddle.addWidget(&label2);
640     hBoxMiddle.addWidget(&password2);
641     
642     QHBoxLayout hBoxBottom(&vBoxLayout);
643     hBoxBottom.setSpacing(5);
644     
645     QPushButton encryptButton(QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/encryptButton.png") ),
646                               "Encrypt", &dialog);
647     connect(&encryptButton, SIGNAL(clicked()), &dialog, SLOT(accept()));
648     
649     QPushButton cancelButton(QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png") ),
650                              "Cancel", &dialog);
651     connect(&cancelButton, SIGNAL(clicked()), &dialog, SLOT(reject()));
652     
653     hBoxBottom.addStretch();
654     hBoxBottom.addWidget(&encryptButton);
655     hBoxBottom.addWidget(&cancelButton);
656     
657     while(dialog.exec())
658     {
659         if(password1.text() == password2.text())
660         {
661             db->encryptDb(password1.text());
662             clientOpened();
663             break;
664         }
665     }
666 }
bool MainStack::eventFilter (QObject * target, QEvent * event) [private]
Definition at line 269 of file mainStack.cpp.
References active, closeClient(), and tasks.
270 {
271     if(event->type() == QEvent::KeyPress)
272     {
273         QKeyEvent *keyEvent = (QKeyEvent *)event;
274         if(keyEvent->key() == Key_F8 && active == 1)
275         {
276             closeClient();
277             return true;
278         }
279     }
280     if(event->type() == QEvent::FocusIn)
281     {
282     //    if(typeid(*target) == typeid(QPushButton))
283         {
284             ((QPushButton*)target)->setDefault(true);
285             if(active == 1)
286                 tasks.focusedButton = (QPushButton*)target;
287         }
288     }
289     if(event->type() == QEvent::FocusOut)
290     {
291     //    if(typeid(*target) == typeid(QPushButton))
292             ((QPushButton*)target)->setDefault(false);
293     }
294     if(event->type() == QEvent::Show)
295     {
296         if(active == 1)
297             tasks.focusedButton->setFocus();
298     }
299     
300     return QWidgetStack::eventFilter(target,event);
301 }
void MainStack::import () [private, slot]
Definition at line 596 of file mainStack.cpp.
References db, Database::importDb(), and importPath.
597 {
598     QString file = QFileDialog::getOpenFileName(
599             importPath,
600             "Client Database (*.db *.dbx)",
601             this,
602             0,
603             "Import a Database File");
604 
605     if(!file.isEmpty())
606         db->importDb(file);
607 }
void MainStack::nameChanged () [signal]
Referenced by editName().
void MainStack::openDefault () [private, slot]
Definition at line 303 of file mainStack.cpp.
References clientOpened(), db, dbOpened(), Database::getCurDb(), and Database::openNew().
Referenced by clientOpened(), and MainStack().
304 {
305     QString file = db->getCurDb();
306 
307     bool encrypted = false;
308 
309     if(file.right(4) == ".dbx")
310     {
311         file.truncate(file.length() - 4);
312         encrypted = true;
313     }
314     else if(file.right(3) == ".db")
315         file.truncate(file.length() - 3);
316 
317     QString password(QString::null);
318 
319     if(encrypted)
320     {
321         QDialog dialog2;
322         dialog2.setCaption("Enter Password");
323     
324         QVBoxLayout vBoxLayout2(&dialog2);
325         vBoxLayout2.setMargin(5);
326         vBoxLayout2.setSpacing(5);
327     
328         QLabel label2("<nobr>This database is encrypted</nobr><br><nobr>Enter the password:</nobr>", &dialog2);
329         QLineEdit password2(&dialog2);
330         password2.setMaxLength(20);
331         password2.setEchoMode(QLineEdit::Password);
332         vBoxLayout2.addStretch();
333         vBoxLayout2.addWidget(&label2);
334         vBoxLayout2.addWidget(&password2);
335         vBoxLayout2.addSpacing(10);
336     
337         QHBoxLayout hBoxLayout2(&vBoxLayout2);
338         hBoxLayout2.setSpacing(5);
339     
340         QPushButton decryptButton2(QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/decryptButton.png") ),
341                                    "Open", &dialog2);
342         connect(&decryptButton2, SIGNAL(clicked()), &dialog2, SLOT(accept()));
343     
344         QPushButton cancelButton2(QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png") ),
345                                   "Cancel", &dialog2);
346         connect(&cancelButton2, SIGNAL(clicked()), &dialog2, SLOT(reject()));
347     
348         hBoxLayout2.addStretch();
349         hBoxLayout2.addWidget(&decryptButton2);
350         hBoxLayout2.addWidget(&cancelButton2);
351 
352         while(dialog2.exec())
353         {
354             password = password2.text();
355 
356             if(db->openNew(file, password))
357             {
358                 clientOpened();
359                 emit dbOpened();
360                 break;
361             }
362         }
363     }
364     else
365     {
366         if(db->openNew(file, password))
367         {
368             clientOpened();
369             emit dbOpened();
370         }
371     }
372 }
void MainStack::openNewDialog () [private, slot]
Definition at line 374 of file mainStack.cpp.
References clientOpened(), db, dbOpened(), Database::getClientList(), hBoxLayout, Database::openNew(), and vBoxLayout.
Referenced by MainStack().
375 {
376     QDialog dialog;
377     dialog.setCaption("Open Client");
378     
379     QVBoxLayout vBoxLayout(&dialog);
380     vBoxLayout.setMargin(5);
381     vBoxLayout.setSpacing(5);
382     
383     QLabel label("Choose a Client:", &dialog);
384     vBoxLayout.addWidget(&label);
385     
386     QListBox listBox(&dialog);
387     listBox.setFocus();
388     listBox.insertStringList(db->getClientList());
389     listBox.setSelected(0, true);
390     connect(&listBox, SIGNAL(selected(QListBoxItem*)), &dialog, SLOT(accept()));
391     
392     vBoxLayout.addWidget(&listBox);
393     vBoxLayout.addSpacing(10);
394     
395     QHBoxLayout hBoxLayout(&vBoxLayout);
396     hBoxLayout.setSpacing(5);
397     
398     QPushButton okButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/openNewButton.png")), "Open", &dialog);
399     okButton.setDefault(true);
400     connect(&okButton, SIGNAL(clicked()), &dialog, SLOT(accept()));
401     
402     QPushButton cancelButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")), "Cancel", &dialog);
403     connect(&cancelButton, SIGNAL(clicked()), &dialog, SLOT(reject()));
404     
405     hBoxLayout.addWidget(&okButton);
406     hBoxLayout.addWidget(&cancelButton);
407     
408     if(dialog.exec() && listBox.count())
409     {
410         QString file = listBox.selectedItem()->text();
411         file.remove(QRegExp(".+\\("));
412 
413         bool encrypted = false;
414 
415         if(file.right(5) == ".dbx)")
416         {
417             file.truncate(file.length() - 5);
418             encrypted = true;
419         }
420         if(file.right(4) == ".db)")
421             file.truncate(file.length() - 4);
422 
423         QString password(QString::null);
424 
425         if(encrypted)
426         {
427             QDialog dialog2;
428             dialog2.setCaption("Enter Password");
429     
430             QVBoxLayout vBoxLayout2(&dialog2);
431             vBoxLayout2.setMargin(5);
432             vBoxLayout2.setSpacing(5);
433     
434             QLabel label2("<nobr>This database is encrypted</nobr><br><nobr>Enter the password:</nobr>", &dialog2);
435             QLineEdit password2(&dialog2);
436             password2.setMaxLength(20);
437             password2.setEchoMode(QLineEdit::Password);
438             vBoxLayout2.addStretch();
439             vBoxLayout2.addWidget(&label2);
440             vBoxLayout2.addWidget(&password2);
441             vBoxLayout2.addSpacing(10);
442     
443             QHBoxLayout hBoxLayout2(&vBoxLayout2);
444             hBoxLayout2.setSpacing(5);
445     
446             QPushButton decryptButton2(QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/decryptButton.png") ),
447                                       "Open", &dialog2);
448             connect(&decryptButton2, SIGNAL(clicked()), &dialog2, SLOT(accept()));
449     
450             QPushButton cancelButton2(QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png") ),
451                                      "Cancel", &dialog2);
452             connect(&cancelButton2, SIGNAL(clicked()), &dialog2, SLOT(reject()));
453     
454             hBoxLayout2.addStretch();
455             hBoxLayout2.addWidget(&decryptButton2);
456             hBoxLayout2.addWidget(&cancelButton2);
457 
458             if(dialog2.exec())
459                 password = password2.text();
460         }
461 
462         if(db->openNew(file, password))
463         {
464             clientOpened();
465             emit dbOpened();
466         }
467     }
468 }
void MainStack::prepareQuit () [private, slot]
Definition at line 737 of file mainStack.cpp.
References active, closeClient(), and quit().
Referenced by MainStack().
738 {
739     if(active == 1)
740         closeClient();
741     emit quit();
742 }
void MainStack::quit () [signal]
Referenced by prepareQuit().
void MainStack::saveAndClearJournalTmp () [signal]
Referenced by closeClient().
void MainStack::switchToAccounts () [signal]
Referenced by clientOpened().
void MainStack::switchToJournal () [signal]
Referenced by clientOpened(), and closeClient().
void MainStack::switchToReports () [signal]
Referenced by clientOpened().
void MainStack::switchWidget () [private]
Definition at line 253 of file mainStack.cpp.
References active, main, and tasks.
Referenced by clientOpened(), and closeClient().
254 {
255     if(active == 0)
256     {
257         raiseWidget(1);
258         active = 1;
259         tasks.focusedButton->setFocus();
260     }
261     else
262     {
263         raiseWidget(0);
264         active = 0;
265         main.openDefaultButton->setFocus();
266     }
267 }
Member Data Documentation
QPushButton* MainStack::accountsButton [private]
Definition at line 85 of file mainStack.h.
int MainStack::active [private]
Definition at line 60 of file mainStack.h.
Referenced by clientOpened(), closeClient(), closed(), eventFilter(), MainStack(), prepareQuit(), and switchWidget().
QVGroupBox* MainStack::adminGroup [private]
Definition at line 88 of file mainStack.h.
QVGroupBox* MainStack::clientGroup [private]
Definition at line 84 of file mainStack.h.
QString MainStack::clientPath [private]
Definition at line 56 of file mainStack.h.
Referenced by changePath(), and MainStack().
QPushButton* MainStack::closeButton [private]
Definition at line 81 of file mainStack.h.
QPushButton* MainStack::copyDatabaseButton [private]
Definition at line 90 of file mainStack.h.
QPushButton* MainStack::createNewButton [private]
Definition at line 69 of file mainStack.h.
QPushButton* MainStack::cryptButton [private]
Definition at line 91 of file mainStack.h.
Database* MainStack::db [private]
Definition at line 53 of file mainStack.h.
Referenced by clientOpened(), closeClient(), copyClient(), createNewDialog(), decrypt(), editName(), encrypt(), import(), MainStack(), openDefault(), and openNewDialog().
QPushButton* MainStack::editNameButton [private]
Definition at line 89 of file mainStack.h.
QString MainStack::exportPath [private]
Definition at line 57 of file mainStack.h.
Referenced by copyClient(), and MainStack().
QPushButton* MainStack::focusedButton [private]
Definition at line 77 of file mainStack.h.
QHBoxLayout* MainStack::hBoxLabel [private]
Definition at line 80 of file mainStack.h.
QHBoxLayout* MainStack::hBoxLayout [private]
Definition at line 82 of file mainStack.h.
QHBoxLayout* MainStack::hBoxLayout [private]
Definition at line 64 of file mainStack.h.
Referenced by decrypt(), editName(), and openNewDialog().
QPushButton* MainStack::importButton [private]
Definition at line 72 of file mainStack.h.
QString MainStack::importPath [private]
Definition at line 58 of file mainStack.h.
Referenced by import(), and MainStack().
QPushButton* MainStack::journalButton [private]
Definition at line 86 of file mainStack.h.
struct { ... } MainStack::main [private]
Referenced by clientOpened(), editName(), MainStack(), and switchWidget().
QVGroupBox* MainStack::mainGroup [private]
Definition at line 66 of file mainStack.h.
QPushButton* MainStack::openDefaultButton [private]
Definition at line 67 of file mainStack.h.
QPushButton* MainStack::openNewButton [private]
Definition at line 68 of file mainStack.h.
QVGroupBox* MainStack::otherGroup [private]
Definition at line 70 of file mainStack.h.
QPushButton* MainStack::pathButton [private]
Definition at line 71 of file mainStack.h.
QPushButton* MainStack::quitButton [private]
Definition at line 73 of file mainStack.h.
QPushButton* MainStack::reportButton [private]
Definition at line 87 of file mainStack.h.
Settings* MainStack::settings [private]
Definition at line 54 of file mainStack.h.
Referenced by changePath(), and MainStack().
struct { ... } MainStack::tasks [private]
Referenced by clientOpened(), eventFilter(), and switchWidget().
QVBoxLayout* MainStack::vBoxLabel [private]
Definition at line 79 of file mainStack.h.
QVBoxLayout* MainStack::vBoxLayout [private]
Definition at line 83 of file mainStack.h.
QVBoxLayout* MainStack::vBoxLayout [private]
Definition at line 65 of file mainStack.h.
Referenced by createNewDialog(), decrypt(), editName(), encrypt(), and openNewDialog().
QWidget* MainStack::widget [private]
Definition at line 78 of file mainStack.h.
QWidget* MainStack::widget [private]
Definition at line 63 of file mainStack.h.
Referenced by clientOpened().
The documentation for this class was generated from the following files:
mainStack.h
mainStack.cpp