JournalTable Class Reference
#include <journalTable.h>
Signals
void goToMain ()
void goToAccounts ()
void goToReports ()
void goToHelp ()
Public Member Functions
JournalTable (QWidget *parent=0, const char *name=0)
~JournalTable ()
bool isInserting () const
int debitColWidth ()
int creditColWidth ()
void populate ()
void clearTable ()
Private Slots
void updateDb (int, int)
void editingChanged (int, int)
void updateAccounts ()
Private Member Functions
void insert ()
void remove (int row)
void keyPressEvent (QKeyEvent *event)
Private Attributes
Database * db
bool editing
int editingRow
int editingCol
bool inserting
QStringList accounts
Constructor & Destructor Documentation
JournalTable::JournalTable (QWidget * parent = 0, const char * name = 0)
Definition at line 18 of file journalTable.cpp.
References accounts, db, editing, editingChanged(), Database::getAccountsList(), inserting, Database::instance(), populate(), updateAccounts(), and updateDb().
19     : QTable(parent,name)  
20 {
21     db = Database::instance();
22     
23     connect(db, SIGNAL(accountsChanged()), this, SLOT(updateAccounts()));
24         
25     setLeftMargin(0);
26     setVScrollBarMode(QScrollView::AlwaysOn);
27     setSelectionMode(QTable::SingleRow);
28     setFocusStyle(QTable::SpreadSheet);
29     
30     insertColumns(0,6);
31     
32     QStringList labels;
33     labels << "Date" << "Account" << "Reference" << "Description" << "Debit" << "Credit";
34     setColumnLabels(labels);
35               
36     setColumnStretchable(3, true);
37     
38     accounts = db->getAccountsList();
39     
40     populate();
41     
42     inserting = false;
43     editing = false;
44     
45     connect(this, SIGNAL(currentChanged(int, int)), this, SLOT(editingChanged(int, int)));
46     connect(this, SIGNAL(valueChanged(int, int)), this, SLOT(updateDb(int, int)));    
47 }
JournalTable::~JournalTable ()
Definition at line 49 of file journalTable.cpp.
50 {}
Member Function Documentation
void JournalTable::clearTable ()
Definition at line 170 of file journalTable.cpp.
171 {
172     int rows = numRows();
173     for(int row = 0; row <= rows; row++)
174         removeRow(0);
175 }
int JournalTable::creditColWidth ()
Definition at line 255 of file journalTable.cpp.
Referenced by JournalSummary::JournalSummary().
256 {
257     return columnWidth(5);
258 }
int JournalTable::debitColWidth ()
Definition at line 250 of file journalTable.cpp.
Referenced by JournalSummary::JournalSummary().
251 {
252     return columnWidth(4);
253 }
void JournalTable::editingChanged (int, int) [private, slot]
Definition at line 177 of file journalTable.cpp.
References editingCol, and editingRow.
Referenced by JournalTable().
178 {
179     editingRow = newRow;
180     editingCol = newCol;
181 }
void JournalTable::goToAccounts () [signal]
Referenced by keyPressEvent().
void JournalTable::goToHelp () [signal]
Referenced by keyPressEvent().
void JournalTable::goToMain () [signal]
Referenced by keyPressEvent().
void JournalTable::goToReports () [signal]
Referenced by keyPressEvent().
void JournalTable::insert () [private]
Definition at line 84 of file journalTable.cpp.
References accounts, db, editing, editingCol, editingRow, inserting, and Database::nextJournalTmpKey().
Referenced by keyPressEvent().
85 {
86     inserting = true;
87 
88     int newRow = numRows();
89     insertRows(newRow);
90 
91     editing = true;
92     editingRow = newRow;
93     editingCol = 0;
94 
95     ensureCellVisible(newRow, 0);
96     setItem(newRow, 0, new DateEdit(this, ""));
97     setItem(newRow, 1, new AccountEditItem(this, accounts, "", db->nextJournalTmpKey()));
98     setItem(newRow, 2, new QTableItem(this, QTableItem::OnTyping));
99     setItem(newRow, 3, new JournalDescEdit(this, ""));
100     setItem(newRow, 4, new MoneyEditItem(this, ""));
101     setItem(newRow, 5, new MoneyEditItem(this, ""));
102     setCurrentCell(newRow,0);
103 
104     beginEdit(newRow, 0, false);
105 }
bool JournalTable::isInserting () const
Definition at line 107 of file journalTable.cpp.
References inserting.
Referenced by JournalDescEdit::createEditor().
108 {
109     return inserting;
110 }
void JournalTable::keyPressEvent (QKeyEvent * event) [private]
Definition at line 183 of file journalTable.cpp.
References editing, editingCol, editingRow, goToAccounts(), goToHelp(), goToMain(), goToReports(), insert(), inserting, and remove().
184 {
185     switch(event->key())
186     {
187         case Key_Insert:
188             insert();
189             break;
190         case Key_Delete:
191             remove(currentRow());
192             break;
193         case Key_Enter:
194         case Key_Return:
195         case Key_Tab:
196             if(editing)
197             {
198                 endEdit(editingRow, editingCol, true, true);
199                 if(editingCol == 5)
200                 {
201                     editingCol = 0;
202                     if(editingRow == (numRows() - 1))
203                     {
204                         inserting = false;
205                         editing = false;
206                         setCurrentCell(editingRow, 0);
207                         break;
208                     }
209                     editingRow++;
210                 }
211                 else
212                 {
213                     editingCol++;
214                 }
215             }
216             setCurrentCell(editingRow, editingCol);
217 
218             beginEdit(editingRow, editingCol, false);
219 
220             editing = true;
221             break;
222         case Key_Escape:
223             if(editing)
224             {
225                 endEdit(editingRow, editingCol, true, true);
226                 editing = false;
227             }
228             else
229                 emit goToMain();
230             break;
231         case Key_F1:
232             emit goToMain();
233             break;
234         case Key_F2:
235             emit goToAccounts();
236             break;
237         case Key_F3:
238             break;
239         case Key_F4:
240             emit goToReports();
241             break;
242         case Key_F5:
243             emit goToHelp();
244             break;
245         default:
246             QTable::keyPressEvent(event);
247     }
248 }
void JournalTable::populate ()
Definition at line 52 of file journalTable.cpp.
References accounts, db, editingCol, editingRow, and Database::getJournalTmpData().
Referenced by JournalTable().
53 {
54     for(int row = 0; row <= numRows(); row++)
55         removeRow(0);
56     
57     QPtrList<QStringList>* data = db->getJournalTmpData();
58     QPtrListIterator<QStringList> it(*data);
59     
60     QStringList *stringList;
61     while((stringList = it.current()) != 0)
62     {
63         ++it;
64         insertRows(0);
65         setItem(0, 0, new DateEdit(this, stringList->operator[](1)));
66         setItem(0, 1, new AccountEditItem(this, accounts, stringList->operator[](2), stringList->operator[](0)));
67         setItem(0, 2, new QTableItem(this, QTableItem::OnTyping, stringList->operator[](3)));
68         setItem(0, 3, new JournalDescEdit(this, stringList->operator[](4)));
69         setItem(0, 4, new MoneyEditItem(this, stringList->operator[](5)));
70         setItem(0, 5, new MoneyEditItem(this, stringList->operator[](6)));
71         delete stringList;
72     }
73 
74     delete data;
75 
76     if(numRows())
77     {
78         setCurrentCell(0,0);
79         editingRow = 0;
80         editingCol = 0;
81     }
82 }
void JournalTable::remove (int row) [private]
Definition at line 112 of file journalTable.cpp.
References db, and Database::deleteJournalTmp().
Referenced by keyPressEvent().
113 {
114     QString key = ((AccountEditItem*)(item(row, 1)))->getKey();
115     
116     QDialog dialog;
117     dialog.setCaption("Delete Record");
118 
119     QVBoxLayout vBoxLayout(&dialog);
120     vBoxLayout.setMargin(5);
121     vBoxLayout.setSpacing(5);
122 
123     QLabel label("<nobr>Are you sure you want to delete the selected record?</nobr>", &dialog);
124 
125     vBoxLayout.addWidget(&label);
126 
127     vBoxLayout.addSpacing(10);
128 
129     QHBoxLayout hBoxLayout(&vBoxLayout);
130     hBoxLayout.setSpacing(5);
131 
132     QPushButton buttonDelete(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/deleteButton.png")),
133                              "Delete", &dialog);
134     connect(&buttonDelete, SIGNAL(clicked()), &dialog, SLOT(accept()));
135 
136     QPushButton buttonDontDelete(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/okButton.png")),
137                                  "Don't Delete", &dialog);
138     connect(&buttonDontDelete, SIGNAL(clicked()), &dialog, SLOT(reject()));
139 
140     buttonDontDelete.setDefault(true);
141 
142     hBoxLayout.addStretch();
143     hBoxLayout.addWidget(&buttonDelete);
144     hBoxLayout.addWidget(&buttonDontDelete);
145 
146     if(dialog.exec())
147     {
148         db->deleteJournalTmp(key);
149         removeRow(row);
150     }
151     if(row > 0)
152         setCurrentCell(row - 1, 0);
153 }
void JournalTable::updateAccounts () [private, slot]
Definition at line 260 of file journalTable.cpp.
References accounts, db, and Database::getAccountsList().
Referenced by JournalTable().
261 {
262     accounts = db->getAccountsList();
263 }
void JournalTable::updateDb (int, int) [private, slot]
Definition at line 155 of file journalTable.cpp.
References db, Database::getAccountDesc(), inserting, and Database::updateJournalTmp().
Referenced by JournalTable().
156 {
157     QString key = ((AccountEditItem*)(item(row, 1)))->getKey();
158     QString date = text(row, 0);
159     QString account = text(row, 1);
160     QString reference = text(row, 2);
161     QString desc = text(row, 3);
162     QString debit = text(row, 4);
163     QString credit = text(row, 5);
164     db->updateJournalTmp(key, date, account, reference, desc, debit, credit);
165 
166     if(inserting && col == 1 && text(row, 3) == "")
167         setText(row, 3, db->getAccountDesc(account));
168 }
Member Data Documentation
QStringList JournalTable::accounts [private]
Definition at line 47 of file journalTable.h.
Referenced by insert(), JournalTable(), populate(), and updateAccounts().
Database* JournalTable::db [private]
Definition at line 39 of file journalTable.h.
Referenced by insert(), JournalTable(), populate(), remove(), updateAccounts(), and updateDb().
bool JournalTable::editing [private]
Definition at line 41 of file journalTable.h.
Referenced by insert(), JournalTable(), and keyPressEvent().
int JournalTable::editingCol [private]
Definition at line 43 of file journalTable.h.
Referenced by editingChanged(), insert(), keyPressEvent(), and populate().
int JournalTable::editingRow [private]
Definition at line 42 of file journalTable.h.
Referenced by editingChanged(), insert(), keyPressEvent(), and populate().
bool JournalTable::inserting [private]
Definition at line 45 of file journalTable.h.
Referenced by insert(), isInserting(), JournalTable(), keyPressEvent(), and updateDb().
The documentation for this class was generated from the following files:
journalTable.h
journalTable.cpp