PDFOptions Class Reference
#include <pdfOptions.h>
Public Member Functions
PDFOptions ()
QString exec ()
Private Slots
void paperSizeChanged (int)
void passwordNoClicked ()
void passwordYesClicked ()
Private Attributes
Settings * settings
xx xx xx xx xx xx xx xx xx
struct {
 QDialog * dialog
 QVBoxLayout * vBoxLayout
 QLabel * topLabel
 QLabel * defaultLabel
 QHBoxLayout * defaultHBoxLayout
 QVBoxLayout * defaultVBoxLayout
 QLabel * defaultPaperSizeLabel
 QLabel * defaultPasswordLabel
 QLabel * defaultPermissionsLabel
 QHBoxLayout * buttonHBoxLayout
 QPushButton * changeOptionsButton
 QPushButton * useDefaultsButton
} question
xx xx xx xx xx xx xx xx xx
struct {
 QDialog * dialog
 QVBoxLayout * vBoxLayout
 QLabel * paperSizeLabel
 QHBoxLayout * paperSizeHBoxLayout
 QVBoxLayout * paperSizeVBoxLayout
 QHBoxLayout * paperSizeComboHBoxLayout
 QComboBox * paperSizeComboBox
 QHBoxLayout * paperSizeCustomHBoxLayout
 QLineEdit * paperSizeCustomWidthLineEdit
 QLabel * paperSizeCustomBetweenLabel
 QLineEdit * paperSizeCustomHeightLineEdit
 QComboBox * paperSizeCustomUnitsComboBox
 QLabel * passwordLabel
 QHBoxLayout * passwordHBoxLayout
 QVBoxLayout * passwordVBoxLayout
 QRadioButton * passwordNoRadioButton
 QRadioButton * passwordYesRadioButton
 QHBoxLayout * passwordYesHBoxLayout
 QLabel * passwordYesLabel
 QLabel * permissionsLabel
 QHBoxLayout * permissionsHBoxLayout
 QGridLayout * permissionsGridLayout
 QCheckBox * permissionsNoPrint
 QCheckBox * permissionsNoModify
 QCheckBox * permissionsNoCopy
 QCheckBox * permissionsNoAnnotate
 QHBoxLayout * buttonHBoxLayout
 QPushButton * buttonCreate
 QPushButton * buttonCancel
} options
xx xx xx xx xx xx xx xx xx
struct {
 QDialog * dialog
 QVBoxLayout * vBoxLayout
 QLabel * label
 QLabel * label2
 QGridLayout * gridLayout
 QLabel * firstLabel
 QLineEdit * firstLineEdit
 QLabel * secondLabel
 QLineEdit * secondLineEdit
 QHBoxLayout * hBoxLayout
 QPushButton * createButton
 QPushButton * cancelButton
} password
Constructor & Destructor Documentation
PDFOptions::PDFOptions ()
Definition at line 15 of file pdfOptions.cpp.
References Settings::instance(), and settings.
15                        : QObject(0)
16 {
17     settings = Settings::instance();
18 }
Member Function Documentation
QString PDFOptions::exec ()
Definition at line 20 of file pdfOptions.cpp.
References Settings::getPDFPaperSizeHeight(), Settings::getPDFPaperSizeInt(), Settings::getPDFPaperSizeString(), Settings::getPDFPaperSizeUnits(), Settings::getPDFPaperSizeWidth(), Settings::getPDFPasswordBool(), Settings::getPDFPasswordString(), Settings::getPDFPermissionsNoAnnotate(), Settings::getPDFPermissionsNoCopy(), Settings::getPDFPermissionsNoModify(), Settings::getPDFPermissionsNoPrint(), Settings::getPDFPermissionsString(), options, paperSizeChanged(), password, passwordNoClicked(), passwordYesClicked(), question, Settings::setPDFPaperSize(), Settings::setPDFPaperSizeHeight(), Settings::setPDFPaperSizeUnits(), Settings::setPDFPaperSizeWidth(), Settings::setPDFPassword(), Settings::setPDFPermissionsNoAnnotate(), Settings::setPDFPermissionsNoCopy(), Settings::setPDFPermissionsNoModify(), Settings::setPDFPermissionsNoPrint(), and settings.
Referenced by ReportStack::exportPDF().
21 {
22     QString string = QString::null;
23 
24     int PDFPaperSize = settings->getPDFPaperSizeInt();
25     QString PDFPaperSizeWidth = settings->getPDFPaperSizeWidth();
26     QString PDFPaperSizeHeight = settings->getPDFPaperSizeHeight();
27     int PDFPaperSizeUnits = settings->getPDFPaperSizeUnits();
28 
29     bool PDFPassword = settings->getPDFPasswordBool();
30     QString PDFPasswordString = QString::null;
31 
32     bool PDFPermissionsNoPrint = settings->getPDFPermissionsNoPrint();
33     bool PDFPermissionsNoModify = settings->getPDFPermissionsNoModify();
34     bool PDFPermissionsNoCopy = settings->getPDFPermissionsNoCopy();
35     bool PDFPermissionsNoAnnotate = settings->getPDFPermissionsNoAnnotate();
36 
37     question.dialog = new QDialog(0);
38     question.dialog->setCaption("PDF Options");
39 
40     question.vBoxLayout = new QVBoxLayout(question.dialog);
41     question.vBoxLayout->setMargin(5);
42     question.vBoxLayout->setSpacing(5);
43 
44     question.topLabel = new QLabel("<nobr>Would you like to change your default PDF Options?</nobr>", question.dialog);
45     question.vBoxLayout->addWidget(question.topLabel);
46 
47     question.vBoxLayout->addSpacing(10);
48 
49     question.defaultLabel = new QLabel("Defaults:", question.dialog);
50     question.vBoxLayout->addWidget(question.defaultLabel);
51 
52     question.defaultHBoxLayout = new QHBoxLayout(question.vBoxLayout);
53     question.defaultHBoxLayout->addSpacing(5);
54 
55     question.defaultVBoxLayout = new QVBoxLayout(question.defaultHBoxLayout);
56     question.defaultVBoxLayout->setSpacing(5);
57 
58     question.defaultPaperSizeLabel = new QLabel(question.dialog);
59 
60     if(PDFPaperSize == 3)
61     {
62         QString paperSize("Paper Size: Custom (" + settings->getPDFPaperSizeWidth() + " x "
63                           + settings->getPDFPaperSizeHeight());
64         if(PDFPaperSizeUnits == 0)
65             paperSize += "in)";
66         if(PDFPaperSizeUnits == 1)
67             paperSize += "cm)";
68         else
69             paperSize += "mm)";
70 
71         question.defaultPaperSizeLabel->setText(paperSize);
72     }
73     else
74         question.defaultPaperSizeLabel->setText("Paper Size: " + settings->getPDFPaperSizeString());
75 
76     question.defaultPasswordLabel = new QLabel("Password Protection: " + settings->getPDFPasswordString(), question.dialog);
77     question.defaultPermissionsLabel = new QLabel("Permissions: " + settings->getPDFPermissionsString(), question.dialog);
78 
79     question.defaultVBoxLayout->addWidget(question.defaultPaperSizeLabel);
80     question.defaultVBoxLayout->addWidget(question.defaultPasswordLabel);
81     question.defaultVBoxLayout->addWidget(question.defaultPermissionsLabel);
82 
83     question.vBoxLayout->addSpacing(10);
84 
85     question.buttonHBoxLayout = new QHBoxLayout(question.vBoxLayout);
86     question.buttonHBoxLayout->setSpacing(5);
87 
88     question.changeOptionsButton = new QPushButton(
89             QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/changeOptionsButton.png")),
90             "Change Options", question.dialog);
91     question.changeOptionsButton->setDefault(false);
92     connect(question.changeOptionsButton, SIGNAL(clicked()), question.dialog, SLOT(accept()));
93 
94     question.useDefaultsButton = new QPushButton(
95             QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/okButton.png")),
96             "Use Defaults", question.dialog);
97     question.useDefaultsButton->setDefault(true);
98     connect(question.useDefaultsButton, SIGNAL(clicked()), question.dialog, SLOT(reject()));
99 
100     question.buttonHBoxLayout->addStretch();
101     question.buttonHBoxLayout->addWidget(question.changeOptionsButton);
102     question.buttonHBoxLayout->addWidget(question.useDefaultsButton);
103 
104     if(question.dialog->exec())
105     {
106         options.dialog = new QDialog(0);
107         options.dialog->setCaption("PDF Options");
108 
109         options.vBoxLayout = new QVBoxLayout(options.dialog);
110         options.vBoxLayout->setMargin(5);
111         options.vBoxLayout->setSpacing(5);
112 
113         options.paperSizeLabel = new QLabel("Paper Size:", options.dialog);
114         options.vBoxLayout->addWidget(options.paperSizeLabel);
115 
116         options.paperSizeHBoxLayout = new QHBoxLayout(options.vBoxLayout);
117         options.paperSizeHBoxLayout->addSpacing(5);
118 
119         options.paperSizeVBoxLayout = new QVBoxLayout(options.paperSizeHBoxLayout);
120         options.paperSizeVBoxLayout->setSpacing(5);
121 
122         options.paperSizeComboHBoxLayout = new QHBoxLayout(options.paperSizeVBoxLayout);
123 
124         options.paperSizeComboBox = new QComboBox(options.dialog);
125         options.paperSizeComboBox->insertStringList(
126                 QStringList("Letter (8.5 x 11in)") << "A4 (8.27 x 11.69in)"
127                 << "Universal (8.27 x 11in)" << "Custom");
128         connect(options.paperSizeComboBox, SIGNAL(activated(int)), this, SLOT(paperSizeChanged(int)));
129         options.paperSizeComboBox->setCurrentItem(PDFPaperSize);
130 
131         options.paperSizeComboHBoxLayout->addWidget(options.paperSizeComboBox);
132         options.paperSizeComboHBoxLayout->addStretch();
133 
134         options.paperSizeCustomHBoxLayout = new QHBoxLayout(options.paperSizeVBoxLayout);
135         options.paperSizeCustomHBoxLayout->setSpacing(5);
136 
137         options.paperSizeCustomWidthLineEdit = new QLineEdit(options.dialog);
138         options.paperSizeCustomWidthLineEdit->setMaxLength(7);
139         options.paperSizeCustomWidthLineEdit->setFixedWidth(
140                 (options.paperSizeCustomWidthLineEdit->minimumSizeHint()).width() * 2);
141         if(PDFPaperSize == 3)
142             options.paperSizeCustomWidthLineEdit->setText(PDFPaperSizeWidth);
143         else
144             options.paperSizeCustomWidthLineEdit->setEnabled(false);
145         options.paperSizeCustomHBoxLayout->addWidget(options.paperSizeCustomWidthLineEdit);
146 
147         options.paperSizeCustomBetweenLabel = new QLabel("x", options.dialog);
148         if(PDFPaperSize != 3)
149             options.paperSizeCustomBetweenLabel->setEnabled(false);
150         options.paperSizeCustomHBoxLayout->addWidget(options.paperSizeCustomBetweenLabel);
151 
152         options.paperSizeCustomHeightLineEdit = new QLineEdit(options.dialog);
153         options.paperSizeCustomHeightLineEdit->setMaxLength(7);
154         options.paperSizeCustomHeightLineEdit->setFixedWidth(
155                 (options.paperSizeCustomHeightLineEdit->minimumSizeHint()).width() * 2);
156         if(PDFPaperSize == 3)
157             options.paperSizeCustomHeightLineEdit->setText(PDFPaperSizeHeight);
158         else
159             options.paperSizeCustomHeightLineEdit->setEnabled(false);
160         options.paperSizeCustomHBoxLayout->addWidget(options.paperSizeCustomHeightLineEdit);
161 
162         options.paperSizeCustomUnitsComboBox = new QComboBox(options.dialog);
163         options.paperSizeCustomUnitsComboBox->insertStringList(
164                 QStringList("in") << "cm" << "mm");
165         if(PDFPaperSize == 3)
166             options.paperSizeCustomUnitsComboBox->setCurrentItem(PDFPaperSizeUnits);
167         else
168             options.paperSizeCustomUnitsComboBox->setEnabled(false);
169         options.paperSizeCustomHBoxLayout->addWidget(options.paperSizeCustomUnitsComboBox);
170 
171         options.paperSizeCustomHBoxLayout->addStretch();
172 
173         options.vBoxLayout->addSpacing(10);
174 
175 
176         options.passwordLabel = new QLabel("Password Protection:", options.dialog);
177         options.vBoxLayout->addWidget(options.passwordLabel);
178 
179         options.passwordHBoxLayout = new QHBoxLayout(options.vBoxLayout);
180         options.passwordHBoxLayout->addSpacing(5);
181 
182         options.passwordVBoxLayout = new QVBoxLayout(options.passwordHBoxLayout);
183         options.passwordVBoxLayout->setSpacing(5);
184 
185         options.passwordNoRadioButton = new QRadioButton("No Password", options.dialog);
186         connect(options.passwordNoRadioButton, SIGNAL(clicked()), this, SLOT(passwordNoClicked()));
187         options.passwordVBoxLayout->addWidget(options.passwordNoRadioButton);
188 
189         options.passwordYesRadioButton = new QRadioButton("Use Password", options.dialog);
190         connect(options.passwordYesRadioButton, SIGNAL(clicked()), this, SLOT(passwordYesClicked()));
191         options.passwordVBoxLayout->addWidget(options.passwordYesRadioButton);
192 
193         if(PDFPassword)
194             options.passwordYesRadioButton->setChecked(true);
195         else
196             options.passwordNoRadioButton->setChecked(true);
197 
198         options.passwordYesHBoxLayout = new QHBoxLayout(options.passwordVBoxLayout);
199         options.passwordYesHBoxLayout->addSpacing(5);
200 
201         options.passwordYesLabel = new QLabel("<nobr>(You will be asked to enter this password</nobr>"
202                                               "<br>after you press \"Create PDF\")",
203                                               options.dialog);
204         options.passwordYesHBoxLayout->addWidget(options.passwordYesLabel);
205 
206         options.vBoxLayout->addSpacing(10);
207 
208 
209         options.permissionsLabel = new QLabel("Permissions:", options.dialog);
210         options.vBoxLayout->addWidget(options.permissionsLabel);
211 
212         options.permissionsHBoxLayout = new QHBoxLayout(options.vBoxLayout);
213         options.permissionsHBoxLayout->addSpacing(5);
214 
215         options.permissionsGridLayout = new QGridLayout(options.permissionsHBoxLayout, 2, 2, 5);
216 
217         options.permissionsNoPrint = new QCheckBox("No-Print", options.dialog);
218         if(PDFPermissionsNoPrint)
219             options.permissionsNoPrint->setChecked(true);
220 
221         options.permissionsNoModify = new QCheckBox("No-Modify", options.dialog);
222         if(PDFPermissionsNoModify)
223             options.permissionsNoModify->setChecked(true);
224 
225         options.permissionsNoCopy = new QCheckBox("No-Copy", options.dialog);
226         if(PDFPermissionsNoCopy)
227             options.permissionsNoCopy->setChecked(true);
228 
229         options.permissionsNoAnnotate = new QCheckBox("No-Annotate", options.dialog);
230         if(PDFPermissionsNoAnnotate)
231             options.permissionsNoAnnotate->setChecked(true);
232 
233         options.permissionsGridLayout->addWidget(options.permissionsNoPrint, 0, 0);
234         options.permissionsGridLayout->addWidget(options.permissionsNoModify, 0, 1);
235         options.permissionsGridLayout->addWidget(options.permissionsNoCopy, 1, 0);
236         options.permissionsGridLayout->addWidget(options.permissionsNoAnnotate, 1, 1);
237 
238         options.vBoxLayout->addSpacing(10);
239 
240 
241         options.buttonHBoxLayout = new QHBoxLayout(options.vBoxLayout);
242         options.buttonHBoxLayout->setSpacing(5);
243 
244         options.buttonCreate = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/exportpdf.png")),
245                                                "Create PDF", options.dialog);
246         connect(options.buttonCreate, SIGNAL(clicked()), options.dialog, SLOT(accept()));
247 
248         options.buttonCancel = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")),
249                                                "Cancel", options.dialog);
250         connect(options.buttonCancel, SIGNAL(clicked()), options.dialog, SLOT(reject()));
251 
252         options.buttonHBoxLayout->addStretch();
253         options.buttonHBoxLayout->addWidget(options.buttonCreate);
254         options.buttonHBoxLayout->addWidget(options.buttonCancel);
255 
256         if(options.dialog->exec())
257         {
258             PDFPaperSize = options.paperSizeComboBox->currentItem();
259             if(PDFPaperSize == 3)
260             {
261                 PDFPaperSizeWidth = options.paperSizeCustomWidthLineEdit->text();
262                 PDFPaperSizeHeight = options.paperSizeCustomHeightLineEdit->text();
263                 PDFPaperSizeUnits = options.paperSizeCustomUnitsComboBox->currentItem();
264             }
265 
266             PDFPassword = options.passwordYesRadioButton->isChecked();
267 
268             PDFPermissionsNoPrint = options.permissionsNoPrint->isChecked();
269             PDFPermissionsNoModify = options.permissionsNoModify->isChecked();
270             PDFPermissionsNoCopy = options.permissionsNoCopy->isChecked();
271             PDFPermissionsNoAnnotate = options.permissionsNoAnnotate->isChecked();
272 
273             delete options.dialog;
274             delete question.dialog;
275         }
276         else
277         {
278             delete options.dialog;
279             delete question.dialog;
280             return string;
281         }
282     }
283 
284     if(PDFPassword)
285     {
286         password.dialog = new QDialog(0);
287 
288         password.vBoxLayout = new QVBoxLayout(password.dialog);
289         password.vBoxLayout->setMargin(5);
290         password.vBoxLayout->setSpacing(5);
291 
292         password.label = new QLabel("<nobr>Enter a password to protect the PDF document.</nobr>", password.dialog);
293         password.label2 = new QLabel("Note: If you wish not to use a password,<br>leave both fields blank.", password.dialog);
294 
295         password.vBoxLayout->addWidget(password.label);
296         password.vBoxLayout->addSpacing(5);
297         password.vBoxLayout->addWidget(password.label2);
298 
299         password.vBoxLayout->addSpacing(10);
300 
301         password.gridLayout = new QGridLayout(password.vBoxLayout, 2, 2, 5);  // rows, cols, spacing
302 
303         password.firstLabel = new QLabel("Password:", password.dialog);
304         password.firstLineEdit = new QLineEdit(password.dialog);
305         password.firstLineEdit->setMaxLength(20);
306         password.firstLineEdit->setEchoMode(QLineEdit::Password);
307 
308         password.secondLabel = new QLabel("Repeat:", password.dialog);
309         password.secondLineEdit = new QLineEdit(password.dialog);
310         password.secondLineEdit->setMaxLength(20);
311         password.secondLineEdit->setEchoMode(QLineEdit::Password);
312 
313         password.gridLayout->addWidget(password.firstLabel, 0, 0);
314         password.gridLayout->addWidget(password.firstLineEdit, 0, 1);
315         password.gridLayout->addWidget(password.secondLabel, 1, 0, Qt::AlignRight | Qt::AlignVCenter);
316         password.gridLayout->addWidget(password.secondLineEdit, 1, 1);
317 
318         password.vBoxLayout->addSpacing(10);
319 
320         password.hBoxLayout = new QHBoxLayout(password.vBoxLayout);
321         password.hBoxLayout->setSpacing(5);
322 
323         password.createButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/exportpdf.png")),
324                                                 "Create PDF", password.dialog);
325         connect(password.createButton, SIGNAL(clicked()), password.dialog, SLOT(accept()));
326 
327         password.cancelButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")),
328                                                 "Cancel", password.dialog);
329         connect(password.cancelButton, SIGNAL(clicked()), password.dialog, SLOT(reject()));
330 
331         password.hBoxLayout->addStretch();
332         password.hBoxLayout->addWidget(password.createButton);
333         password.hBoxLayout->addWidget(password.cancelButton);
334 
335         bool accepted = false;
336         while(password.dialog->exec())
337         {
338             if(password.firstLineEdit->text() == password.secondLineEdit->text())
339             {
340                 PDFPasswordString = password.firstLineEdit->text();
341                 accepted = true;
342                 break;
343             }
344             password.label->setText("<nobr>The passwords did not match.  Try again.</nobr>");
345         }
346         delete password.dialog;
347 
348         if(!accepted)
349             return string;
350     }
351 
352     if(PDFPaperSize == 0)
353         string += "--size letter ";
354     if(PDFPaperSize == 1)
355         string += "--size a4 ";
356     if(PDFPaperSize == 2)
357         string += "8.27x11.69in ";
358     if(PDFPaperSize == 3)
359     {
360         string += "--size " + PDFPaperSizeWidth + "x" + PDFPaperSizeHeight;
361         if(PDFPaperSizeUnits == 0)
362             string += "in ";
363         if(PDFPaperSizeUnits == 1)
364             string += "cm ";
365         if(PDFPaperSizeUnits == 2)
366             string += "mm ";
367     }
368 
369     if(PDFPassword || PDFPermissionsNoPrint || PDFPermissionsNoModify || PDFPermissionsNoCopy || PDFPermissionsNoAnnotate)
370         string += "--encryption ";
371 
372     if(PDFPassword)
373         string += "--user-password \"" + PDFPasswordString + "\" ";
374 
375     if(PDFPermissionsNoPrint || PDFPermissionsNoModify || PDFPermissionsNoCopy || PDFPermissionsNoAnnotate)
376     {
377         if(PDFPermissionsNoPrint)
378             string += "--permissions no-print ";
379         if(PDFPermissionsNoModify)
380             string += "--permissions no-modify ";
381         if(PDFPermissionsNoCopy)
382             string += "--permissions no-copy ";
383         if(PDFPermissionsNoAnnotate)
384             string += "--permissions no-annotate ";
385     }
386 
387     settings->setPDFPaperSize(PDFPaperSize);
388     settings->setPDFPaperSizeWidth(PDFPaperSizeWidth);
389     settings->setPDFPaperSizeHeight(PDFPaperSizeHeight);
390     settings->setPDFPaperSizeUnits(PDFPaperSizeUnits);
391     settings->setPDFPassword(PDFPassword);
392     settings->setPDFPermissionsNoPrint(PDFPermissionsNoPrint);
393     settings->setPDFPermissionsNoModify(PDFPermissionsNoModify);
394     settings->setPDFPermissionsNoCopy(PDFPermissionsNoCopy);
395     settings->setPDFPermissionsNoAnnotate(PDFPermissionsNoAnnotate);
396 
397     return string;
398 }
void PDFOptions::paperSizeChanged (int) [private, slot]
Definition at line 400 of file pdfOptions.cpp.
References options.
Referenced by exec().
401 {
402     if(index != 3)
403     {
404         options.paperSizeCustomWidthLineEdit->setEnabled(false);
405         options.paperSizeCustomBetweenLabel->setEnabled(false);
406         options.paperSizeCustomHeightLineEdit->setEnabled(false);
407         options.paperSizeCustomUnitsComboBox->setEnabled(false);
408     }
409     else
410     {
411         options.paperSizeCustomWidthLineEdit->setEnabled(true);
412         options.paperSizeCustomBetweenLabel->setEnabled(true);
413         options.paperSizeCustomHeightLineEdit->setEnabled(true);
414         options.paperSizeCustomUnitsComboBox->setEnabled(true);
415     }
416 }
void PDFOptions::passwordNoClicked () [private, slot]
Definition at line 418 of file pdfOptions.cpp.
References options.
Referenced by exec().
419 {
420     options.passwordYesRadioButton->setChecked(false);
421     options.passwordNoRadioButton->setChecked(true);
422 }
void PDFOptions::passwordYesClicked () [private, slot]
Definition at line 424 of file pdfOptions.cpp.
References options.
Referenced by exec().
425 {
426     options.passwordNoRadioButton->setChecked(false);
427     options.passwordYesRadioButton->setChecked(true);
428 }
Member Data Documentation
QPushButton* PDFOptions::buttonCancel [private]
Definition at line 83 of file pdfOptions.h.
QPushButton* PDFOptions::buttonCreate [private]
Definition at line 82 of file pdfOptions.h.
QHBoxLayout* PDFOptions::buttonHBoxLayout [private]
Definition at line 81 of file pdfOptions.h.
QHBoxLayout* PDFOptions::buttonHBoxLayout [private]
Definition at line 45 of file pdfOptions.h.
QPushButton* PDFOptions::cancelButton [private]
Definition at line 98 of file pdfOptions.h.
QPushButton* PDFOptions::changeOptionsButton [private]
Definition at line 46 of file pdfOptions.h.
QPushButton* PDFOptions::createButton [private]
Definition at line 97 of file pdfOptions.h.
QHBoxLayout* PDFOptions::defaultHBoxLayout [private]
Definition at line 40 of file pdfOptions.h.
QLabel* PDFOptions::defaultLabel [private]
Definition at line 39 of file pdfOptions.h.
QLabel* PDFOptions::defaultPaperSizeLabel [private]
Definition at line 42 of file pdfOptions.h.
QLabel* PDFOptions::defaultPasswordLabel [private]
Definition at line 43 of file pdfOptions.h.
QLabel* PDFOptions::defaultPermissionsLabel [private]
Definition at line 44 of file pdfOptions.h.
QVBoxLayout* PDFOptions::defaultVBoxLayout [private]
Definition at line 41 of file pdfOptions.h.
QDialog* PDFOptions::dialog [private]
Definition at line 87 of file pdfOptions.h.
QDialog* PDFOptions::dialog [private]
Definition at line 51 of file pdfOptions.h.
QDialog* PDFOptions::dialog [private]
Definition at line 36 of file pdfOptions.h.
QLabel* PDFOptions::firstLabel [private]
Definition at line 92 of file pdfOptions.h.
QLineEdit* PDFOptions::firstLineEdit [private]
Definition at line 93 of file pdfOptions.h.
QGridLayout* PDFOptions::gridLayout [private]
Definition at line 91 of file pdfOptions.h.
QHBoxLayout* PDFOptions::hBoxLayout [private]
Definition at line 96 of file pdfOptions.h.
QLabel* PDFOptions::label [private]
Definition at line 89 of file pdfOptions.h.
QLabel* PDFOptions::label2 [private]
Definition at line 90 of file pdfOptions.h.
struct { ... } PDFOptions::options [private]
Referenced by exec(), paperSizeChanged(), passwordNoClicked(), and passwordYesClicked().
QComboBox* PDFOptions::paperSizeComboBox [private]
Definition at line 58 of file pdfOptions.h.
QHBoxLayout* PDFOptions::paperSizeComboHBoxLayout [private]
Definition at line 57 of file pdfOptions.h.
QLabel* PDFOptions::paperSizeCustomBetweenLabel [private]
Definition at line 61 of file pdfOptions.h.
QHBoxLayout* PDFOptions::paperSizeCustomHBoxLayout [private]
Definition at line 59 of file pdfOptions.h.
QLineEdit* PDFOptions::paperSizeCustomHeightLineEdit [private]
Definition at line 62 of file pdfOptions.h.
QComboBox* PDFOptions::paperSizeCustomUnitsComboBox [private]
Definition at line 63 of file pdfOptions.h.
QLineEdit* PDFOptions::paperSizeCustomWidthLineEdit [private]
Definition at line 60 of file pdfOptions.h.
QHBoxLayout* PDFOptions::paperSizeHBoxLayout [private]
Definition at line 55 of file pdfOptions.h.
QLabel* PDFOptions::paperSizeLabel [private]
Definition at line 54 of file pdfOptions.h.
QVBoxLayout* PDFOptions::paperSizeVBoxLayout [private]
Definition at line 56 of file pdfOptions.h.
struct { ... } PDFOptions::password [private]
Referenced by exec().
QHBoxLayout* PDFOptions::passwordHBoxLayout [private]
Definition at line 66 of file pdfOptions.h.
QLabel* PDFOptions::passwordLabel [private]
Definition at line 65 of file pdfOptions.h.
QRadioButton* PDFOptions::passwordNoRadioButton [private]
Definition at line 68 of file pdfOptions.h.
QVBoxLayout* PDFOptions::passwordVBoxLayout [private]
Definition at line 67 of file pdfOptions.h.
QHBoxLayout* PDFOptions::passwordYesHBoxLayout [private]
Definition at line 70 of file pdfOptions.h.
QLabel* PDFOptions::passwordYesLabel [private]
Definition at line 71 of file pdfOptions.h.
QRadioButton* PDFOptions::passwordYesRadioButton [private]
Definition at line 69 of file pdfOptions.h.
QGridLayout* PDFOptions::permissionsGridLayout [private]
Definition at line 75 of file pdfOptions.h.
QHBoxLayout* PDFOptions::permissionsHBoxLayout [private]
Definition at line 74 of file pdfOptions.h.
QLabel* PDFOptions::permissionsLabel [private]
Definition at line 73 of file pdfOptions.h.
QCheckBox* PDFOptions::permissionsNoAnnotate [private]
Definition at line 79 of file pdfOptions.h.
QCheckBox* PDFOptions::permissionsNoCopy [private]
Definition at line 78 of file pdfOptions.h.
QCheckBox* PDFOptions::permissionsNoModify [private]
Definition at line 77 of file pdfOptions.h.
QCheckBox* PDFOptions::permissionsNoPrint [private]
Definition at line 76 of file pdfOptions.h.
struct { ... } PDFOptions::question [private]
Referenced by exec().
QLabel* PDFOptions::secondLabel [private]
Definition at line 94 of file pdfOptions.h.
QLineEdit* PDFOptions::secondLineEdit [private]
Definition at line 95 of file pdfOptions.h.
Settings* PDFOptions::settings [private]
Definition at line 33 of file pdfOptions.h.
Referenced by exec(), and PDFOptions().
QLabel* PDFOptions::topLabel [private]
Definition at line 38 of file pdfOptions.h.
QPushButton* PDFOptions::useDefaultsButton [private]
Definition at line 47 of file pdfOptions.h.
QVBoxLayout* PDFOptions::vBoxLayout [private]
Definition at line 88 of file pdfOptions.h.
QVBoxLayout* PDFOptions::vBoxLayout [private]
Definition at line 52 of file pdfOptions.h.
QVBoxLayout* PDFOptions::vBoxLayout [private]
Definition at line 37 of file pdfOptions.h.
The documentation for this class was generated from the following files:
pdfOptions.h
pdfOptions.cpp