CloseDialog Class Reference
#include <closeDialog.h>
Public Member Functions
CloseDialog ()
Private Slots
void saveAndClear ()
void dontSave ()
void retToEntry ()
Private Attributes
QVBoxLayout * vBoxLayout
QLabel * label
QHBoxLayout * hBoxLayout
QPushButton * saveButton
QPushButton * dontSaveButton
QPushButton * returnButton
Constructor & Destructor Documentation
CloseDialog::CloseDialog ()
Definition at line 9 of file closeDialog.cpp.
References dontSave(), dontSaveButton, hBoxLayout, label, retToEntry(), returnButton, saveAndClear(), saveButton, and vBoxLayout.
9                          : QDialog(0)
10 {
11     setCaption("Close Client");
12 
13     vBoxLayout = new QVBoxLayout(this);
14     vBoxLayout->setMargin(5);
15     vBoxLayout->setSpacing(5);
16 
17     label = new QLabel("<nobr>There are entries in the journal which have not been saved and cleared.</nobr><br>"
18                        "<nobr>Would you like to save and clear these entries now?</nobr><br><br>"
19                        "Note: if you do not save and clear these entries, "
20                        "they will <u>not</u> be lost.  You will find them "
21                        "in the same place when you open this client again.", this);
22 
23     vBoxLayout->addWidget(label);
24     vBoxLayout->addSpacing(10);
25 
26     hBoxLayout = new QHBoxLayout(vBoxLayout);
27     hBoxLayout->setSpacing(5);
28 
29     saveButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/saveAndClear.png")),
30                                  "Save and Clear Entries", this);
31     connect(saveButton, SIGNAL(clicked()), this, SLOT(saveAndClear()));
32 
33     dontSaveButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")),
34                                      "Don't Save and Clear", this);
35     connect(dontSaveButton, SIGNAL(clicked()), this, SLOT(dontSave()));
36 
37     returnButton = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/return.png")),
38                                    "Return to Journal Entry", this);
39     connect(returnButton, SIGNAL(clicked()), this, SLOT(retToEntry()));
40 
41     hBoxLayout->addStretch();
42     hBoxLayout->addWidget(saveButton);
43     hBoxLayout->addWidget(dontSaveButton);
44     hBoxLayout->addWidget(returnButton);
45 }
Member Function Documentation
void CloseDialog::dontSave () [private, slot]
Definition at line 52 of file closeDialog.cpp.
Referenced by CloseDialog().
53 {
54     done(1);
55 }
void CloseDialog::retToEntry () [private, slot]
Definition at line 57 of file closeDialog.cpp.
Referenced by CloseDialog().
58 {
59     done(2);
60 }
void CloseDialog::saveAndClear () [private, slot]
Definition at line 47 of file closeDialog.cpp.
Referenced by CloseDialog().
48 {
49     done(0);
50 }
Member Data Documentation
QPushButton* CloseDialog::dontSaveButton [private]
Definition at line 27 of file closeDialog.h.
Referenced by CloseDialog().
QHBoxLayout* CloseDialog::hBoxLayout [private]
Definition at line 25 of file closeDialog.h.
Referenced by CloseDialog().
QLabel* CloseDialog::label [private]
Definition at line 24 of file closeDialog.h.
Referenced by CloseDialog().
QPushButton* CloseDialog::returnButton [private]
Definition at line 28 of file closeDialog.h.
Referenced by CloseDialog().
QPushButton* CloseDialog::saveButton [private]
Definition at line 26 of file closeDialog.h.
Referenced by CloseDialog().
QVBoxLayout* CloseDialog::vBoxLayout [private]
Definition at line 23 of file closeDialog.h.
Referenced by CloseDialog().
The documentation for this class was generated from the following files:
closeDialog.h
closeDialog.cpp