HelpStack Class Reference
#include <helpStack.h>
Signals
void goToMain ()
Public Member Functions
HelpStack (QWidget *parent=0, const char *name=0)
~HelpStack ()
Private Slots
void helpContents ()
Private Member Functions
bool eventFilter (QObject *target, QEvent *event)
Private Attributes
xx xx xx xx xx xx xx xx xx
struct {
 QVBoxLayout * vBoxLayout
 QBoxLayout * labelLayout
 GoBackLabel * topLabel
 QPushButton * helpContentsButton
 QTextBrowser * content
 QLabel * bottomLabel
} main
Constructor & Destructor Documentation
HelpStack::HelpStack (QWidget * parent = 0, const char * name = 0)
Definition at line 14 of file helpStack.cpp.
References goToMain(), helpContents(), and main.
15     : QWidget(parent,name)
16 {
17     main.vBoxLayout = new QVBoxLayout(this);
18     main.vBoxLayout->setMargin(5);
19     main.vBoxLayout->setSpacing(5);
20     
21     main.labelLayout = new QBoxLayout(main.vBoxLayout, QBoxLayout::LeftToRight);
22     
23     main.topLabel = new GoBackLabel(this);
24     connect(main.topLabel, SIGNAL(goBack()), this, SIGNAL(goToMain()));
25     
26     main.helpContentsButton = new QPushButton(
27             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/help.png") ),
28             "Help Contents (F8)", this);
29     main.helpContentsButton->setFocusPolicy(QWidget::NoFocus);
30     connect(main.helpContentsButton, SIGNAL(clicked()), this, SLOT(helpContents()));
31     
32     main.labelLayout->addWidget(main.topLabel, 0, Qt::AlignLeft | Qt::AlignTop);
33     main.labelLayout->addStretch();
34     main.labelLayout->addWidget(main.helpContentsButton);
35     
36     main.content = new QTextBrowser(this);
37     main.content->setVScrollBarMode(QScrollView::AlwaysOn);
38     main.content->mimeSourceFactory()->addFilePath(HELP_PATH);
39     main.content->setSource("contents.html");
40     main.content->installEventFilter(this);
41     
42     main.vBoxLayout->addWidget(main.content);
43     
44     main.bottomLabel = new QLabel(
45             "<nobr><b>Keyboard Control:</b></nobr><br>"
46             "<nobr> &nbsp; &nbsp; <b>Up</b> / <b>Down</b>: Scroll the page</nobr><br>"
47             "<nobr> &nbsp; &nbsp; <b>Tab</b> / <b>Shift-Tab</b>: Select a link</nobr>", this);
48     
49     main.vBoxLayout->addWidget(main.bottomLabel);
50    
51 }
HelpStack::~HelpStack ()
Definition at line 53 of file helpStack.cpp.
54 {}
Member Function Documentation
bool HelpStack::eventFilter (QObject * target, QEvent * event) [private]
Definition at line 61 of file helpStack.cpp.
References goToMain(), and helpContents().
62 {
63     if(event->type() == QEvent::KeyPress)
64     {
65         QKeyEvent *keyEvent = (QKeyEvent *)event;
66         if(keyEvent->key() == Key_Escape)
67         {
68             emit goToMain();
69             return true;
70         }
71         if(keyEvent->key() == Key_F8)
72         {
73             helpContents();
74             return true;
75         }
76     }
77     return QWidget::eventFilter(target,event);
78 }
void HelpStack::goToMain () [signal]
Referenced by eventFilter(), and HelpStack().
void HelpStack::helpContents () [private, slot]
Definition at line 56 of file helpStack.cpp.
References main.
Referenced by eventFilter(), and HelpStack().
57 {
58     main.content->home();
59 }
Member Data Documentation
QLabel* HelpStack::bottomLabel [private]
Definition at line 37 of file helpStack.h.
QTextBrowser* HelpStack::content [private]
Definition at line 36 of file helpStack.h.
QPushButton* HelpStack::helpContentsButton [private]
Definition at line 35 of file helpStack.h.
QBoxLayout* HelpStack::labelLayout [private]
Definition at line 33 of file helpStack.h.
struct { ... } HelpStack::main [private]
Referenced by helpContents(), and HelpStack().
GoBackLabel* HelpStack::topLabel [private]
Definition at line 34 of file helpStack.h.
QVBoxLayout* HelpStack::vBoxLayout [private]
Definition at line 32 of file helpStack.h.
The documentation for this class was generated from the following files:
helpStack.h
helpStack.cpp