AccountTable Class Reference
#include <accountTable.h>
Signals
void goToMain ()
void goToJournal ()
void goToReports ()
void goToHelp ()
Public Member Functions
AccountTable (QWidget *parent=0, const char *name=0)
~AccountTable ()
void populate ()
Private Slots
void updateDb (int, int)
void editingChanged (int, int)
Private Member Functions
void keyPressEvent (QKeyEvent *event)
void insert ()
void remove (int row)
Private Attributes
Database * db
Settings * settings
bool editing
int editingRow
int editingCol
bool inserting
Constructor & Destructor Documentation
AccountTable::AccountTable (QWidget * parent = 0, const char * name = 0)
Definition at line 17 of file accountTable.cpp.
References db, editing, editingChanged(), inserting, Settings::instance(), Database::instance(), populate(), settings, and updateDb().
18     : QTable(parent,name)  
19 {
20     db = Database::instance();
21     settings = Settings::instance();
22 
23     setLeftMargin(0);
24     setVScrollBarMode(QScrollView::AlwaysOn);
25     setSelectionMode(QTable::SingleRow);
26     setFocusStyle(QTable::SpreadSheet);
27     
28     insertColumns(0,2);
29     
30     QStringList labels;
31     labels << "Account ID" << "Account Description";
32     setColumnLabels(labels);
33     
34     setColumnStretchable(1, true);
35     
36     populate();
37 
38     setCurrentCell(0,0);
39     
40     inserting = false;
41     editing = false;
42     
43     connect(this, SIGNAL(currentChanged(int, int)), this, SLOT(editingChanged(int, int)));
44     connect(this, SIGNAL(valueChanged(int, int)), this, SLOT(updateDb(int, int)));
45     
46 }
AccountTable::~AccountTable ()
Definition at line 48 of file accountTable.cpp.
49 {}
Member Function Documentation
void AccountTable::editingChanged (int, int) [private, slot]
Definition at line 186 of file accountTable.cpp.
References editingCol, and editingRow.
Referenced by AccountTable().
187 {
188     editingRow = newRow;
189     editingCol = newCol;
190 }
void AccountTable::goToHelp () [signal]
Referenced by keyPressEvent().
void AccountTable::goToJournal () [signal]
Referenced by keyPressEvent().
void AccountTable::goToMain () [signal]
Referenced by keyPressEvent().
void AccountTable::goToReports () [signal]
Referenced by keyPressEvent().
void AccountTable::insert () [private]
Definition at line 80 of file accountTable.cpp.
References db, editing, editingCol, editingRow, inserting, and Database::nextAccountKey().
Referenced by keyPressEvent().
81 {
82     inserting = true;
83 
84     int newRow = numRows();
85     insertRows(newRow);
86 
87     editing = true;
88     editingRow = newRow;
89     editingCol = 0;
90 
91     ensureCellVisible(newRow, 0);
92     setItem(newRow, 0, new AccountEditItem(this, "", db->nextAccountKey()));
93     setColumnReadOnly(0, false);
94     setItem(newRow, 1, new QTableItem(this, QTableItem::OnTyping, ""));
95     setCurrentCell(newRow,0);
96 
97     beginEdit(newRow, 0, false);
98 }
void AccountTable::keyPressEvent (QKeyEvent * event) [private]
Definition at line 192 of file accountTable.cpp.
References editing, editingCol, editingRow, goToHelp(), goToJournal(), goToMain(), goToReports(), insert(), inserting, and remove().
193 {
194     switch(event->key())
195     {
196         case Key_Insert:
197             insert();
198             break;
199         case Key_Delete:
200             remove(currentRow());
201             break;
202         case Key_Enter:
203         case Key_Return:
204         case Key_Tab:
205             if(editing)
206             {
207                 if(inserting)
208                 {
209                     if(editingCol == 1)
210                     {
211                         endEdit(editingRow, editingCol, true, true);
212                         editing = false;
213                         inserting = false;
214                         break;
215                     }
216 
217                     endEdit(editingRow, editingCol, true, true);
218                     sortColumn(0, true, true);
219 
220                     editingRow = currentRow();
221                 }
222                 else if(editingRow != (numRows() - 1))
223                 {
224                     endEdit(editingRow, editingCol, true, true);
225                     editingRow++;
226                 }
227                 else
228                 {
229                     endEdit(editingRow, editingCol, true, true);
230                     editing = false;
231                     break;
232                 }
233             }
234             editing = true;
235             editingCol = 1;
236 
237             setCurrentCell(editingRow, editingCol);
238             beginEdit(editingRow, editingCol, false);
239             break;
240         case Key_Escape:
241             if(editing)
242             {
243                 endEdit(editingRow, editingCol, true, true);
244                 editing = false;
245                 inserting = false;
246             }
247             else
248                 emit goToMain();
249             break;
250         case Key_Up:
251         case Key_Left:
252         case Key_Down:
253         case Key_Right:
254             if(inserting)
255                 sortColumn(0, true, true);
256             inserting = false;
257 
258             QTable::keyPressEvent(event);
259             break;
260         case Key_F1:
261             emit goToMain();
262             break;
263         case Key_F2:
264             break;
265         case Key_F3:
266             emit goToJournal();
267             break;
268         case Key_F4:
269             emit goToReports();
270             break;
271         case Key_F5:
272             emit goToHelp();
273             break;
274         default:
275             QTable::keyPressEvent(event);
276     }
277 }
void AccountTable::populate ()
Definition at line 51 of file accountTable.cpp.
References db, editingCol, editingRow, and Database::getAccountsData().
Referenced by AccountTable().
52 {
53     int rows = numRows();
54     for(int row = 0; row < rows; row++)
55         removeRow(0);
56     
57     QPtrList<QStringList>* data = db->getAccountsData();
58     QPtrListIterator<QStringList> it(*data);
59     
60     QStringList *stringList;
61     while((stringList = it.current()) != 0)
62     {
63         ++it;
64         insertRows(0);
65         setItem(0, 0, new AccountEditItem(this, stringList->operator[](1), stringList->operator[](0)));
66         setItem(0, 1, new QTableItem(this, QTableItem::OnTyping, stringList->operator[](2)));
67         delete stringList;
68     }
69 
70     delete data;
71 
72     setColumnReadOnly(0, true);
73     
74     sortColumn(0, true, true);
75 
76     editingRow = 0;
77     editingCol = 1;
78 }
void AccountTable::remove (int row) [private]
Definition at line 100 of file accountTable.cpp.
References Database::accountHasEntries(), db, and Database::deleteAccount().
Referenced by keyPressEvent().
101 {
102     QString key = ((AccountEditItem*)(item(row, 0)))->getKey();
103 
104     if(db->accountHasEntries(text(row, 0)))
105     {
106         QDialog dialog;
107         dialog.setCaption("Delete Record");
108 
109         QVBoxLayout vBoxLayout(&dialog);
110         vBoxLayout.setMargin(5);
111         vBoxLayout.setSpacing(5);
112 
113         QLabel label("<nobr>Cannot delete account " + text(row, 0) + "</nobr>;<br>"
114                 "<nobr>there is data associated with this account.</nobr>", &dialog);
115         
116         vBoxLayout.addWidget(&label);
117 
118         vBoxLayout.addSpacing(10);
119 
120         QHBoxLayout hBoxLayout(&vBoxLayout);
121         hBoxLayout.setSpacing(5);
122 
123         QPushButton okButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/okButton.png")),
124                              "OK", &dialog);
125         connect(&okButton, SIGNAL(clicked()), &dialog, SLOT(accept()));
126 
127         hBoxLayout.addStretch();
128         hBoxLayout.addWidget(&okButton);
129 
130         dialog.exec();
131 
132         return;
133     }
134     
135     QDialog dialog;
136     dialog.setCaption("Delete Record");
137 
138     QVBoxLayout vBoxLayout(&dialog);
139     vBoxLayout.setMargin(5);
140     vBoxLayout.setSpacing(5);
141 
142     QLabel label("<nobr>Are you sure you want to delete the selected record?</nobr>", &dialog);
143 
144     vBoxLayout.addWidget(&label);
145 
146     vBoxLayout.addSpacing(10);
147 
148     QHBoxLayout hBoxLayout(&vBoxLayout);
149     hBoxLayout.setSpacing(5);
150 
151     QPushButton buttonDelete(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/deleteButton.png")),
152                              "Delete", &dialog);
153     connect(&buttonDelete, SIGNAL(clicked()), &dialog, SLOT(accept()));
154 
155     QPushButton buttonDontDelete(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/okButton.png")),
156                                  "Don't Delete", &dialog);
157     connect(&buttonDontDelete, SIGNAL(clicked()), &dialog, SLOT(reject()));
158 
159     buttonDontDelete.setDefault(true);
160 
161     hBoxLayout.addStretch();
162     hBoxLayout.addWidget(&buttonDelete);
163     hBoxLayout.addWidget(&buttonDontDelete);
164 
165     if(dialog.exec())
166     {
167         db->deleteAccount(key);
168         removeRow(row);
169 
170         if(row > 0)
171             setCurrentCell(row - 1, 1);
172     }
173 }
void AccountTable::updateDb (int, int) [private, slot]
Definition at line 175 of file accountTable.cpp.
References db, and Database::updateAccount().
Referenced by AccountTable().
176 {
177     QString id = text(row, 0);
178     QString key = ((AccountEditItem*)(item(row, 0)))->getKey();
179     QString desc = text(row, 1);
180     db->updateAccount(key, id, desc);
181 
182     setColumnReadOnly(0, true);
183     setCurrentCell(row, 1);
184 }
Member Data Documentation
Database* AccountTable::db [private]
Definition at line 34 of file accountTable.h.
Referenced by AccountTable(), insert(), populate(), remove(), and updateDb().
bool AccountTable::editing [private]
Definition at line 37 of file accountTable.h.
Referenced by AccountTable(), insert(), and keyPressEvent().
int AccountTable::editingCol [private]
Definition at line 39 of file accountTable.h.
Referenced by editingChanged(), insert(), keyPressEvent(), and populate().
int AccountTable::editingRow [private]
Definition at line 38 of file accountTable.h.
Referenced by editingChanged(), insert(), keyPressEvent(), and populate().
bool AccountTable::inserting [private]
Definition at line 41 of file accountTable.h.
Referenced by AccountTable(), insert(), and keyPressEvent().
Settings* AccountTable::settings [private]
Definition at line 35 of file accountTable.h.
Referenced by AccountTable().
The documentation for this class was generated from the following files:
accountTable.h
accountTable.cpp