Settings Class Reference
#include <settings.h>
Public Member Functions
void destroy ()
QString getClientPath () const
void setClientPath (QString)
QString getExportPath () const
void setExportPath (QString)
QString getImportPath () const
void setImportPath (QString)
QString getDefaultDb () const
void setDefaultDb (QString)
QString getDefaultClient () const
void setDefaultClient (QString)
int getDefaultWidth () const
void setDefaultWidth (int)
int getDefaultHeight () const
void setDefaultHeight (int)
int getDefaultX () const
void setDefaultX (int)
int getDefaultY () const
void setDefaultY (int)
QString getPrinterPrinterName () const
void setPrinterPrinterName (QString)
bool getPrinterOutputToFile () const
void setPrinterOutputToFile (bool)
QString getPrinterOutputFileName () const
void setPrinterOutputFileName (QString)
QString getPrinterPrintProgram () const
void setPrinterPrintProgram (QString)
QPrinter::Orientation getPrinterOrientation () const
void setPrinterOrientation (QPrinter::Orientation)
QPrinter::PageSize getPrinterPageSize () const
void setPrinterPageSize (QPrinter::PageSize)
QPrinter::PageOrder getPrinterPageOrder () const
void setPrinterPageOrder (QPrinter::PageOrder)
QPrinter::ColorMode getPrinterColorMode () const
void setPrinterColorMode (QPrinter::ColorMode)
QPrinter::PaperSource getPrinterPaperSource () const
void setPrinterPaperSource (QPrinter::PaperSource)
int getPDFPaperSizeInt () const
QString getPDFPaperSizeString () const
void setPDFPaperSize (int)
QString getPDFPaperSizeWidth () const
void setPDFPaperSizeWidth (QString)
QString getPDFPaperSizeHeight () const
void setPDFPaperSizeHeight (QString)
int getPDFPaperSizeUnits () const
void setPDFPaperSizeUnits (int)
bool getPDFPasswordBool () const
QString getPDFPasswordString () const
void setPDFPassword (bool)
QString getPDFPermissionsString () const
bool getPDFPermissionsNoPrint () const
void setPDFPermissionsNoPrint (bool)
bool getPDFPermissionsNoModify () const
void setPDFPermissionsNoModify (bool)
bool getPDFPermissionsNoCopy () const
void setPDFPermissionsNoCopy (bool)
bool getPDFPermissionsNoAnnotate () const
void setPDFPermissionsNoAnnotate (bool)
Static Public Member Functions
Settings * instance ()
Private Member Functions
Settings ()
~Settings ()
Private Attributes
QString clientPath
QString exportPath
QString importPath
QString defaultDb
QString defaultClient
int defaultWidth
int defaultHeight
int defaultX
int defaultY
QString printerPrinterName
bool printerOutputToFile
QString printerOutputFileName
QString printerPrintProgram
QPrinter::Orientation printerOrientation
QPrinter::PageSize printerPageSize
QPrinter::PageOrder printerPageOrder
QPrinter::ColorMode printerColorMode
QPrinter::PaperSource printerPaperSource
int PDFPaperSize
QString PDFPaperSizeWidth
QString PDFPaperSizeHeight
int PDFPaperSizeUnits
bool PDFPassword
bool PDFPermissionsNoPrint
bool PDFPermissionsNoModify
bool PDFPermissionsNoCopy
bool PDFPermissionsNoAnnotate
Static Private Attributes
Settings * settings = 0
Constructor & Destructor Documentation
Settings::Settings () [private]
Definition at line 12 of file settings.cpp.
References clientPath, defaultClient, defaultDb, defaultHeight, defaultWidth, defaultX, defaultY, exportPath, importPath, PDFPaperSize, PDFPaperSizeHeight, PDFPaperSizeUnits, PDFPaperSizeWidth, PDFPassword, PDFPermissionsNoAnnotate, PDFPermissionsNoCopy, PDFPermissionsNoModify, PDFPermissionsNoPrint, printerColorMode, printerOrientation, printerOutputFileName, printerOutputToFile, printerPageOrder, printerPageSize, printerPaperSource, printerPrinterName, and printerPrintProgram.
13 {
14     // read settings
15     QSettings get;
16     get.setPath("eckroth.net", "GeneralLedger");
17     get.beginGroup("/GeneralLedger");
18     
19 #ifdef Q_OS_WIN32
20     TCHAR myDocPath[MAX_PATH];
21     char myDocPath2[MAX_PATH*2];
22     SHGetFolderPath(NULL, CSIDL_PERSONAL, NULL, 0, myDocPath);
23     wcstombs(myDocPath2, myDocPath, MAX_PATH * 2);
24     clientPath = get.readEntry("/paths/clientPath", myDocPath2);
25     exportPath = get.readEntry("/paths/exportPath", myDocPath2);
26     importPath = get.readEntry("/paths/importPath", myDocPath2);
27 #else
28     QString myHome = std::getenv("HOME");
29     clientPath = get.readEntry("/paths/clientPath", myHome);
30     exportPath = get.readEntry("/paths/exportPath", myHome);
31     importPath = get.readEntry("/paths/importPath", myHome);
32 #endif
33 
34     defaultDb = get.readEntry("/database/defaultDb", "");
35     defaultClient = get.readEntry("/database/defaultClient", "");
36 
37     defaultWidth = get.readNumEntry("/geometry/width", 700);
38     defaultHeight = get.readNumEntry("/geometry/height", 500);
39     defaultX = get.readNumEntry("/geometry/x", 0);
40     defaultY = get.readNumEntry("/geometry/y", 0);
41 
42     printerPrinterName = get.readEntry("/printer/printerName", "");
43     printerOutputToFile = (bool)get.readNumEntry("/printer/outputToFile", 0);
44     printerOutputFileName = get.readEntry("/printer/outputFileName", "");
45     printerPrintProgram = get.readEntry("/printer/printProgram", "");
46     printerOrientation = (QPrinter::Orientation)get.readNumEntry("/printer/orientation", 0);
47     printerPageSize = (QPrinter::PageSize)get.readNumEntry("/printer/pageSize", 2);
48     printerPageOrder = (QPrinter::PageOrder)get.readNumEntry("/printer/pageOrder", 0);
49     printerColorMode = (QPrinter::ColorMode)get.readNumEntry("/printer/colorMode", 0);
50     printerPaperSource = (QPrinter::PaperSource)get.readNumEntry("/printer/paperSource", 6);
51 
52     PDFPaperSize = get.readNumEntry("/PDF/paperSize", 0);
53     PDFPaperSizeWidth = get.readEntry("/PDF/paperSizeWidth", "");
54     PDFPaperSizeHeight = get.readEntry("/PDF/paperSizeHeight", "");
55     PDFPaperSizeUnits = get.readNumEntry("/PDF/paperSizeUnits", 0);
56     PDFPassword = get.readNumEntry("/PDF/password", 0);
57     PDFPermissionsNoPrint = get.readNumEntry("/PDF/permissionsNoPrint", 0);
58     PDFPermissionsNoModify = get.readNumEntry("/PDF/permissionsNoModify", 0);
59     PDFPermissionsNoCopy = get.readNumEntry("/PDF/permissionsNoCopy", 0);
60     PDFPermissionsNoAnnotate = get.readNumEntry("/PDF/permissionsNoAnnotate", 0);
61 
62     get.endGroup();
63     
64 }
Settings::~Settings () [private]
Definition at line 66 of file settings.cpp.
References clientPath, defaultClient, defaultDb, defaultHeight, defaultWidth, defaultX, defaultY, exportPath, importPath, PDFPaperSize, PDFPaperSizeHeight, PDFPaperSizeUnits, PDFPaperSizeWidth, PDFPassword, PDFPermissionsNoAnnotate, PDFPermissionsNoCopy, PDFPermissionsNoModify, PDFPermissionsNoPrint, printerColorMode, printerOrientation, printerOutputFileName, printerOutputToFile, printerPageOrder, printerPageSize, printerPaperSource, printerPrinterName, and printerPrintProgram.
67 {
68     // write settings
69     QSettings put;
70     put.setPath("eckroth.net", "GeneralLedger");
71     put.beginGroup("/GeneralLedger");
72 
73     put.writeEntry("/paths/clientPath", clientPath);
74     put.writeEntry("/paths/exportPath", exportPath);
75     put.writeEntry("/paths/importPath", importPath);
76 
77     put.writeEntry("/database/defaultDb", defaultDb);
78     put.writeEntry("/database/defaultClient", defaultClient);
79 
80     put.writeEntry("/geometry/width", defaultWidth);
81     put.writeEntry("/geometry/height", defaultHeight);
82     put.writeEntry("/geometry/x", defaultX);
83     put.writeEntry("/geometry/y", defaultY);
84 
85     put.writeEntry("/printer/printerName", printerPrinterName);
86     put.writeEntry("/printer/outputToFile", (int)printerOutputToFile);
87     put.writeEntry("/printer/outputFileName", printerOutputFileName);
88     put.writeEntry("/printer/printProgram", printerPrintProgram);
89     put.writeEntry("/printer/orientation", (int)printerOrientation);
90     put.writeEntry("/printer/pageSize", (int)printerPageSize);
91     put.writeEntry("/printer/pageOrder", (int)printerPageOrder);
92     put.writeEntry("/printer/colorMode", (int)printerColorMode);
93     put.writeEntry("/printer/paperSource", (int)printerPaperSource);
94 
95     put.writeEntry("/PDF/paperSize", PDFPaperSize);
96     put.writeEntry("/PDF/paperSizeWidth", PDFPaperSizeWidth);
97     put.writeEntry("/PDF/paperSizeHeight", PDFPaperSizeHeight);
98     put.writeEntry("/PDF/paperSizeUnits", PDFPaperSizeUnits);
99     put.writeEntry("/PDF/password", (int)PDFPassword);
100     put.writeEntry("/PDF/permissionsNoPrint", (int)PDFPermissionsNoPrint);
101     put.writeEntry("/PDF/permissionsNoModify", (int)PDFPermissionsNoModify);
102     put.writeEntry("/PDF/permissionsNoCopy", (int)PDFPermissionsNoCopy);
103     put.writeEntry("/PDF/permissionsNoAnnotate", (int)PDFPermissionsNoAnnotate);
104 
105     put.endGroup();
106 }
Member Function Documentation
void Settings::destroy ()
Definition at line 115 of file settings.cpp.
References settings.
Referenced by main().
116 {
117     if(settings != 0)
118         delete settings;
119 }
QString Settings::getClientPath () const
Definition at line 121 of file settings.cpp.
References clientPath.
Referenced by Database::createNew(), Database::Database(), MainStack::MainStack(), Database::openNew(), and ReportStack::ReportStack().
122 {
123     return clientPath;
124 }
QString Settings::getDefaultClient () const
Definition at line 161 of file settings.cpp.
References defaultClient.
Referenced by Database::Database().
162 {
163     return defaultClient;
164 }
QString Settings::getDefaultDb () const
Definition at line 151 of file settings.cpp.
References defaultDb.
Referenced by Database::Database().
152 {
153     return defaultDb;
154 }
int Settings::getDefaultHeight () const
Definition at line 181 of file settings.cpp.
References defaultHeight.
Referenced by Tabs::Tabs().
182 {
183     return defaultHeight;
184 }
int Settings::getDefaultWidth () const
Definition at line 171 of file settings.cpp.
References defaultWidth.
Referenced by Tabs::Tabs().
172 {
173     return defaultWidth;
174 }
int Settings::getDefaultX () const
Definition at line 191 of file settings.cpp.
References defaultX.
Referenced by Tabs::Tabs().
192 {
193     return defaultX;
194 }
int Settings::getDefaultY () const
Definition at line 201 of file settings.cpp.
References defaultY.
Referenced by Tabs::Tabs().
202 {
203     return defaultY;
204 }
QString Settings::getExportPath () const
Definition at line 131 of file settings.cpp.
References exportPath.
Referenced by AccountStack::AccountStack(), JournalStack::JournalStack(), MainStack::MainStack(), and ReportStack::ReportStack().
132 {
133     return exportPath;
134 }
QString Settings::getImportPath () const
Definition at line 141 of file settings.cpp.
References importPath.
Referenced by AccountStack::AccountStack(), JournalStack::JournalStack(), MainStack::MainStack(), and ReportStack::ReportStack().
142 {
143     return importPath;
144 }
QString Settings::getPDFPaperSizeHeight () const
Definition at line 335 of file settings.cpp.
References PDFPaperSizeHeight.
Referenced by PDFOptions::exec().
336 {
337     return PDFPaperSizeHeight;
338 }
int Settings::getPDFPaperSizeInt () const
Definition at line 301 of file settings.cpp.
References PDFPaperSize.
Referenced by PDFOptions::exec().
302 {
303     return PDFPaperSize;
304 }
QString Settings::getPDFPaperSizeString () const
Definition at line 306 of file settings.cpp.
References PDFPaperSize.
Referenced by PDFOptions::exec().
307 {
308     if(PDFPaperSize == 0)
309         return "Letter (8.5 x 11in)";
310     if(PDFPaperSize == 1)
311         return "A4 (8.27 x 11.69in)";
312     if(PDFPaperSize == 2)
313         return "Universal (8.27 x 11in)";
314     if(PDFPaperSize == 3)
315         return "Custom";
316     else
317         return "";
318 }
int Settings::getPDFPaperSizeUnits () const
Definition at line 345 of file settings.cpp.
References PDFPaperSizeUnits.
Referenced by PDFOptions::exec().
346 {
347     return PDFPaperSizeUnits;
348 }
QString Settings::getPDFPaperSizeWidth () const
Definition at line 325 of file settings.cpp.
References PDFPaperSizeWidth.
Referenced by PDFOptions::exec().
326 {
327     return PDFPaperSizeWidth;
328 }
bool Settings::getPDFPasswordBool () const
Definition at line 355 of file settings.cpp.
References PDFPassword.
Referenced by PDFOptions::exec().
356 {
357     return PDFPassword;
358 }
QString Settings::getPDFPasswordString () const
Definition at line 360 of file settings.cpp.
References PDFPassword.
Referenced by PDFOptions::exec().
361 {
362     if(PDFPassword)
363         return "Yes";
364     else
365         return "No";
366 }
bool Settings::getPDFPermissionsNoAnnotate () const
Definition at line 440 of file settings.cpp.
References PDFPermissionsNoAnnotate.
Referenced by PDFOptions::exec().
441 {
442     return PDFPermissionsNoAnnotate;
443 }
bool Settings::getPDFPermissionsNoCopy () const
Definition at line 430 of file settings.cpp.
References PDFPermissionsNoCopy.
Referenced by PDFOptions::exec().
431 {
432     return PDFPermissionsNoCopy;
433 }
bool Settings::getPDFPermissionsNoModify () const
Definition at line 420 of file settings.cpp.
References PDFPermissionsNoModify.
Referenced by PDFOptions::exec().
421 {
422     return PDFPermissionsNoModify;
423 }
bool Settings::getPDFPermissionsNoPrint () const
Definition at line 410 of file settings.cpp.
References PDFPermissionsNoPrint.
Referenced by PDFOptions::exec().
411 {
412     return PDFPermissionsNoPrint;
413 }
QString Settings::getPDFPermissionsString () const
Definition at line 373 of file settings.cpp.
References PDFPermissionsNoAnnotate, PDFPermissionsNoCopy, PDFPermissionsNoModify, and PDFPermissionsNoPrint.
Referenced by PDFOptions::exec().
374 {
375     QString string("");
376 
377     if(PDFPermissionsNoPrint)
378         string += "No-Print";
379     
380     if(PDFPermissionsNoModify)
381     {
382         if(string != "")
383             string += ", No-Modify";
384         else
385             string += "No-Modify";
386     }
387 
388     if(PDFPermissionsNoCopy)
389     {
390         if(string != "")
391             string += ", No-Copy";
392         else
393             string += "No-Copy";
394     }
395 
396     if(PDFPermissionsNoAnnotate)
397     {
398         if(string != "")
399             string += ", No-Annotate";
400         else
401             string += "No-Annotate";
402     }
403 
404     if(string == "")
405         string += "All";
406 
407     return string;
408 }
QPrinter::ColorMode Settings::getPrinterColorMode () const
Definition at line 281 of file settings.cpp.
References printerColorMode.
Referenced by Printer::Printer().
282 {
283     return printerColorMode;
284 }
QPrinter::Orientation Settings::getPrinterOrientation () const
Definition at line 251 of file settings.cpp.
References printerOrientation.
Referenced by Printer::Printer().
252 {
253     return printerOrientation;
254 }
QString Settings::getPrinterOutputFileName () const
Definition at line 231 of file settings.cpp.
References printerOutputFileName.
Referenced by Printer::Printer().
232 {
233     return printerOutputFileName;
234 }
bool Settings::getPrinterOutputToFile () const
Definition at line 221 of file settings.cpp.
References printerOutputToFile.
Referenced by Printer::Printer().
222 {
223     return printerOutputToFile;
224 }
QPrinter::PageOrder Settings::getPrinterPageOrder () const
Definition at line 271 of file settings.cpp.
References printerPageOrder.
Referenced by Printer::Printer().
272 {
273     return printerPageOrder;
274 }
QPrinter::PageSize Settings::getPrinterPageSize () const
Definition at line 261 of file settings.cpp.
References printerPageSize.
Referenced by Printer::Printer().
262 {
263     return printerPageSize;
264 }
QPrinter::PaperSource Settings::getPrinterPaperSource () const
Definition at line 291 of file settings.cpp.
References printerPaperSource.
Referenced by Printer::Printer().
292 {
293     return printerPaperSource;
294 }
QString Settings::getPrinterPrinterName () const
Definition at line 211 of file settings.cpp.
References printerPrinterName.
Referenced by Printer::Printer().
212 {
213     return printerPrinterName;
214 }
QString Settings::getPrinterPrintProgram () const
Definition at line 241 of file settings.cpp.
References printerPrintProgram.
Referenced by Printer::Printer().
242 {
243     return printerPrintProgram;
244 }
Settings * Settings::instance () [static]
Definition at line 108 of file settings.cpp.
References settings.
Referenced by AccountStack::AccountStack(), AccountTable::AccountTable(), Database::Database(), JournalStack::JournalStack(), main(), MainStack::MainStack(), PDFOptions::PDFOptions(), Printer::Printer(), ReportStack::ReportStack(), and Tabs::Tabs().
109 {
110     if(settings == 0)
111         settings = new Settings;
112     return settings;
113 }
void Settings::setClientPath (QString)
Definition at line 126 of file settings.cpp.
References clientPath.
Referenced by MainStack::changePath().
127 {
128     clientPath = newClientPath;
129 }
void Settings::setDefaultClient (QString)
Definition at line 166 of file settings.cpp.
References defaultClient.
Referenced by Database::~Database().
167 {
168     defaultClient = newDefaultClient;
169 }
void Settings::setDefaultDb (QString)
Definition at line 156 of file settings.cpp.
References defaultDb.
Referenced by Database::~Database().
157 {
158     defaultDb = newDefaultDb;
159 }
void Settings::setDefaultHeight (int)
Definition at line 186 of file settings.cpp.
References defaultHeight.
Referenced by Tabs::quit().
187 {
188     defaultHeight = newDefaultHeight;
189 }
void Settings::setDefaultWidth (int)
Definition at line 176 of file settings.cpp.
References defaultWidth.
Referenced by Tabs::quit().
177 {
178     defaultWidth = newDefaultWidth;
179 }
void Settings::setDefaultX (int)
Definition at line 196 of file settings.cpp.
References defaultX.
Referenced by Tabs::quit().
197 {
198     defaultX = newDefaultX;
199 }
void Settings::setDefaultY (int)
Definition at line 206 of file settings.cpp.
References defaultY.
Referenced by Tabs::quit().
207 {
208     defaultY = newDefaultY;
209 }
void Settings::setExportPath (QString)
Definition at line 136 of file settings.cpp.
References exportPath.
137 {
138     exportPath = newExportPath;
139 }
void Settings::setImportPath (QString)
Definition at line 146 of file settings.cpp.
References importPath.
147 {
148     importPath = newImportPath;
149 }
void Settings::setPDFPaperSize (int)
Definition at line 320 of file settings.cpp.
References PDFPaperSize.
Referenced by PDFOptions::exec().
321 {
322     PDFPaperSize = newPDFPaperSize;
323 }
void Settings::setPDFPaperSizeHeight (QString)
Definition at line 340 of file settings.cpp.
References PDFPaperSizeHeight.
Referenced by PDFOptions::exec().
341 {
342     PDFPaperSizeHeight = newPDFPaperSizeHeight;
343 }
void Settings::setPDFPaperSizeUnits (int)
Definition at line 350 of file settings.cpp.
References PDFPaperSizeUnits.
Referenced by PDFOptions::exec().
351 {
352     PDFPaperSizeUnits = newPDFPaperSizeUnits;
353 }
void Settings::setPDFPaperSizeWidth (QString)
Definition at line 330 of file settings.cpp.
References PDFPaperSizeWidth.
Referenced by PDFOptions::exec().
331 {
332     PDFPaperSizeWidth = newPDFPaperSizeWidth;
333 }
void Settings::setPDFPassword (bool)
Definition at line 368 of file settings.cpp.
References PDFPassword.
Referenced by PDFOptions::exec().
369 {
370     PDFPassword = newPDFPassword;
371 }
void Settings::setPDFPermissionsNoAnnotate (bool)
Definition at line 445 of file settings.cpp.
References PDFPermissionsNoAnnotate.
Referenced by PDFOptions::exec().
446 {
447     PDFPermissionsNoAnnotate = newPDFPermissionsNoAnnotate;
448 }       
void Settings::setPDFPermissionsNoCopy (bool)
Definition at line 435 of file settings.cpp.
References PDFPermissionsNoCopy.
Referenced by PDFOptions::exec().
436 {
437     PDFPermissionsNoCopy = newPDFPermissionsNoCopy;
438 }
void Settings::setPDFPermissionsNoModify (bool)
Definition at line 425 of file settings.cpp.
References PDFPermissionsNoModify.
Referenced by PDFOptions::exec().
426 {
427     PDFPermissionsNoModify = newPDFPermissionsNoModify;
428 }
void Settings::setPDFPermissionsNoPrint (bool)
Definition at line 415 of file settings.cpp.
References PDFPermissionsNoPrint.
Referenced by PDFOptions::exec().
416 {
417     PDFPermissionsNoPrint = newPDFPermissionsNoPrint;
418 }
void Settings::setPrinterColorMode (QPrinter::ColorMode)
Definition at line 286 of file settings.cpp.
References printerColorMode.
Referenced by Printer::~Printer().
287 {
288     printerColorMode = newPrinterColorMode;
289 }
void Settings::setPrinterOrientation (QPrinter::Orientation)
Definition at line 256 of file settings.cpp.
References printerOrientation.
Referenced by Printer::~Printer().
257 {
258     printerOrientation = newPrinterOrientation;
259 }
void Settings::setPrinterOutputFileName (QString)
Definition at line 236 of file settings.cpp.
References printerOutputFileName.
Referenced by Printer::~Printer().
237 {
238     printerOutputFileName = newPrinterOutputFileName;
239 }
void Settings::setPrinterOutputToFile (bool)
Definition at line 226 of file settings.cpp.
References printerOutputToFile.
Referenced by Printer::~Printer().
227 {
228     printerOutputToFile = newPrinterOutputToFile;
229 }
void Settings::setPrinterPageOrder (QPrinter::PageOrder)
Definition at line 276 of file settings.cpp.
References printerPageOrder.
Referenced by Printer::~Printer().
277 {
278     printerPageOrder = newPrinterPageOrder;
279 }
void Settings::setPrinterPageSize (QPrinter::PageSize)
Definition at line 266 of file settings.cpp.
References printerPageSize.
Referenced by Printer::~Printer().
267 {
268     printerPageSize = newPrinterPageSize;
269 }
void Settings::setPrinterPaperSource (QPrinter::PaperSource)
Definition at line 296 of file settings.cpp.
References printerPaperSource.
Referenced by Printer::~Printer().
297 {
298     printerPaperSource = newPrinterPaperSource;
299 }
void Settings::setPrinterPrinterName (QString)
Definition at line 216 of file settings.cpp.
References printerPrinterName.
Referenced by Printer::~Printer().
217 {
218     printerPrinterName = newPrinterPrinterName;
219 }
void Settings::setPrinterPrintProgram (QString)
Definition at line 246 of file settings.cpp.
References printerPrintProgram.
Referenced by Printer::~Printer().
247 {
248     printerPrintProgram = newPrinterPrintProgram;
249 }
Member Data Documentation
QString Settings::clientPath [private]
Definition at line 89 of file settings.h.
Referenced by getClientPath(), setClientPath(), Settings(), and ~Settings().
QString Settings::defaultClient [private]
Definition at line 94 of file settings.h.
Referenced by getDefaultClient(), setDefaultClient(), Settings(), and ~Settings().
QString Settings::defaultDb [private]
Definition at line 93 of file settings.h.
Referenced by getDefaultDb(), setDefaultDb(), Settings(), and ~Settings().
int Settings::defaultHeight [private]
Definition at line 97 of file settings.h.
Referenced by getDefaultHeight(), setDefaultHeight(), Settings(), and ~Settings().
int Settings::defaultWidth [private]
Definition at line 96 of file settings.h.
Referenced by getDefaultWidth(), setDefaultWidth(), Settings(), and ~Settings().
int Settings::defaultX [private]
Definition at line 98 of file settings.h.
Referenced by getDefaultX(), setDefaultX(), Settings(), and ~Settings().
int Settings::defaultY [private]
Definition at line 99 of file settings.h.
Referenced by getDefaultY(), setDefaultY(), Settings(), and ~Settings().
QString Settings::exportPath [private]
Definition at line 90 of file settings.h.
Referenced by getExportPath(), setExportPath(), Settings(), and ~Settings().
QString Settings::importPath [private]
Definition at line 91 of file settings.h.
Referenced by getImportPath(), setImportPath(), Settings(), and ~Settings().
int Settings::PDFPaperSize [private]
Definition at line 111 of file settings.h.
Referenced by getPDFPaperSizeInt(), getPDFPaperSizeString(), setPDFPaperSize(), Settings(), and ~Settings().
QString Settings::PDFPaperSizeHeight [private]
Definition at line 113 of file settings.h.
Referenced by getPDFPaperSizeHeight(), setPDFPaperSizeHeight(), Settings(), and ~Settings().
int Settings::PDFPaperSizeUnits [private]
Definition at line 114 of file settings.h.
Referenced by getPDFPaperSizeUnits(), setPDFPaperSizeUnits(), Settings(), and ~Settings().
QString Settings::PDFPaperSizeWidth [private]
Definition at line 112 of file settings.h.
Referenced by getPDFPaperSizeWidth(), setPDFPaperSizeWidth(), Settings(), and ~Settings().
bool Settings::PDFPassword [private]
Definition at line 115 of file settings.h.
Referenced by getPDFPasswordBool(), getPDFPasswordString(), setPDFPassword(), Settings(), and ~Settings().
bool Settings::PDFPermissionsNoAnnotate [private]
Definition at line 119 of file settings.h.
Referenced by getPDFPermissionsNoAnnotate(), getPDFPermissionsString(), setPDFPermissionsNoAnnotate(), Settings(), and ~Settings().
bool Settings::PDFPermissionsNoCopy [private]
Definition at line 118 of file settings.h.
Referenced by getPDFPermissionsNoCopy(), getPDFPermissionsString(), setPDFPermissionsNoCopy(), Settings(), and ~Settings().
bool Settings::PDFPermissionsNoModify [private]
Definition at line 117 of file settings.h.
Referenced by getPDFPermissionsNoModify(), getPDFPermissionsString(), setPDFPermissionsNoModify(), Settings(), and ~Settings().
bool Settings::PDFPermissionsNoPrint [private]
Definition at line 116 of file settings.h.
Referenced by getPDFPermissionsNoPrint(), getPDFPermissionsString(), setPDFPermissionsNoPrint(), Settings(), and ~Settings().
QPrinter::ColorMode Settings::printerColorMode [private]
Definition at line 108 of file settings.h.
Referenced by getPrinterColorMode(), setPrinterColorMode(), Settings(), and ~Settings().
QPrinter::Orientation Settings::printerOrientation [private]
Definition at line 105 of file settings.h.
Referenced by getPrinterOrientation(), setPrinterOrientation(), Settings(), and ~Settings().
QString Settings::printerOutputFileName [private]
Definition at line 103 of file settings.h.
Referenced by getPrinterOutputFileName(), setPrinterOutputFileName(), Settings(), and ~Settings().
bool Settings::printerOutputToFile [private]
Definition at line 102 of file settings.h.
Referenced by getPrinterOutputToFile(), setPrinterOutputToFile(), Settings(), and ~Settings().
QPrinter::PageOrder Settings::printerPageOrder [private]
Definition at line 107 of file settings.h.
Referenced by getPrinterPageOrder(), setPrinterPageOrder(), Settings(), and ~Settings().
QPrinter::PageSize Settings::printerPageSize [private]
Definition at line 106 of file settings.h.
Referenced by getPrinterPageSize(), setPrinterPageSize(), Settings(), and ~Settings().
QPrinter::PaperSource Settings::printerPaperSource [private]
Definition at line 109 of file settings.h.
Referenced by getPrinterPaperSource(), setPrinterPaperSource(), Settings(), and ~Settings().
QString Settings::printerPrinterName [private]
Definition at line 101 of file settings.h.
Referenced by getPrinterPrinterName(), setPrinterPrinterName(), Settings(), and ~Settings().
QString Settings::printerPrintProgram [private]
Definition at line 104 of file settings.h.
Referenced by getPrinterPrintProgram(), setPrinterPrintProgram(), Settings(), and ~Settings().
Settings * Settings::settings = 0 [static, private]
Definition at line 451 of file settings.cpp.
Referenced by destroy(), and instance().
The documentation for this class was generated from the following files:
settings.h
settings.cpp