JournalStack Class Reference
#include <journalStack.h>
Public Slots
void saveAndClear ()
Signals
void goToMain ()
void goToAccounts ()
void goToReports ()
void goToHelp ()
Public Member Functions
JournalStack (QWidget *parent=0, const char *name=0)
~JournalStack ()
Private Slots
void dbOpened ()
void importCSV ()
void exportCSV ()
void printJournal ()
Private Member Functions
bool eventFilter (QObject *target, QEvent *event)
void showEvent (QShowEvent *)
Private Attributes
Database * db
Settings * settings
Printer * printer
QString exportPath
QString importPath
bool active
bool printed
xx xx xx xx xx xx xx xx xx
struct {
 QVBoxLayout * vBoxLayout
 QBoxLayout * labelLayout
 GoBackLabel * topLabel
 QPushButton * saveAndClear
 QPushButton * print
 JournalTable * dataTable
 JournalSummary * summary
 QLabel * hr
 QWidget * bottomWidget
 QHBoxLayout * bottomHBoxLayout
 QLabel * bottomLabel
 QFrame * bottomRightFrame
 QBoxLayout * bottomRightBoxLayout
 QPushButton * importButton
 QPushButton * exportButton
} main
Constructor & Destructor Documentation
JournalStack::JournalStack (QWidget * parent = 0, const char * name = 0)
Definition at line 20 of file journalStack.cpp.
References active, db, exportPath, Settings::getExportPath(), Settings::getImportPath(), importPath, Settings::instance(), Printer::instance(), Database::instance(), printed, printer, and settings.
21     : QWidget(parent,name)
22 {
23     db = Database::instance();
24     printer = Printer::instance();
25     settings = Settings::instance();
26 
27     exportPath = settings->getExportPath();
28     importPath = settings->getImportPath();
29     
30     active = false;
31     printed = false;
32 }
JournalStack::~JournalStack ()
Definition at line 34 of file journalStack.cpp.
35 {}
Member Function Documentation
void JournalStack::dbOpened () [private, slot]
Definition at line 37 of file journalStack.cpp.
References active, exportCSV(), goToAccounts(), goToHelp(), goToMain(), goToReports(), importCSV(), main, printJournal(), and saveAndClear().
38 {
39     if(active)
40     {
41         delete main.exportButton;
42         delete main.importButton;
43         delete main.bottomRightBoxLayout;
44         delete main.bottomRightFrame;
45         delete main.bottomLabel;
46         delete main.bottomHBoxLayout;
47         delete main.bottomWidget;
48         delete main.hr;
49         delete main.summary;
50         delete main.dataTable;
51         delete main.saveAndClear;
52         delete main.print;
53         delete main.topLabel;
54         delete main.labelLayout;
55         delete main.vBoxLayout;
56     }
57     
58     main.vBoxLayout = new QVBoxLayout(this);
59     main.vBoxLayout->setMargin(5);
60     
61     main.labelLayout = new QBoxLayout(main.vBoxLayout, QBoxLayout::LeftToRight);
62     
63     main.topLabel = new GoBackLabel(this);
64     connect(main.topLabel, SIGNAL(goBack()), this, SIGNAL(goToMain()));
65     
66     main.saveAndClear = new QPushButton(
67             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/saveAndClear.png") ),
68             "Save and Clear (F8)", this);
69     main.saveAndClear->setFocusPolicy(QWidget::NoFocus);
70     connect(main.saveAndClear, SIGNAL(clicked()), this, SLOT(saveAndClear()));
71     
72     main.print = new QPushButton(
73             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/print.png") ),
74             "Print Journal Entries (F9)", this);
75     main.print->setFocusPolicy(QWidget::NoFocus);
76     connect(main.print, SIGNAL(clicked()), this, SLOT(printJournal()));
77     
78     main.labelLayout->addWidget(main.topLabel, 0, Qt::AlignLeft | Qt::AlignTop);
79     main.labelLayout->addStretch();
80     main.labelLayout->addWidget(main.saveAndClear);
81     main.labelLayout->addSpacing(5);
82     main.labelLayout->addWidget(main.print);
83     
84     main.dataTable = new JournalTable(this);
85     connect(main.dataTable, SIGNAL(goToMain()), this, SIGNAL(goToMain()));
86     connect(main.dataTable, SIGNAL(goToAccounts()), this, SIGNAL(goToAccounts()));
87     connect(main.dataTable, SIGNAL(goToReports()), this, SIGNAL(goToReports()));
88     connect(main.dataTable, SIGNAL(goToHelp()), this, SIGNAL(goToHelp()));
89     main.dataTable->installEventFilter(this);
90     
91     main.vBoxLayout->addSpacing(5);
92     main.vBoxLayout->addWidget(main.dataTable);
93     
94     main.summary = new JournalSummary(this, 0, main.dataTable);
95     main.vBoxLayout->addWidget(main.summary);
96     
97     main.hr = new QLabel("<hr>", this);
98     main.vBoxLayout->addWidget(main.hr);
99     
100     
101     main.bottomWidget = new QWidget(this);
102     main.bottomHBoxLayout = new QHBoxLayout(main.bottomWidget);
103     
104     main.bottomLabel = new QLabel(
105             "<nobr><b>Keyboard Control:</b></nobr><br>"
106             "<nobr> &nbsp; &nbsp; <b>Enter</b>: Edit current field, move to next field</nobr><br>"
107             "<nobr> &nbsp; &nbsp; <b>Insert</b> / <b>Delete</b>: Create new entry / Delete selected entry</nobr>",
108     main.bottomWidget);
109     
110     main.bottomRightFrame = new QFrame(main.bottomWidget);
111     main.bottomRightBoxLayout = new QBoxLayout(main.bottomRightFrame, QBoxLayout::LeftToRight);
112     main.bottomRightBoxLayout->setSpacing(5);
113     
114     main.importButton = new QPushButton(
115             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/import.png") ),
116             "Import from CSV (F11)", main.bottomRightFrame);
117     main.importButton->setFocusPolicy(QWidget::NoFocus);
118     connect(main.importButton, SIGNAL(clicked()), this, SLOT(importCSV()));
119     
120     main.exportButton = new QPushButton(
121             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/export.png") ),
122             "Export to CSV (F12)", main.bottomRightFrame);
123     main.exportButton->setFocusPolicy(QWidget::NoFocus);
124     connect(main.exportButton, SIGNAL(clicked()), this, SLOT(exportCSV()));
125     
126     main.bottomRightBoxLayout->addWidget(main.importButton, 0, Qt::AlignLeft | Qt::AlignTop);
127     main.bottomRightBoxLayout->addWidget(main.exportButton, 0, Qt::AlignLeft | Qt::AlignTop);
128     
129     main.bottomHBoxLayout->addWidget(main.bottomLabel);
130     main.bottomHBoxLayout->addStretch();
131     main.bottomHBoxLayout->addWidget(main.bottomRightFrame);
132     
133     main.vBoxLayout->addWidget(main.bottomWidget);
134     
135     active = true;
136 }
bool JournalStack::eventFilter (QObject * target, QEvent * event) [private]
Definition at line 170 of file journalStack.cpp.
References exportCSV(), importCSV(), printJournal(), and saveAndClear().
171 {
172     if(event->type() == QEvent::KeyPress)
173     {
174         QKeyEvent *keyEvent = (QKeyEvent*)event;
175         if(keyEvent->key() == Key_F8)
176         {
177             saveAndClear();
178             return true;
179         }
180         if(keyEvent->key() == Key_F9)
181         {
182             printJournal();
183             return true;
184         }
185         if(keyEvent->key() == Key_F11)
186         {
187             importCSV();
188             return true;
189         }
190         if(keyEvent->key() == Key_F12)
191         {
192             exportCSV();
193             return true;
194         }
195     }
196     
197     return QWidget::eventFilter(target,event);
198 }
void JournalStack::exportCSV () [private, slot]
Definition at line 154 of file journalStack.cpp.
References db, Database::exportCSV(), exportPath, and Database::journalTmpEmpty().
Referenced by dbOpened(), and eventFilter().
155 {
156     if(db->journalTmpEmpty())
157         return;
158 
159     QString file = QFileDialog::getSaveFileName(
160             exportPath,
161             "Comma Separated Values (*.csv)",
162             this,
163             0,
164             "Export Journal Entries");
165 
166     if(file != "")
167         db->exportCSV("journalTmp", file);
168 }
void JournalStack::goToAccounts () [signal]
Referenced by dbOpened().
void JournalStack::goToHelp () [signal]
Referenced by dbOpened().
void JournalStack::goToMain () [signal]
Referenced by dbOpened().
void JournalStack::goToReports () [signal]
Referenced by dbOpened().
void JournalStack::importCSV () [private, slot]
Definition at line 138 of file journalStack.cpp.
References db, Database::importCSV(), importPath, and main.
Referenced by dbOpened(), and eventFilter().
139 {
140     QString file = QFileDialog::getOpenFileName(
141             importPath,
142             "Comma Separated Values (*.csv)",
143             this,
144             0,
145             "Import Journal Entries");
146     
147     if(file != "")
148     {
149         db->importCSV("journalTmp", file);
150         main.dataTable->populate();
151     }
152 }
void JournalStack::printJournal () [private, slot]
Definition at line 245 of file journalStack.cpp.
References db, Database::getJournalTmpReport(), Database::journalTmpEmpty(), Database::journalTmpReportData(), Database::journalTmpReportHeader(), printer, and Printer::printReport().
Referenced by dbOpened(), and eventFilter().
246 {
247     if(db->journalTmpEmpty())
248         return;
249 
250     db->getJournalTmpReport();
251     printer->printReport(db->journalTmpReportHeader(), db->journalTmpReportData());
252 }
void JournalStack::saveAndClear () [slot]
Referenced by dbOpened(), and eventFilter().
void JournalStack::showEvent (QShowEvent *) [private]
Definition at line 254 of file journalStack.cpp.
References main.
255 {
256     main.dataTable->setFocus();
257 }
Member Data Documentation
bool JournalStack::active [private]
Definition at line 55 of file journalStack.h.
Referenced by dbOpened(), and JournalStack().
QHBoxLayout* JournalStack::bottomHBoxLayout [private]
Definition at line 69 of file journalStack.h.
QLabel* JournalStack::bottomLabel [private]
Definition at line 70 of file journalStack.h.
QBoxLayout* JournalStack::bottomRightBoxLayout [private]
Definition at line 72 of file journalStack.h.
QFrame* JournalStack::bottomRightFrame [private]
Definition at line 71 of file journalStack.h.
QWidget* JournalStack::bottomWidget [private]
Definition at line 68 of file journalStack.h.
JournalTable* JournalStack::dataTable [private]
Definition at line 65 of file journalStack.h.
Database* JournalStack::db [private]
Definition at line 48 of file journalStack.h.
Referenced by exportCSV(), importCSV(), JournalStack(), and printJournal().
QPushButton* JournalStack::exportButton [private]
Definition at line 74 of file journalStack.h.
QString JournalStack::exportPath [private]
Definition at line 52 of file journalStack.h.
Referenced by exportCSV(), and JournalStack().
QLabel* JournalStack::hr [private]
Definition at line 67 of file journalStack.h.
QPushButton* JournalStack::importButton [private]
Definition at line 73 of file journalStack.h.
QString JournalStack::importPath [private]
Definition at line 53 of file journalStack.h.
Referenced by importCSV(), and JournalStack().
QBoxLayout* JournalStack::labelLayout [private]
Definition at line 61 of file journalStack.h.
struct { ... } JournalStack::main [private]
Referenced by dbOpened(), importCSV(), and showEvent().
QPushButton* JournalStack::print [private]
Definition at line 64 of file journalStack.h.
bool JournalStack::printed [private]
Definition at line 57 of file journalStack.h.
Referenced by JournalStack().
Printer* JournalStack::printer [private]
Definition at line 50 of file journalStack.h.
Referenced by JournalStack(), and printJournal().
void JournalStack::saveAndClear [private]
Definition at line 200 of file journalStack.cpp.
201 {
202     if(db->journalTmpEmpty())
203         return;
204 
205     if(!printed)
206     {
207         QDialog dialog;
208         dialog.setCaption("Print Before Closing");
209 
210         QVBoxLayout vBoxLayout(&dialog);
211         vBoxLayout.setMargin(5);
212         vBoxLayout.setSpacing(5);
213 
214         QLabel label("<nobr>You have not printed the Journal Entries.</nobr><br>"
215                 "<nobr>Would you like to print them now?</nobr>", &dialog);
216         vBoxLayout.addWidget(&label);
217 
218         vBoxLayout.addSpacing(10);
219 
220         QHBoxLayout hBoxLayout(&vBoxLayout);
221         hBoxLayout.setSpacing(5);
222 
223         QPushButton noPrintButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/saveAndClear.png")),
224                                   "Save Without Printing", &dialog);
225         connect(&noPrintButton, SIGNAL(clicked()), &dialog, SLOT(reject()));
226         noPrintButton.setDefault(false);
227 
228         QPushButton printButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/print.png")),
229                                 "Print and Save", &dialog);
230         connect(&printButton, SIGNAL(clicked()), &dialog, SLOT(accept()));
231         printButton.setDefault(true);
232 
233         hBoxLayout.addStretch();
234         hBoxLayout.addWidget(&noPrintButton);
235         hBoxLayout.addWidget(&printButton);
236 
237         if(dialog.exec())
238             printJournal();
239 
240     }
241     db->commitJournalTmp();
242     main.dataTable->clearTable();
243 }
Settings* JournalStack::settings [private]
Definition at line 49 of file journalStack.h.
Referenced by JournalStack().
JournalSummary* JournalStack::summary [private]
Definition at line 66 of file journalStack.h.
GoBackLabel* JournalStack::topLabel [private]
Definition at line 62 of file journalStack.h.
QVBoxLayout* JournalStack::vBoxLayout [private]
Definition at line 60 of file journalStack.h.
The documentation for this class was generated from the following files:
journalStack.h
journalStack.cpp