IncomeRetailEditor Class Reference
#include <incomeRetailEditor.h>
Public Member Functions
IncomeRetailEditor (QWidget *parent=0, const char *name=0)
~IncomeRetailEditor ()
Private Slots
void updateSection (void *)
void addElement (int category)
void addIncome ()
void addCOS ()
void addExpenses ()
void oneAccountToggled ()
void rangeAccountToggled ()
void updateAccounts ()
Private Member Functions
void listSection (ElementSection *section)
void deleteSection (ElementSection *section)
Private Attributes
Database * db
QStringList accounts
QFrame * frame
QVBoxLayout * vBoxLayout
IncomeRetailEditor::ElementSection income
IncomeRetailEditor::ElementSection cos
IncomeRetailEditor::ElementSection expenses
xx xx xx xx xx xx xx xx xx
struct {
 QDialog * main
 QVBoxLayout * vBoxLayout
 QRadioButton * oneAccount
 QFrame * oneAccountFrame
 QHBoxLayout * oneAccountHBoxLayout
 QLabel * oneAccountLabel
 AccountList * oneAccountEdit
 QRadioButton * rangeAccount
 QFrame * rangeAccountFrame
 QHBoxLayout * rangeAccountHBoxLayout
 QFrame * rangeAccountFrameList
 QVBoxLayout * rangeAccountFrameListVBoxLayout
 QFrame * rangeBeginEndFrame
 QHBoxLayout * rangeBeginEndHBoxLayout
 QLabel * rangeBegin
 AccountList * rangeBeginEdit
 QLabel * rangeBetween
 AccountList * rangeEndEdit
 QFrame * rangeDescFrame
 QHBoxLayout * rangeDescFrameHBoxLayout
 QLabel * rangeDesc
 QLineEdit * rangeDescEdit
 QFrame * buttonFrame
 QHBoxLayout * buttonFrameHBoxLayout
 QPushButton * ok
 QPushButton * cancel
} dialog
Constructor & Destructor Documentation
IncomeRetailEditor::IncomeRetailEditor (QWidget * parent = 0, const char * name = 0)
Definition at line 18 of file incomeRetailEditor.cpp.
References accounts, IncomeRetailEditor::ElementSection::addButton, addCOS(), addExpenses(), addIncome(), IncomeRetailEditor::ElementSection::bottomFrame, IncomeRetailEditor::ElementSection::bottomHBoxLayout, cos, db, expenses, frame, Database::getAccountsList(), income, Database::instance(), IncomeRetailEditor::ElementSection::label, listSection(), IncomeRetailEditor::ElementSection::listView, IncomeRetailEditor::ElementSection::topFrame, IncomeRetailEditor::ElementSection::topHBoxLayout, updateAccounts(), and vBoxLayout.
19     : QScrollView(parent,name)
20 {
21     db = Database::instance();
22     
23     setResizePolicy(QScrollView::AutoOneFit);
24     setMargins(5,5,5,5);
25     
26     connect(db, SIGNAL(accountsChanged()), this, SLOT(updateAccounts()));
27     accounts = db->getAccountsList();
28    
29     frame = new QFrame(viewport());
30     vBoxLayout = new QVBoxLayout(frame);
31     
32     income.topFrame = new QFrame(frame);
33     income.topHBoxLayout = new QHBoxLayout(income.topFrame);
34     
35     
36     income.label = new QLabel("<b>Income:</b>", income.topFrame);
37     income.addButton = new QPushButton(
38             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/addElement.png") ),
39             "Add to Income", income.topFrame);
40     connect(income.addButton, SIGNAL(clicked()), this, SLOT(addIncome()));
41 
42     income.topHBoxLayout->addWidget(income.label);
43     income.topHBoxLayout->addStretch();
44     income.topHBoxLayout->addWidget(income.addButton);
45     
46     income.bottomFrame = new QFrame(frame);
47     income.bottomHBoxLayout = new QHBoxLayout(income.bottomFrame);
48     listSection(&income);
49     
50     income.bottomHBoxLayout->addSpacing(5);
51     income.bottomHBoxLayout->addWidget(income.listView);
52     
53     vBoxLayout->addWidget(income.topFrame);
54     vBoxLayout->addSpacing(5);
55 
56     vBoxLayout->addWidget(income.bottomFrame);
57     vBoxLayout->addSpacing(10);
58    
59 
60     cos.topFrame = new QFrame(frame);
61     cos.topHBoxLayout = new QHBoxLayout(cos.topFrame);
62     
63     cos.label = new QLabel("<nobr><b>Cost Of Sales:</b></nobr>", cos.topFrame);
64     cos.addButton = new QPushButton(
65             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/addElement.png") ),
66             "Add to Cost Of Sales", cos.topFrame);
67     connect(cos.addButton, SIGNAL(clicked()), this, SLOT(addCOS()));
68     
69     cos.topHBoxLayout->addWidget(cos.label);
70     cos.topHBoxLayout->addStretch();
71     cos.topHBoxLayout->addWidget(cos.addButton);
72     
73     cos.bottomFrame = new QFrame(frame);
74     cos.bottomHBoxLayout = new QHBoxLayout(cos.bottomFrame);
75     listSection(&cos);
76     
77     cos.bottomHBoxLayout->addSpacing(5);
78     cos.bottomHBoxLayout->addWidget(cos.listView);
79     
80     vBoxLayout->addWidget(cos.topFrame);
81     vBoxLayout->addSpacing(5);
82     vBoxLayout->addWidget(cos.bottomFrame);
83     vBoxLayout->addSpacing(10);
84    
85     expenses.topFrame = new QFrame(frame);
86     expenses.topHBoxLayout = new QHBoxLayout(expenses.topFrame);
87     
88     expenses.label = new QLabel("<b>Expenses:</b>", expenses.topFrame);
89     expenses.addButton = new QPushButton(
90             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/addElement.png") ),
91             "Add to Expenses", expenses.topFrame);
92     connect(expenses.addButton, SIGNAL(clicked()), this, SLOT(addExpenses()));
93     
94     expenses.topHBoxLayout->addWidget(expenses.label);
95     expenses.topHBoxLayout->addStretch();
96     expenses.topHBoxLayout->addWidget(expenses.addButton);
97     
98     expenses.bottomFrame = new QFrame(frame);
99     expenses.bottomHBoxLayout = new QHBoxLayout(expenses.bottomFrame);
100     listSection(&expenses);
101     
102     expenses.bottomHBoxLayout->addSpacing(5);
103     expenses.bottomHBoxLayout->addWidget(expenses.listView);
104     
105     vBoxLayout->addWidget(expenses.topFrame);
106     vBoxLayout->addSpacing(5);
107     vBoxLayout->addWidget(expenses.bottomFrame);
108     
109     vBoxLayout->addStretch();
110     
111     addChild(frame);
112 }
IncomeRetailEditor::~IncomeRetailEditor ()
Definition at line 114 of file incomeRetailEditor.cpp.
References cos, IncomeRetailEditor::ElementSection::elements, expenses, and income.
115 {
116     for(unsigned int i = 0; i < income.elements.size(); i++)
117         delete income.elements[i];
118     income.elements.clear();
119     
120     for(unsigned int i = 0; i < cos.elements.size(); i++)
121         delete cos.elements[i];
122     cos.elements.clear();
123     
124     for(unsigned int i = 0; i < expenses.elements.size(); i++)
125         delete expenses.elements[i];
126     expenses.elements.clear();
127 }
Member Function Documentation
void IncomeRetailEditor::addCOS () [private, slot]
Definition at line 342 of file incomeRetailEditor.cpp.
References addElement(), cos, and updateSection().
Referenced by IncomeRetailEditor().
343 {
344     addElement((int)Database::incomeRetailCOS);
345     updateSection(&cos);
346 }
void IncomeRetailEditor::addElement (int category) [private, slot]
Definition at line 193 of file incomeRetailEditor.cpp.
References accounts, Database::createElement(), db, dialog, oneAccountToggled(), and rangeAccountToggled().
Referenced by addCOS(), addExpenses(), and addIncome().
194 {
195     dialog.main = new QDialog;
196     switch((Database::editorCategories)category)
197     {
198         case Database::incomeRetailIncome:
199             dialog.main->setCaption("Add to Income");
200             break;
201         case Database::incomeRetailCOS:
202             dialog.main->setCaption("Add to Cost Of Sales");
203             break;
204         case Database::incomeRetailExpenses:
205             dialog.main->setCaption("Add to Expenses");
206             break;
207         default:
208             break;
209     }
210     
211     dialog.vBoxLayout = new QVBoxLayout(dialog.main);
212     dialog.vBoxLayout->setMargin(5);
213     dialog.vBoxLayout->setSpacing(5);
214     
215     dialog.oneAccount = new QRadioButton("One Account", dialog.main);
216     connect(dialog.oneAccount, SIGNAL(clicked()), this, SLOT(oneAccountToggled()));
217         
218     dialog.oneAccountFrame = new QFrame(dialog.main);
219     dialog.oneAccountHBoxLayout = new QHBoxLayout(dialog.oneAccountFrame);
220     dialog.oneAccountHBoxLayout->setSpacing(5);
221     
222     dialog.oneAccountHBoxLayout->addSpacing(5);
223     dialog.oneAccountLabel = new QLabel("Account:", dialog.oneAccountFrame);
224     dialog.oneAccountHBoxLayout->addWidget(dialog.oneAccountLabel);
225     dialog.oneAccountEdit = new AccountList(dialog.oneAccountFrame, 0, accounts);
226     dialog.oneAccountHBoxLayout->addWidget(dialog.oneAccountEdit);
227     dialog.oneAccountHBoxLayout->addStretch();
228        
229     dialog.rangeAccount = new QRadioButton("Range of Accounts", dialog.main);
230     connect(dialog.rangeAccount, SIGNAL(clicked()), this, SLOT(rangeAccountToggled()));
231        
232     dialog.rangeAccountFrame = new QFrame(dialog.main, "rangeAccountFrame");
233     dialog.rangeAccountHBoxLayout = new QHBoxLayout(dialog.rangeAccountFrame);
234     dialog.rangeAccountHBoxLayout->addSpacing(5);
235     
236     dialog.rangeAccountFrameList = new QFrame(dialog.rangeAccountFrame);
237     dialog.rangeAccountFrameListVBoxLayout = new QVBoxLayout(dialog.rangeAccountFrameList);
238     dialog.rangeAccountFrameListVBoxLayout->setSpacing(5);
239     
240     dialog.rangeBeginEndFrame = new QFrame(dialog.rangeAccountFrameList);
241     dialog.rangeBeginEndHBoxLayout = new QHBoxLayout(dialog.rangeBeginEndFrame);
242     dialog.rangeBeginEndHBoxLayout->setSpacing(5);
243     
244     dialog.rangeBegin = new QLabel("Begin:", dialog.rangeBeginEndFrame);
245     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBegin);
246     dialog.rangeBeginEdit = new AccountList(dialog.rangeBeginEndFrame, 0, accounts);
247     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBeginEdit);
248     dialog.rangeBetween = new QLabel("to", dialog.rangeBeginEndFrame);
249     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBetween);
250     dialog.rangeEndEdit = new AccountList(dialog.rangeBeginEndFrame, 0, accounts);
251     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeEndEdit);
252     dialog.rangeBeginEndHBoxLayout->addStretch();
253     
254     dialog.rangeDescFrame = new QFrame(dialog.rangeAccountFrameList);
255     dialog.rangeDescFrameHBoxLayout = new QHBoxLayout(dialog.rangeDescFrame);
256     dialog.rangeDescFrameHBoxLayout->setSpacing(5);
257     
258     dialog.rangeDesc = new QLabel("Description:", dialog.rangeDescFrame);
259     dialog.rangeDescFrameHBoxLayout->addWidget(dialog.rangeDesc);
260     dialog.rangeDescEdit = new QLineEdit(dialog.rangeDescFrame);
261     dialog.rangeDescFrameHBoxLayout->addWidget(dialog.rangeDescEdit);
262     
263     dialog.rangeAccountFrameListVBoxLayout->addWidget(dialog.rangeBeginEndFrame);
264     dialog.rangeAccountFrameListVBoxLayout->addWidget(dialog.rangeDescFrame);
265     
266     dialog.rangeAccountHBoxLayout->addWidget(dialog.rangeAccountFrameList);
267     
268         
269     dialog.buttonFrame = new QFrame(dialog.main);
270     dialog.buttonFrameHBoxLayout = new QHBoxLayout(dialog.buttonFrame);
271     dialog.buttonFrameHBoxLayout->setSpacing(5);
272     dialog.buttonFrameHBoxLayout->addStretch();
273     
274     dialog.ok = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/addElement.png")),
275             "Add", dialog.buttonFrame);
276     connect(dialog.ok, SIGNAL(clicked()), dialog.main, SLOT(accept()));
277     dialog.buttonFrameHBoxLayout->addWidget(dialog.ok);
278     
279     dialog.cancel = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")),
280             "Cancel", dialog.buttonFrame);
281     connect(dialog.cancel, SIGNAL(clicked()), dialog.main, SLOT(reject()));
282     dialog.buttonFrameHBoxLayout->addWidget(dialog.cancel);
283     
284     
285     dialog.vBoxLayout->addWidget(dialog.oneAccount);
286     dialog.vBoxLayout->addWidget(dialog.oneAccountFrame);
287     dialog.vBoxLayout->addWidget(dialog.rangeAccount);
288     dialog.vBoxLayout->addWidget(dialog.rangeAccountFrame);
289     dialog.vBoxLayout->addSpacing(10);
290     dialog.vBoxLayout->addWidget(dialog.buttonFrame);
291     
292     oneAccountToggled();
293     
294     if(dialog.main->exec())
295     {
296         if(dialog.oneAccount->isChecked())
297             db->createElement((Database::editorCategories)category,
298                                       "0", "", dialog.oneAccountEdit->accountNumber(), "");
299         else
300             db->createElement((Database::editorCategories)category,
301                                       "1", dialog.rangeDescEdit->text(),
302                                       dialog.rangeBeginEdit->accountNumber(), dialog.rangeEndEdit->accountNumber());
303     }
304     
305     delete dialog.main;
306 }
void IncomeRetailEditor::addExpenses () [private, slot]
Definition at line 348 of file incomeRetailEditor.cpp.
References addElement(), expenses, and updateSection().
Referenced by IncomeRetailEditor().
349 {
350     addElement((int)Database::incomeRetailExpenses);
351     updateSection(&expenses);
352 }
void IncomeRetailEditor::addIncome () [private, slot]
Definition at line 336 of file incomeRetailEditor.cpp.
References addElement(), income, and updateSection().
Referenced by IncomeRetailEditor().
337 {
338     addElement((int)Database::incomeRetailIncome);
339     updateSection(&income);
340 }
void IncomeRetailEditor::deleteSection (ElementSection * section) [private]
Definition at line 158 of file incomeRetailEditor.cpp.
References IncomeRetailEditor::ElementSection::elements, IncomeRetailEditor::ElementSection::listView, and IncomeRetailEditor::ElementSection::vBoxLayout.
Referenced by updateSection().
159 {
160     if(section->elements.size())
161     {
162         for(unsigned int i = 0; i < section->elements.size(); i++)
163             delete section->elements[i];
164         section->elements.clear();
165         delete section->vBoxLayout;
166     }
167     delete section->listView;
168 }
void IncomeRetailEditor::listSection (ElementSection * section) [private]
Definition at line 129 of file incomeRetailEditor.cpp.
References IncomeRetailEditor::ElementSection::bottomFrame, cos, db, IncomeRetailEditor::ElementSection::elements, expenses, Database::getElements(), EditorElement::getFrame(), income, IncomeRetailEditor::ElementSection::listView, updateSection(), and IncomeRetailEditor::ElementSection::vBoxLayout.
Referenced by IncomeRetailEditor(), and updateSection().
130 {
131     QPtrList<EditorElement> list;
132     if(section == &income)
133         list = db->getElements(Database::incomeRetailIncome);
134     if(section == &cos)
135         list = db->getElements(Database::incomeRetailCOS);
136     if(section == &expenses)
137         list = db->getElements(Database::incomeRetailExpenses);
138     
139     if(!list.isEmpty())
140     {
141         section->listView = new QFrame(section->bottomFrame);
142         section->vBoxLayout = new QVBoxLayout(section->listView);
143         
144         EditorElement *element;
145         
146         for(element = list.first(); element; element = list.next())
147         {
148             connect(element, SIGNAL(changed(void*)), this, SLOT(updateSection(void*)));
149             section->elements.push_back(element);
150             section->vBoxLayout->addWidget(element->getFrame(section->listView, (void*)section));
151         }
152     }
153     else
154         section->listView = new QLabel("No Entries", section->bottomFrame);
155     
156 }
void IncomeRetailEditor::oneAccountToggled () [private, slot]
Definition at line 308 of file incomeRetailEditor.cpp.
References dialog.
Referenced by addElement().
309 {
310     dialog.oneAccount->setChecked(true);
311     dialog.rangeAccount->setChecked(false);
312     dialog.oneAccountLabel->setEnabled(true);
313     dialog.oneAccountEdit->setEnabled(true);
314     dialog.rangeBegin->setEnabled(false);
315     dialog.rangeBeginEdit->setEnabled(false);
316     dialog.rangeBetween->setEnabled(false);
317     dialog.rangeEndEdit->setEnabled(false);
318     dialog.rangeDesc->setEnabled(false);
319     dialog.rangeDescEdit->setEnabled(false);
320 }
void IncomeRetailEditor::rangeAccountToggled () [private, slot]
Definition at line 322 of file incomeRetailEditor.cpp.
References dialog.
Referenced by addElement().
323 {
324     dialog.rangeAccount->setChecked(true);
325     dialog.oneAccount->setChecked(false);
326     dialog.oneAccountLabel->setEnabled(false);
327     dialog.oneAccountEdit->setEnabled(false);
328     dialog.rangeBegin->setEnabled(true);
329     dialog.rangeBeginEdit->setEnabled(true);
330     dialog.rangeBetween->setEnabled(true);
331     dialog.rangeEndEdit->setEnabled(true);
332     dialog.rangeDesc->setEnabled(true);
333     dialog.rangeDescEdit->setEnabled(true);
334 }
void IncomeRetailEditor::updateAccounts () [private, slot]
Definition at line 354 of file incomeRetailEditor.cpp.
References accounts, db, and Database::getAccountsList().
Referenced by IncomeRetailEditor().
355 {
356     accounts = db->getAccountsList();
357 }
void IncomeRetailEditor::updateSection (void *) [private, slot]
Definition at line 170 of file incomeRetailEditor.cpp.
References IncomeRetailEditor::ElementSection::bottomHBoxLayout, cos, deleteSection(), expenses, income, listSection(), and IncomeRetailEditor::ElementSection::listView.
Referenced by addCOS(), addExpenses(), addIncome(), and listSection().
171 {
172     ElementSection *section = (ElementSection*)newSection;
173     deleteSection(section);
174     listSection(section);
175     
176     if(section == &income) 
177     {
178         income.bottomHBoxLayout->addWidget(income.listView);
179         income.listView->show();
180     }
181     if(section == &cos) 
182     {
183         cos.bottomHBoxLayout->addWidget(cos.listView);
184         cos.listView->show();
185     }
186     if(section == &expenses) 
187     {
188         expenses.bottomHBoxLayout->addWidget(expenses.listView);
189         expenses.listView->show();
190     }
191 }
Member Data Documentation
QStringList IncomeRetailEditor::accounts [private]
Definition at line 43 of file incomeRetailEditor.h.
Referenced by addElement(), IncomeRetailEditor(), and updateAccounts().
QFrame* IncomeRetailEditor::buttonFrame [private]
Definition at line 86 of file incomeRetailEditor.h.
QHBoxLayout* IncomeRetailEditor::buttonFrameHBoxLayout [private]
Definition at line 87 of file incomeRetailEditor.h.
QPushButton* IncomeRetailEditor::cancel [private]
Definition at line 89 of file incomeRetailEditor.h.
struct IncomeRetailEditor::ElementSection IncomeRetailEditor::cos [private]
Referenced by addCOS(), IncomeRetailEditor(), listSection(), updateSection(), and ~IncomeRetailEditor().
Database* IncomeRetailEditor::db [private]
Definition at line 41 of file incomeRetailEditor.h.
Referenced by addElement(), IncomeRetailEditor(), listSection(), and updateAccounts().
struct { ... } IncomeRetailEditor::dialog [private]
Referenced by addElement(), oneAccountToggled(), and rangeAccountToggled().
struct IncomeRetailEditor::ElementSection IncomeRetailEditor::expenses [private]
Referenced by addExpenses(), IncomeRetailEditor(), listSection(), updateSection(), and ~IncomeRetailEditor().
QFrame* IncomeRetailEditor::frame [private]
Definition at line 45 of file incomeRetailEditor.h.
Referenced by IncomeRetailEditor().
struct IncomeRetailEditor::ElementSection IncomeRetailEditor::income [private]
Referenced by addIncome(), IncomeRetailEditor(), listSection(), updateSection(), and ~IncomeRetailEditor().
QDialog* IncomeRetailEditor::main [private]
Definition at line 64 of file incomeRetailEditor.h.
QPushButton* IncomeRetailEditor::ok [private]
Definition at line 88 of file incomeRetailEditor.h.
QRadioButton* IncomeRetailEditor::oneAccount [private]
Definition at line 66 of file incomeRetailEditor.h.
AccountList* IncomeRetailEditor::oneAccountEdit [private]
Definition at line 70 of file incomeRetailEditor.h.
QFrame* IncomeRetailEditor::oneAccountFrame [private]
Definition at line 67 of file incomeRetailEditor.h.
QHBoxLayout* IncomeRetailEditor::oneAccountHBoxLayout [private]
Definition at line 68 of file incomeRetailEditor.h.
QLabel* IncomeRetailEditor::oneAccountLabel [private]
Definition at line 69 of file incomeRetailEditor.h.
QRadioButton* IncomeRetailEditor::rangeAccount [private]
Definition at line 71 of file incomeRetailEditor.h.
QFrame* IncomeRetailEditor::rangeAccountFrame [private]
Definition at line 72 of file incomeRetailEditor.h.
QFrame* IncomeRetailEditor::rangeAccountFrameList [private]
Definition at line 74 of file incomeRetailEditor.h.
QVBoxLayout* IncomeRetailEditor::rangeAccountFrameListVBoxLayout [private]
Definition at line 75 of file incomeRetailEditor.h.
QHBoxLayout* IncomeRetailEditor::rangeAccountHBoxLayout [private]
Definition at line 73 of file incomeRetailEditor.h.
QLabel* IncomeRetailEditor::rangeBegin [private]
Definition at line 78 of file incomeRetailEditor.h.
AccountList* IncomeRetailEditor::rangeBeginEdit [private]
Definition at line 79 of file incomeRetailEditor.h.
QFrame* IncomeRetailEditor::rangeBeginEndFrame [private]
Definition at line 76 of file incomeRetailEditor.h.
QHBoxLayout* IncomeRetailEditor::rangeBeginEndHBoxLayout [private]
Definition at line 77 of file incomeRetailEditor.h.
QLabel* IncomeRetailEditor::rangeBetween [private]
Definition at line 80 of file incomeRetailEditor.h.
QLabel* IncomeRetailEditor::rangeDesc [private]
Definition at line 84 of file incomeRetailEditor.h.
QLineEdit* IncomeRetailEditor::rangeDescEdit [private]
Definition at line 85 of file incomeRetailEditor.h.
QFrame* IncomeRetailEditor::rangeDescFrame [private]
Definition at line 82 of file incomeRetailEditor.h.
QHBoxLayout* IncomeRetailEditor::rangeDescFrameHBoxLayout [private]
Definition at line 83 of file incomeRetailEditor.h.
AccountList* IncomeRetailEditor::rangeEndEdit [private]
Definition at line 81 of file incomeRetailEditor.h.
QVBoxLayout* IncomeRetailEditor::vBoxLayout [private]
Definition at line 65 of file incomeRetailEditor.h.
QVBoxLayout* IncomeRetailEditor::vBoxLayout [private]
Definition at line 46 of file incomeRetailEditor.h.
Referenced by IncomeRetailEditor().
The documentation for this class was generated from the following files:
incomeRetailEditor.h
incomeRetailEditor.cpp