Printer Class Reference
#include <printer.h>
Public Member Functions
void destroy ()
void printReport (const QString &header, const QString &data)
Static Public Member Functions
Printer * instance ()
Private Member Functions
Printer ()
~Printer ()
Private Attributes
Settings * settings
Static Private Attributes
Printer * printer = 0
Constructor & Destructor Documentation
Printer::Printer () [private]
Definition at line 17 of file printer.cpp.
References Settings::getPrinterColorMode(), Settings::getPrinterOrientation(), Settings::getPrinterOutputFileName(), Settings::getPrinterOutputToFile(), Settings::getPrinterPageOrder(), Settings::getPrinterPageSize(), Settings::getPrinterPaperSource(), Settings::getPrinterPrinterName(), Settings::getPrinterPrintProgram(), Settings::instance(), and settings.
17                  : QPrinter(QPrinter::HighResolution)
18 {
19     settings = Settings::instance();
20     setPrinterName(settings->getPrinterPrinterName());
21     setOutputToFile(settings->getPrinterOutputToFile());
22     setOutputFileName(settings->getPrinterOutputFileName());
23     setPrintProgram(settings->getPrinterPrintProgram());
24     setOrientation(settings->getPrinterOrientation());
25     setPageSize(settings->getPrinterPageSize());
26     setPageOrder(settings->getPrinterPageOrder());
27     setColorMode(settings->getPrinterColorMode());
28     setPaperSource(settings->getPrinterPaperSource());
29 }
Printer::~Printer () [private]
Definition at line 31 of file printer.cpp.
References Settings::setPrinterColorMode(), Settings::setPrinterOrientation(), Settings::setPrinterOutputFileName(), Settings::setPrinterOutputToFile(), Settings::setPrinterPageOrder(), Settings::setPrinterPageSize(), Settings::setPrinterPaperSource(), Settings::setPrinterPrinterName(), Settings::setPrinterPrintProgram(), and settings.
32 {
33     settings->setPrinterPrinterName(printerName());
34     settings->setPrinterOutputToFile(outputToFile());
35     settings->setPrinterOutputFileName(outputFileName());
36     settings->setPrinterPrintProgram(printProgram());
37     settings->setPrinterOrientation(orientation());
38     settings->setPrinterPageSize(pageSize());
39     settings->setPrinterPageOrder(pageOrder());
40     settings->setPrinterColorMode(colorMode());
41     settings->setPrinterPaperSource(paperSource());
42 }
Member Function Documentation
void Printer::destroy ()
Definition at line 51 of file printer.cpp.
References printer.
Referenced by main().
52 {
53     if(printer != 0)
54         delete printer;
55 }
Printer * Printer::instance () [static]
Definition at line 44 of file printer.cpp.
References printer.
Referenced by JournalStack::JournalStack(), main(), and ReportStack::ReportStack().
45 {
46     if(printer == 0)
47         printer = new Printer;
48     return printer;
49 }
void Printer::printReport (const QString & header, const QString & data)
Definition at line 57 of file printer.cpp.
Referenced by JournalStack::printJournal().
58 {
59     if(setup(0))
60     {
61 
62         QPainter painter(this);
63 
64         QPaintDeviceMetrics metrics(this);
65         int headerGap = metrics.logicalDpiY() / 4;  // quarter inch
66 
67         QFont headerFont("Verdana", 8);
68         QFont dataFont("Verdana", 8);
69     
70         QSimpleRichText headerText(header, headerFont);
71     
72         headerText.setWidth(&painter, painter.window().width());
73 
74         int pageHeight = painter.window().height() - headerText.height() - headerGap;
75 
76         QSimpleRichText dataText(data, dataFont, "", 0, 0, pageHeight);
77         dataText.setWidth(&painter, painter.window().width());
78 
79         int numPages = (int)ceil((double)dataText.height() / pageHeight);
80 
81         int index;
82 
83         for(int i = 0; i < (int)numCopies(); ++i)
84         {
85             for(int j = 0; j < numPages; ++j)
86             {
87                 if(i > 0 || j > 0)
88                     newPage();
89 
90                 if(pageOrder() == QPrinter::LastPageFirst)
91                     index = numPages - j - 1;
92                 else
93                     index = j;
94 
95                 QRect headerRect(0, 0, headerText.width(), headerText.height());
96 
97                 QRect dataRect(0, (index * pageHeight), dataText.width(), pageHeight);
98             
99 
100                 headerText.draw(&painter, 0, 0, headerRect, QColorGroup());
101 
102                 painter.save();
103                 painter.translate(0, -dataRect.top() + headerText.height());
104                 dataText.draw(&painter, 0, 0, dataRect, QColorGroup());
105                 painter.restore();
106 
107                 painter.setFont(dataFont);
108                 painter.drawText(painter.window(), Qt::AlignHCenter | Qt::AlignBottom,
109                                  QString("Page " + QString::number(j + 1) + " of " + QString::number(numPages)));
110 
111             }
112         }
113     }
114 }
Member Data Documentation
Printer * Printer::printer = 0 [static, private]
Definition at line 116 of file printer.cpp.
Referenced by destroy(), and instance().
Settings* Printer::settings [private]
Definition at line 23 of file printer.h.
Referenced by Printer(), and ~Printer().
The documentation for this class was generated from the following files:
printer.h
printer.cpp