IncomeSvcEditor Class Reference
#include <incomeSvcEditor.h>
Public Member Functions
IncomeSvcEditor (QWidget *parent=0, const char *name=0)
~IncomeSvcEditor ()
Private Slots
void updateSection (void *)
void addElement (int category)
void addIncome ()
void addExpenses ()
void oneAccountToggled ()
void rangeAccountToggled ()
void updateAccounts ()
Private Member Functions
void listSection (ElementSection *section)
void deleteSection (ElementSection *section)
Private Attributes
Database * db
QStringList accounts
QFrame * frame
QVBoxLayout * vBoxLayout
IncomeSvcEditor::ElementSection income
IncomeSvcEditor::ElementSection expenses
xx xx xx xx xx xx xx xx xx
struct {
 QDialog * main
 QVBoxLayout * vBoxLayout
 QRadioButton * oneAccount
 QFrame * oneAccountFrame
 QHBoxLayout * oneAccountHBoxLayout
 QLabel * oneAccountLabel
 AccountList * oneAccountEdit
 QRadioButton * rangeAccount
 QFrame * rangeAccountFrame
 QHBoxLayout * rangeAccountHBoxLayout
 QFrame * rangeAccountFrameList
 QVBoxLayout * rangeAccountFrameListVBoxLayout
 QFrame * rangeBeginEndFrame
 QHBoxLayout * rangeBeginEndHBoxLayout
 QLabel * rangeBegin
 AccountList * rangeBeginEdit
 QLabel * rangeBetween
 AccountList * rangeEndEdit
 QFrame * rangeDescFrame
 QHBoxLayout * rangeDescFrameHBoxLayout
 QLabel * rangeDesc
 QLineEdit * rangeDescEdit
 QFrame * buttonFrame
 QHBoxLayout * buttonFrameHBoxLayout
 QPushButton * ok
 QPushButton * cancel
} dialog
Constructor & Destructor Documentation
IncomeSvcEditor::IncomeSvcEditor (QWidget * parent = 0, const char * name = 0)
Definition at line 19 of file incomeSvcEditor.cpp.
References accounts, IncomeSvcEditor::ElementSection::addButton, addExpenses(), addIncome(), IncomeSvcEditor::ElementSection::bottomFrame, IncomeSvcEditor::ElementSection::bottomHBoxLayout, db, expenses, frame, Database::getAccountsList(), income, Database::instance(), IncomeSvcEditor::ElementSection::label, listSection(), IncomeSvcEditor::ElementSection::listView, IncomeSvcEditor::ElementSection::topFrame, IncomeSvcEditor::ElementSection::topHBoxLayout, updateAccounts(), and vBoxLayout.
20     : QScrollView(parent,name)
21 {
22     db = Database::instance();
23     
24     setResizePolicy(QScrollView::AutoOneFit);
25     setMargins(5,5,5,5);
26     
27     connect(db, SIGNAL(accountsChanged()), this, SLOT(updateAccounts()));
28     accounts = db->getAccountsList();
29    
30     frame = new QFrame(viewport());
31     vBoxLayout = new QVBoxLayout(frame);
32     
33     income.topFrame = new QFrame(frame);
34     income.topHBoxLayout = new QHBoxLayout(income.topFrame);
35     
36     
37     income.label = new QLabel("<b>Income:</b>", income.topFrame);
38     income.addButton = new QPushButton(
39             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/addElement.png") ),
40             "Add to Income", income.topFrame);
41     connect(income.addButton, SIGNAL(clicked()), this, SLOT(addIncome()));
42 
43     income.topHBoxLayout->addWidget(income.label);
44     income.topHBoxLayout->addStretch();
45     income.topHBoxLayout->addWidget(income.addButton);
46     
47     income.bottomFrame = new QFrame(frame);
48     income.bottomHBoxLayout = new QHBoxLayout(income.bottomFrame);
49     listSection(&income);
50     
51     income.bottomHBoxLayout->addSpacing(5);
52     income.bottomHBoxLayout->addWidget(income.listView);
53     
54     vBoxLayout->addWidget(income.topFrame);
55     vBoxLayout->addSpacing(5);
56 
57     vBoxLayout->addWidget(income.bottomFrame);
58     vBoxLayout->addSpacing(10);
59    
60 
61     expenses.topFrame = new QFrame(frame);
62     expenses.topHBoxLayout = new QHBoxLayout(expenses.topFrame);
63     
64     expenses.label = new QLabel("<b>Expenses:</b>", expenses.topFrame);
65     expenses.addButton = new QPushButton(
66             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/addElement.png") ),
67             "Add to Expenses", expenses.topFrame);
68     connect(expenses.addButton, SIGNAL(clicked()), this, SLOT(addExpenses()));
69     
70     expenses.topHBoxLayout->addWidget(expenses.label);
71     expenses.topHBoxLayout->addStretch();
72     expenses.topHBoxLayout->addWidget(expenses.addButton);
73     
74     expenses.bottomFrame = new QFrame(frame);
75     expenses.bottomHBoxLayout = new QHBoxLayout(expenses.bottomFrame);
76     listSection(&expenses);
77     
78     expenses.bottomHBoxLayout->addSpacing(5);
79     expenses.bottomHBoxLayout->addWidget(expenses.listView);
80     
81     vBoxLayout->addWidget(expenses.topFrame);
82     vBoxLayout->addSpacing(5);
83     vBoxLayout->addWidget(expenses.bottomFrame);
84     
85     vBoxLayout->addStretch();
86     
87     addChild(frame);
88 }
IncomeSvcEditor::~IncomeSvcEditor ()
Definition at line 90 of file incomeSvcEditor.cpp.
References IncomeSvcEditor::ElementSection::elements, expenses, and income.
91 {
92     for(unsigned int i = 0; i < income.elements.size(); i++)
93         delete income.elements[i];
94     income.elements.clear();
95     
96     for(unsigned int i = 0; i < expenses.elements.size(); i++)
97         delete expenses.elements[i];
98     expenses.elements.clear();
99 }
Member Function Documentation
void IncomeSvcEditor::addElement (int category) [private, slot]
Definition at line 158 of file incomeSvcEditor.cpp.
References accounts, Database::createElement(), db, dialog, oneAccountToggled(), and rangeAccountToggled().
Referenced by addExpenses(), and addIncome().
159 {
160     dialog.main = new QDialog;
161     switch((Database::editorCategories)category)
162     {
163         case Database::incomeSvcIncome:
164             dialog.main->setCaption("Add to Income");
165             break;
166         case Database::incomeSvcExpenses:
167             dialog.main->setCaption("Add to Expenses");
168             break;
169         default:
170             break;
171     }
172     
173     dialog.vBoxLayout = new QVBoxLayout(dialog.main);
174     dialog.vBoxLayout->setMargin(5);
175     dialog.vBoxLayout->setSpacing(5);
176     
177     dialog.oneAccount = new QRadioButton("One Account", dialog.main);
178     connect(dialog.oneAccount, SIGNAL(clicked()), this, SLOT(oneAccountToggled()));
179         
180     dialog.oneAccountFrame = new QFrame(dialog.main);
181     dialog.oneAccountHBoxLayout = new QHBoxLayout(dialog.oneAccountFrame);
182     dialog.oneAccountHBoxLayout->setSpacing(5);
183     
184     dialog.oneAccountHBoxLayout->addSpacing(5);
185     dialog.oneAccountLabel = new QLabel("Account:", dialog.oneAccountFrame);
186     dialog.oneAccountHBoxLayout->addWidget(dialog.oneAccountLabel);
187     dialog.oneAccountEdit = new AccountList(dialog.oneAccountFrame, 0, accounts);
188     dialog.oneAccountHBoxLayout->addWidget(dialog.oneAccountEdit);
189     dialog.oneAccountHBoxLayout->addStretch();
190        
191     dialog.rangeAccount = new QRadioButton("Range of Accounts", dialog.main);
192     connect(dialog.rangeAccount, SIGNAL(clicked()), this, SLOT(rangeAccountToggled()));
193        
194     dialog.rangeAccountFrame = new QFrame(dialog.main, "rangeAccountFrame");
195     dialog.rangeAccountHBoxLayout = new QHBoxLayout(dialog.rangeAccountFrame);
196     dialog.rangeAccountHBoxLayout->addSpacing(5);
197     
198     dialog.rangeAccountFrameList = new QFrame(dialog.rangeAccountFrame);
199     dialog.rangeAccountFrameListVBoxLayout = new QVBoxLayout(dialog.rangeAccountFrameList);
200     dialog.rangeAccountFrameListVBoxLayout->setSpacing(5);
201     
202     dialog.rangeBeginEndFrame = new QFrame(dialog.rangeAccountFrameList);
203     dialog.rangeBeginEndHBoxLayout = new QHBoxLayout(dialog.rangeBeginEndFrame);
204     dialog.rangeBeginEndHBoxLayout->setSpacing(5);
205     
206     dialog.rangeBegin = new QLabel("Begin:", dialog.rangeBeginEndFrame);
207     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBegin);
208     dialog.rangeBeginEdit = new AccountList(dialog.rangeBeginEndFrame, 0, accounts);
209     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBeginEdit);
210     dialog.rangeBetween = new QLabel("to", dialog.rangeBeginEndFrame);
211     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeBetween);
212     dialog.rangeEndEdit = new AccountList(dialog.rangeBeginEndFrame, 0, accounts);
213     dialog.rangeBeginEndHBoxLayout->addWidget(dialog.rangeEndEdit);
214     dialog.rangeBeginEndHBoxLayout->addStretch();
215     
216     dialog.rangeDescFrame = new QFrame(dialog.rangeAccountFrameList);
217     dialog.rangeDescFrameHBoxLayout = new QHBoxLayout(dialog.rangeDescFrame);
218     dialog.rangeDescFrameHBoxLayout->setSpacing(5);
219     
220     dialog.rangeDesc = new QLabel("Description:", dialog.rangeDescFrame);
221     dialog.rangeDescFrameHBoxLayout->addWidget(dialog.rangeDesc);
222     dialog.rangeDescEdit = new QLineEdit(dialog.rangeDescFrame);
223     dialog.rangeDescFrameHBoxLayout->addWidget(dialog.rangeDescEdit);
224     
225     dialog.rangeAccountFrameListVBoxLayout->addWidget(dialog.rangeBeginEndFrame);
226     dialog.rangeAccountFrameListVBoxLayout->addWidget(dialog.rangeDescFrame);
227     
228     dialog.rangeAccountHBoxLayout->addWidget(dialog.rangeAccountFrameList);
229     
230         
231     dialog.buttonFrame = new QFrame(dialog.main);
232     dialog.buttonFrameHBoxLayout = new QHBoxLayout(dialog.buttonFrame);
233     dialog.buttonFrameHBoxLayout->setSpacing(5);
234     dialog.buttonFrameHBoxLayout->addStretch();
235     
236     dialog.ok = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/addElement.png")),
237             "Add", dialog.buttonFrame);
238     connect(dialog.ok, SIGNAL(clicked()), dialog.main, SLOT(accept()));
239     dialog.buttonFrameHBoxLayout->addWidget(dialog.ok);
240     
241     dialog.cancel = new QPushButton(QIconSet(QPixmap::fromMimeSource(ICON_PATH + "/cancelButton.png")),
242             "Cancel", dialog.buttonFrame);
243     connect(dialog.cancel, SIGNAL(clicked()), dialog.main, SLOT(reject()));
244     dialog.buttonFrameHBoxLayout->addWidget(dialog.cancel);
245     
246     
247     dialog.vBoxLayout->addWidget(dialog.oneAccount);
248     dialog.vBoxLayout->addWidget(dialog.oneAccountFrame);
249     dialog.vBoxLayout->addWidget(dialog.rangeAccount);
250     dialog.vBoxLayout->addWidget(dialog.rangeAccountFrame);
251     dialog.vBoxLayout->addSpacing(10);
252     dialog.vBoxLayout->addWidget(dialog.buttonFrame);
253     
254     oneAccountToggled();
255     
256     if(dialog.main->exec())
257     {
258         if(dialog.oneAccount->isChecked())
259             db->createElement((Database::editorCategories)category,
260                                       "0", "", dialog.oneAccountEdit->accountNumber(), "");
261         else
262             db->createElement((Database::editorCategories)category,
263                                       "1", dialog.rangeDescEdit->text(),
264                                       dialog.rangeBeginEdit->accountNumber(), dialog.rangeEndEdit->accountNumber());
265     }
266     
267     delete dialog.main;
268 }
void IncomeSvcEditor::addExpenses () [private, slot]
Definition at line 304 of file incomeSvcEditor.cpp.
References addElement(), expenses, and updateSection().
Referenced by IncomeSvcEditor().
305 {
306     addElement((int)Database::incomeSvcExpenses);
307     updateSection(&expenses);
308 }
void IncomeSvcEditor::addIncome () [private, slot]
Definition at line 298 of file incomeSvcEditor.cpp.
References addElement(), income, and updateSection().
Referenced by IncomeSvcEditor().
299 {
300     addElement((int)Database::incomeSvcIncome);
301     updateSection(&income);
302 }
void IncomeSvcEditor::deleteSection (ElementSection * section) [private]
Definition at line 128 of file incomeSvcEditor.cpp.
References IncomeSvcEditor::ElementSection::elements, IncomeSvcEditor::ElementSection::listView, and IncomeSvcEditor::ElementSection::vBoxLayout.
Referenced by updateSection().
129 {
130     if(section->elements.size())
131     {
132         for(unsigned int i = 0; i < section->elements.size(); i++)
133             delete section->elements[i];
134         section->elements.clear();
135         delete section->vBoxLayout;
136     }
137     delete section->listView;
138 }
void IncomeSvcEditor::listSection (ElementSection * section) [private]
Definition at line 101 of file incomeSvcEditor.cpp.
References IncomeSvcEditor::ElementSection::bottomFrame, db, IncomeSvcEditor::ElementSection::elements, expenses, Database::getElements(), EditorElement::getFrame(), income, IncomeSvcEditor::ElementSection::listView, updateSection(), and IncomeSvcEditor::ElementSection::vBoxLayout.
Referenced by IncomeSvcEditor(), and updateSection().
102 {
103     QPtrList<EditorElement> list;
104     if(section == &income)
105         list = db->getElements(Database::incomeSvcIncome);
106     if(section == &expenses)
107         list = db->getElements(Database::incomeSvcExpenses);
108     
109     if(!list.isEmpty())
110     {
111         section->listView = new QFrame(section->bottomFrame);
112         section->vBoxLayout = new QVBoxLayout(section->listView);
113         
114         EditorElement *element;
115         
116         for(element = list.first(); element; element = list.next())
117         {
118             connect(element, SIGNAL(changed(void*)), this, SLOT(updateSection(void*)));
119             section->elements.push_back(element);
120             section->vBoxLayout->addWidget(element->getFrame(section->listView, (void*)section));
121         }
122     }
123     else
124         section->listView = new QLabel("No Entries", section->bottomFrame);
125     
126 }
void IncomeSvcEditor::oneAccountToggled () [private, slot]
Definition at line 270 of file incomeSvcEditor.cpp.
References dialog.
Referenced by addElement().
271 {
272     dialog.oneAccount->setChecked(true);
273     dialog.rangeAccount->setChecked(false);
274     dialog.oneAccountLabel->setEnabled(true);
275     dialog.oneAccountEdit->setEnabled(true);
276     dialog.rangeBegin->setEnabled(false);
277     dialog.rangeBeginEdit->setEnabled(false);
278     dialog.rangeBetween->setEnabled(false);
279     dialog.rangeEndEdit->setEnabled(false);
280     dialog.rangeDesc->setEnabled(false);
281     dialog.rangeDescEdit->setEnabled(false);
282 }
void IncomeSvcEditor::rangeAccountToggled () [private, slot]
Definition at line 284 of file incomeSvcEditor.cpp.
References dialog.
Referenced by addElement().
285 {
286     dialog.rangeAccount->setChecked(true);
287     dialog.oneAccount->setChecked(false);
288     dialog.oneAccountLabel->setEnabled(false);
289     dialog.oneAccountEdit->setEnabled(false);
290     dialog.rangeBegin->setEnabled(true);
291     dialog.rangeBeginEdit->setEnabled(true);
292     dialog.rangeBetween->setEnabled(true);
293     dialog.rangeEndEdit->setEnabled(true);
294     dialog.rangeDesc->setEnabled(true);
295     dialog.rangeDescEdit->setEnabled(true);
296 }
void IncomeSvcEditor::updateAccounts () [private, slot]
Definition at line 310 of file incomeSvcEditor.cpp.
References accounts, db, and Database::getAccountsList().
Referenced by IncomeSvcEditor().
311 {
312     accounts = db->getAccountsList();
313 }
void IncomeSvcEditor::updateSection (void *) [private, slot]
Definition at line 140 of file incomeSvcEditor.cpp.
References IncomeSvcEditor::ElementSection::bottomHBoxLayout, deleteSection(), expenses, income, listSection(), and IncomeSvcEditor::ElementSection::listView.
Referenced by addExpenses(), addIncome(), and listSection().
141 {
142     ElementSection *section = (ElementSection*)newSection;
143     deleteSection(section);
144     listSection(section);
145     
146     if(section == &income) 
147     {
148         income.bottomHBoxLayout->addWidget(income.listView);
149         income.listView->show();
150     }
151     if(section == &expenses) 
152     {
153         expenses.bottomHBoxLayout->addWidget(expenses.listView);
154         expenses.listView->show();
155     }
156 }
Member Data Documentation
QStringList IncomeSvcEditor::accounts [private]
Definition at line 42 of file incomeSvcEditor.h.
Referenced by addElement(), IncomeSvcEditor(), and updateAccounts().
QFrame* IncomeSvcEditor::buttonFrame [private]
Definition at line 85 of file incomeSvcEditor.h.
QHBoxLayout* IncomeSvcEditor::buttonFrameHBoxLayout [private]
Definition at line 86 of file incomeSvcEditor.h.
QPushButton* IncomeSvcEditor::cancel [private]
Definition at line 88 of file incomeSvcEditor.h.
Database* IncomeSvcEditor::db [private]
Definition at line 40 of file incomeSvcEditor.h.
Referenced by addElement(), IncomeSvcEditor(), listSection(), and updateAccounts().
struct { ... } IncomeSvcEditor::dialog [private]
Referenced by addElement(), oneAccountToggled(), and rangeAccountToggled().
struct IncomeSvcEditor::ElementSection IncomeSvcEditor::expenses [private]
Referenced by addExpenses(), IncomeSvcEditor(), listSection(), updateSection(), and ~IncomeSvcEditor().
QFrame* IncomeSvcEditor::frame [private]
Definition at line 44 of file incomeSvcEditor.h.
Referenced by IncomeSvcEditor().
struct IncomeSvcEditor::ElementSection IncomeSvcEditor::income [private]
Referenced by addIncome(), IncomeSvcEditor(), listSection(), updateSection(), and ~IncomeSvcEditor().
QDialog* IncomeSvcEditor::main [private]
Definition at line 63 of file incomeSvcEditor.h.
QPushButton* IncomeSvcEditor::ok [private]
Definition at line 87 of file incomeSvcEditor.h.
QRadioButton* IncomeSvcEditor::oneAccount [private]
Definition at line 65 of file incomeSvcEditor.h.
AccountList* IncomeSvcEditor::oneAccountEdit [private]
Definition at line 69 of file incomeSvcEditor.h.
QFrame* IncomeSvcEditor::oneAccountFrame [private]
Definition at line 66 of file incomeSvcEditor.h.
QHBoxLayout* IncomeSvcEditor::oneAccountHBoxLayout [private]
Definition at line 67 of file incomeSvcEditor.h.
QLabel* IncomeSvcEditor::oneAccountLabel [private]
Definition at line 68 of file incomeSvcEditor.h.
QRadioButton* IncomeSvcEditor::rangeAccount [private]
Definition at line 70 of file incomeSvcEditor.h.
QFrame* IncomeSvcEditor::rangeAccountFrame [private]
Definition at line 71 of file incomeSvcEditor.h.
QFrame* IncomeSvcEditor::rangeAccountFrameList [private]
Definition at line 73 of file incomeSvcEditor.h.
QVBoxLayout* IncomeSvcEditor::rangeAccountFrameListVBoxLayout [private]
Definition at line 74 of file incomeSvcEditor.h.
QHBoxLayout* IncomeSvcEditor::rangeAccountHBoxLayout [private]
Definition at line 72 of file incomeSvcEditor.h.
QLabel* IncomeSvcEditor::rangeBegin [private]
Definition at line 77 of file incomeSvcEditor.h.
AccountList* IncomeSvcEditor::rangeBeginEdit [private]
Definition at line 78 of file incomeSvcEditor.h.
QFrame* IncomeSvcEditor::rangeBeginEndFrame [private]
Definition at line 75 of file incomeSvcEditor.h.
QHBoxLayout* IncomeSvcEditor::rangeBeginEndHBoxLayout [private]
Definition at line 76 of file incomeSvcEditor.h.
QLabel* IncomeSvcEditor::rangeBetween [private]
Definition at line 79 of file incomeSvcEditor.h.
QLabel* IncomeSvcEditor::rangeDesc [private]
Definition at line 83 of file incomeSvcEditor.h.
QLineEdit* IncomeSvcEditor::rangeDescEdit [private]
Definition at line 84 of file incomeSvcEditor.h.
QFrame* IncomeSvcEditor::rangeDescFrame [private]
Definition at line 81 of file incomeSvcEditor.h.
QHBoxLayout* IncomeSvcEditor::rangeDescFrameHBoxLayout [private]
Definition at line 82 of file incomeSvcEditor.h.
AccountList* IncomeSvcEditor::rangeEndEdit [private]
Definition at line 80 of file incomeSvcEditor.h.
QVBoxLayout* IncomeSvcEditor::vBoxLayout [private]
Definition at line 64 of file incomeSvcEditor.h.
QVBoxLayout* IncomeSvcEditor::vBoxLayout [private]
Definition at line 45 of file incomeSvcEditor.h.
Referenced by IncomeSvcEditor().
The documentation for this class was generated from the following files:
incomeSvcEditor.h
incomeSvcEditor.cpp