EditorElement Class Reference
#include <editorElement.h>
Signals
void changed (void *)
Public Member Functions
EditorElement (Database::editorCategories newCategory, QString newId, QString newType, QString newDesc, QString newAccountBegin, QString newAccountEnd)
~EditorElement ()
QFrame * getFrame (QWidget *parent, void *section)
Private Slots
void elementUp ()
void elementDown ()
void removeElement ()
Private Attributes
Database::editorCategories category
void * section
Database * db
QString id
QString type
QString desc
QString accountBegin
QString accountEnd
QFrame * frame
QHBoxLayout * layout
QLabel * descLabel
QLabel * accountsLabel
QPushButton * upButton
QPushButton * downButton
QPushButton * removeButton
Constructor & Destructor Documentation
EditorElement::EditorElement (Database::editorCategories newCategory, QString newId, QString newType, QString newDesc, QString newAccountBegin, QString newAccountEnd)
Definition at line 12 of file editorElement.cpp.
References db, and Database::instance().
15     : QObject(), category(newCategory), id(newId), type(newType), desc(newDesc),
16       accountBegin(newAccountBegin), accountEnd(newAccountEnd)
17 {
18     db = Database::instance();
19 }
EditorElement::~EditorElement ()
Definition at line 21 of file editorElement.cpp.
22 {}
Member Function Documentation
void EditorElement::changed (void *) [signal]
Referenced by elementDown(), elementUp(), and removeElement().
void EditorElement::elementDown () [private, slot]
Definition at line 67 of file editorElement.cpp.
References category, changed(), db, Database::moveElement(), and section.
Referenced by getFrame().
68 {
69     db->moveElement(category, id, false);
70     emit changed(section);
71 }
void EditorElement::elementUp () [private, slot]
Definition at line 61 of file editorElement.cpp.
References category, changed(), db, Database::moveElement(), and section.
Referenced by getFrame().
62 {
63     db->moveElement(category, id, true);
64     emit changed(section);
65 }
QFrame * EditorElement::getFrame (QWidget * parent, void * section)
Definition at line 24 of file editorElement.cpp.
References accountBegin, accountEnd, accountsLabel, desc, descLabel, downButton, elementDown(), elementUp(), frame, layout, removeButton, removeElement(), section, type, and upButton.
Referenced by IncomeSvcEditor::listSection(), IncomeRetailEditor::listSection(), and BalanceSheetEditor::listSection().
25 {
26     section = newSection;
27     
28     frame = new QFrame(parent);
29     layout = new QHBoxLayout(frame);
30     descLabel = new QLabel(desc, frame);
31    
32     if(type == "0")
33         accountsLabel = new QLabel(accountBegin, frame);
34     else
35         accountsLabel = new QLabel(accountBegin + " - " + accountEnd, frame);
36     
37     upButton = new QPushButton(
38             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/elementUp.png") ), "", frame);
39     upButton->setFixedSize(28, 28);
40     connect(upButton, SIGNAL(clicked()), this, SLOT(elementUp()));
41     
42     downButton = new QPushButton(
43                 QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/elementDown.png") ), "", frame);
44     downButton->setFixedSize(28, 28);
45     connect(downButton, SIGNAL(clicked()), this, SLOT(elementDown()));
46     
47     removeButton = new QPushButton(
48             QIconSet( QPixmap::fromMimeSource(ICON_PATH + "/elementRemove.png") ), "", frame);
49     removeButton->setFixedSize(28, 28);
50     connect(removeButton, SIGNAL(clicked()), this, SLOT(removeElement()));
51     
52     layout->addWidget(descLabel);
53     layout->addWidget(accountsLabel);
54     layout->addWidget(upButton);
55     layout->addWidget(downButton);
56     layout->addWidget(removeButton);
57     
58     return frame;
59 }
void EditorElement::removeElement () [private, slot]
Definition at line 73 of file editorElement.cpp.
References category, changed(), db, Database::removeElement(), and section.
Referenced by getFrame().
74 {
75     db->removeElement(category, id);
76     emit changed(section);
77 }
Member Data Documentation
QString EditorElement::accountBegin [private]
Definition at line 42 of file editorElement.h.
Referenced by getFrame().
QString EditorElement::accountEnd [private]
Definition at line 43 of file editorElement.h.
Referenced by getFrame().
QLabel* EditorElement::accountsLabel [private]
Definition at line 48 of file editorElement.h.
Referenced by getFrame().
Database::editorCategories EditorElement::category [private]
Definition at line 34 of file editorElement.h.
Referenced by elementDown(), elementUp(), and removeElement().
Database* EditorElement::db [private]
Definition at line 37 of file editorElement.h.
Referenced by EditorElement(), elementDown(), elementUp(), and removeElement().
QString EditorElement::desc [private]
Definition at line 41 of file editorElement.h.
Referenced by getFrame().
QLabel* EditorElement::descLabel [private]
Definition at line 47 of file editorElement.h.
Referenced by getFrame().
QPushButton* EditorElement::downButton [private]
Definition at line 50 of file editorElement.h.
Referenced by getFrame().
QFrame* EditorElement::frame [private]
Definition at line 45 of file editorElement.h.
Referenced by getFrame().
QString EditorElement::id [private]
Definition at line 39 of file editorElement.h.
QHBoxLayout* EditorElement::layout [private]
Definition at line 46 of file editorElement.h.
Referenced by getFrame().
QPushButton* EditorElement::removeButton [private]
Definition at line 51 of file editorElement.h.
Referenced by getFrame().
void* EditorElement::section [private]
Definition at line 35 of file editorElement.h.
Referenced by elementDown(), elementUp(), getFrame(), and removeElement().
QString EditorElement::type [private]
Definition at line 40 of file editorElement.h.
Referenced by getFrame().
QPushButton* EditorElement::upButton [private]
Definition at line 49 of file editorElement.h.
Referenced by getFrame().
The documentation for this class was generated from the following files:
editorElement.h
editorElement.cpp