main.cpp File Reference
#include <qapplication.h>
#include `tabs.h`
#include `database.h`
#include `printer.h`
#include `settings.h`
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 8 of file main.cpp.
References Settings::destroy(), Printer::destroy(), Database::destroy(), Printer::instance(), Database::instance(), and Settings::instance().
9 {
10     QApplication app(argc,argv);
11     
12     Settings *settings = Settings::instance();
13     Database *db = Database::instance();
14     Printer *printer = Printer::instance();
15     
16     Tabs tabs(&app);
17     tabs.show();
18     app.setMainWidget(&tabs);
19     int retVal = app.exec();
20     db->destroy();
21     printer->destroy();
22     settings->destroy();
23     return retVal;
24 }