######################################################################
# Automatically generated by qmake (1.07a) Fri Nov 12 23:22:30 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += gen-glc.cpp
